# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/25_faillure_analysis.missing_lead.ipynb.

# %% auto #0
__all__ = ['get_time_', 'get_label_', 'get_eqp_name', 'create_info_df']

# %% ../../nbs/25_faillure_analysis.missing_lead.ipynb #03c09868
from pathlib import Path
import numpy as np
from fastcore.all import *
from datetime import datetime, timedelta
from fastcore.imports import *  
import os

# %% ../../nbs/25_faillure_analysis.missing_lead.ipynb #fe3df7cf
def get_time_(x):
    return x.split('_')[1][:-2]

# %% ../../nbs/25_faillure_analysis.missing_lead.ipynb #c35dc881
def get_label_(x):
    if 'Missing' in x:
        return 'Missing'
    elif 'Additional' in x:
        return 'Additional'
    elif 'Flying' in x:
        return 'Flying'
    elif 'DeviceSize' in x:
        return 'Problem with Device Size'
    elif 'Turned Device' in x:
        return 'Turned Device'
    elif 'RefImg' and 'Exception' in x:
        return 'Ref Image Exception'
    else:
        return 'No Label'

# %% ../../nbs/25_faillure_analysis.missing_lead.ipynb #d472a4f9
def get_eqp_name(x):
    'Get eqp name from the file name'
    if 'ET3' in Path(x).parent.name.split('_')[-1]:
        return 'ET3'
    elif 'ET2' in Path(x).parent.name.split('_')[-1]:
        return 'ET2'
    else:
        return 'ET4'

# %% ../../nbs/25_faillure_analysis.missing_lead.ipynb #fa118272
def create_info_df(path):
    #path = Path(path)
    fns = list(map(lambda x: x.as_posix(), path.ls() ))
    df = pd.DataFrame(columns=['path','filename', 'label'])
    df['path'] = fns

    nw_df_=(
        df
        .assign(
            filename = lambda x: x['path'].apply(lambda x: Path(x).name),
            label = lambda x: x['filename'].apply(get_label_),
            date_time_str = lambda x: x['filename'].apply(lambda x: x.split('_')[1][:-2]),
            date_time = lambda x: pd.to_datetime(x['date_time_str'], format='%Y%m%d%H%M%S'),
            eqp_name = lambda x: x['path'].apply(get_eqp_name)
            )
        .loc[:, ['path', 'filename', 'label', 'date_time', 'eqp_name']]
    )
    print(nw_df_['label'].value_counts())
    return nw_df_

# %% ../../nbs/25_faillure_analysis.missing_lead.ipynb #8fff4d06
from cv_tools.core import *
from cv_tools.dataset_check import *
