"""Lightweight U-Net designed by expert CV principles for edge/ONNX deployment."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/47_patching.edge_segmentation_model.ipynb.

# %% auto #0
__all__ = ['ConvBnAct', 'SqueezeExcitation', 'InvertedResidual', 'AttentionGate', 'EncoderStage', 'DecoderStage',
           'EdgeAttentionUNet', 'FocalLoss', 'DiceLoss', 'CombinedSegLoss', 'EdgeModelWithPreprocessing',
           'EdgeModelForTraining', 'get_edge_model']

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #4f2a6a3e
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #f947d7c1
class ConvBnAct(nn.Module):
    """Production building block: Conv2d + BatchNorm2d + Activation.
    
    Design decisions (expert consensus):
    - bias=False when followed by BN (BN absorbs the bias term)
    - ReLU6 for edge/quantization friendliness
    - Supports grouped convolutions for depthwise ops
    """
    def __init__(self, in_ch, out_ch, kernel_size=3, stride=1, padding=1, groups=1, act=True):
        super().__init__()
        self.conv = nn.Conv2d(in_ch, out_ch, kernel_size, stride, padding, groups=groups, bias=False)
        self.bn = nn.BatchNorm2d(out_ch)
        self.act = nn.ReLU6(inplace=True) if act else nn.Identity()
    
    def forward(self, x):
        return self.act(self.bn(self.conv(x)))

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #c0ee2888
class SqueezeExcitation(nn.Module):
    """SE block (Hu et al. 2018) — channel attention for edge deployment.
    
    Uses AdaptiveAvgPool2d(1) → FC → ReLU → FC → Sigmoid.
    ONNX opset-12 safe. ~2*C*C/r parameters.
    """
    def __init__(self, channels, reduction=4):
        super().__init__()
        mid = max(channels // reduction, 4)  # floor at 4 to avoid degenerate bottleneck
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.fc1 = nn.Conv2d(channels, mid, 1, bias=True)   # 1x1 conv == FC on pooled
        self.fc2 = nn.Conv2d(mid, channels, 1, bias=True)
        self.act = nn.ReLU6(inplace=True)
    
    def forward(self, x):
        w = self.pool(x)          # (B, C, 1, 1)
        w = self.act(self.fc1(w)) # (B, C//r, 1, 1)
        w = torch.sigmoid(self.fc2(w))  # (B, C, 1, 1)
        return x * w              # channel-wise reweighting

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #2f170713
class InvertedResidual(nn.Module):
    """MobileNetV2 inverted residual block with optional SE and MC-Dropout.
    
    expand(1x1) → depthwise(3x3) → SE → dropout → project(1x1)
    Residual connection when stride=1 and in_ch==out_ch.
    
    Dropout placement: after SE, before projection. This is the recommended
    position for MC Dropout in inverted residuals (Gal & Ghahramani 2016):
    - Late enough to not disrupt depthwise spatial features
    - Early enough to inject stochasticity before the linear projection
    - Dropout2d drops entire channels → uncertainty over feature maps
    """
    def __init__(self, in_ch, out_ch, expand_ratio=2, stride=1, use_se=True, dropout_p=0.0):
        super().__init__()
        mid_ch = int(in_ch * expand_ratio)
        self.use_residual = (stride == 1 and in_ch == out_ch)
        
        layers = []
        # Expand (skip if expand_ratio == 1)
        if expand_ratio != 1:
            layers.append(ConvBnAct(in_ch, mid_ch, kernel_size=1, padding=0))
        
        # Depthwise 3x3
        layers.append(ConvBnAct(mid_ch, mid_ch, kernel_size=3, stride=stride, padding=1, groups=mid_ch))
        
        # Squeeze-and-Excitation
        if use_se:
            layers.append(SqueezeExcitation(mid_ch, reduction=4))
        
        # MC Dropout: applied in expanded space for richer stochasticity
        if dropout_p > 0:
            layers.append(nn.Dropout2d(dropout_p))
        
        # Project (linear — no activation)
        layers.append(ConvBnAct(mid_ch, out_ch, kernel_size=1, padding=0, act=False))
        
        self.block = nn.Sequential(*layers)
    
    def forward(self, x):
        out = self.block(x)
        if self.use_residual:
            out = out + x
        return out

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #0208da75
class AttentionGate(nn.Module):
    """True Attention Gate (Oktay et al. 2018) for skip connections.
    
    Gates encoder features using decoder context BEFORE concatenation.
    Much more effective than post-concat spatial attention.
    ONNX opset-12 compatible.
    """
    def __init__(self, gate_ch, skip_ch, inter_ch=None):
        super().__init__()
        inter_ch = inter_ch or skip_ch // 2
        inter_ch = max(inter_ch, 4)  # safety floor
        
        # 1x1 convs to project gate and skip to same dimensionality
        self.W_g = nn.Conv2d(gate_ch, inter_ch, kernel_size=1, bias=False)
        self.W_x = nn.Conv2d(skip_ch, inter_ch, kernel_size=1, bias=False)
        self.psi = nn.Conv2d(inter_ch, 1, kernel_size=1, bias=True)
        self.bn = nn.BatchNorm2d(1)
        self.relu = nn.ReLU6(inplace=True)
    
    def forward(self, gate, skip):
        # gate: decoder features (coarse), skip: encoder features (fine)
        g = self.W_g(gate)
        x = self.W_x(skip)
        
        # Handle spatial size mismatch (gate is typically smaller)
        if g.shape[2:] != x.shape[2:]:
            g = F.interpolate(g, size=x.shape[2:], mode='bilinear', align_corners=True)
        
        # Additive attention
        attn = self.relu(g + x)
        attn = torch.sigmoid(self.bn(self.psi(attn)))  # (B, 1, H, W)
        
        return skip * attn  # gate the skip connection

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #e2957943
class EncoderStage(nn.Module):
    """Encoder stage: 1-2 inverted residual blocks + downsampling.
    
    First block handles channel change, second (if present) refines features.
    """
    def __init__(self, in_ch, out_ch, n_blocks=1, expand_ratio=2, use_se=True, dropout_p=0.0):
        super().__init__()
        blocks = [InvertedResidual(in_ch, out_ch, expand_ratio=expand_ratio, use_se=use_se, dropout_p=dropout_p)]
        for _ in range(n_blocks - 1):
            blocks.append(InvertedResidual(out_ch, out_ch, expand_ratio=expand_ratio, use_se=use_se, dropout_p=dropout_p))
        self.blocks = nn.Sequential(*blocks)
        self.downsample = nn.MaxPool2d(kernel_size=2, stride=2)
    
    def forward(self, x):
        features = self.blocks(x)     # high-res features (for skip)
        downsampled = self.downsample(features)  # reduced resolution
        return features, downsampled

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #d7a64e5b
class DecoderStage(nn.Module):
    """Decoder stage: upsample + attention-gated skip + 1x1 reduce + inverted residual.
    
    Key design choices:
    1. Attention gate BEFORE concat (true Attention U-Net)
    2. 1x1 channel reduction AFTER concat (critical for keeping params low)
    3. IRB operates at narrow output width, not bloated concat width
    4. Dropout passed through to InvertedResidual for MC Dropout
    
    Without the reduction conv, concat channels (e.g. 128+64=192) get expanded
    by the IRB (192*2=384 mid channels) — this is where the param explosion happens.
    """
    def __init__(self, in_ch, skip_ch, out_ch, expand_ratio=2, use_se=True, dropout_p=0.0):
        super().__init__()
        self.up = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.attn_gate = AttentionGate(gate_ch=in_ch, skip_ch=skip_ch)
        # 1x1 reduction: (in_ch + skip_ch) → out_ch  (critical for param efficiency)
        self.reduce = ConvBnAct(in_ch + skip_ch, out_ch, kernel_size=1, padding=0)
        # IRB now operates at narrow out_ch width (residual-friendly: in==out)
        self.conv = InvertedResidual(out_ch, out_ch, expand_ratio=expand_ratio, use_se=use_se, dropout_p=dropout_p)
    
    def forward(self, x, skip):
        x = self.up(x)
        
        # Handle spatial size mismatch
        diffY = skip.size(2) - x.size(2)
        diffX = skip.size(3) - x.size(3)
        if diffX != 0 or diffY != 0:
            x = F.pad(x, [diffX // 2, diffX - diffX // 2,
                          diffY // 2, diffY - diffY // 2])
        
        # Attention-gated skip connection (gate BEFORE concat)
        skip = self.attn_gate(gate=x, skip=skip)
        x = torch.cat([x, skip], dim=1)
        x = self.reduce(x)  # cut channels: concat → out_ch
        x = self.conv(x)    # refine at narrow width (with residual)
        return x

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #9d325678
class EdgeAttentionUNet(nn.Module):
    """Production-ready lightweight Attention U-Net for edge deployment.
    
    Expert design choices:
    - Inverted residuals (MobileNetV2) instead of double conv blocks
    - True attention gates on skip connections (Oktay 2018)
    - SE channel attention inside residual blocks
    - SAM3-inspired presence head for early-exit on empty patches
    - MC Dropout support: dropout in bottleneck + decoder for uncertainty
    - bias=False before every BatchNorm
    - ReLU6 for INT8 quantization readiness
    - All ops ONNX opset-12 compatible
    
    Presence head (inspired by SAM 3's decoupled presence token):
    - Branches off bottleneck: GAP → Linear(f*4, 1) = ~65 params
    - During training: supervised by has_object = (mask.sum() > 0)
    - During inference: enables early-exit for empty patches
    - Cost: 0.09% parameter overhead, enables ~40% compute savings on empty patches
    
    MC Dropout strategy (Gal & Ghahramani 2016):
    - Dropout placed in bottleneck (highest uncertainty impact) and all decoders
    - Encoder is dropout-free: preserves clean skip connection features
    - At inference: call mc_forward() with N stochastic passes
    - Uncertainty = pixel-wise variance or entropy across passes
    
    Target: ~60-80K parameters, <5ms inference on CPU for 256x256
    """
    def __init__(
        self, 
        in_channels: int = 1,      # grayscale input
        out_channels: int = 1,     # binary segmentation
        init_features: int = 16,   # base channel width
        expand_ratio: int = 2,     # inverted residual expansion
        dropout_p: float = 0.1,    # MC Dropout probability (0 = no dropout)
        presence_threshold: float = 0.0,  # logit threshold for early-exit (0.0 = p=0.5)
    ):
        super().__init__()
        f = init_features  # shorthand
        self.dropout_p = dropout_p
        self.presence_threshold = presence_threshold
        
        # Stem: standard 3x3 conv to lift input channels
        self.stem = ConvBnAct(in_channels, f, kernel_size=3, padding=1)
        
        # Encoder path (NO dropout — keep skip features clean)
        self.enc1 = EncoderStage(f,   f,   n_blocks=1, expand_ratio=expand_ratio, dropout_p=0.0)
        self.enc2 = EncoderStage(f,   f*2, n_blocks=1, expand_ratio=expand_ratio, dropout_p=0.0)
        self.enc3 = EncoderStage(f*2, f*4, n_blocks=1, expand_ratio=expand_ratio, dropout_p=0.0)
        
        # Bottleneck (refine at same width — NO channel expansion)
        self.bottleneck = InvertedResidual(f*4, f*4, expand_ratio=expand_ratio, use_se=True, dropout_p=dropout_p)
        
        # Presence head: "is there an object?" — branches off bottleneck
        # SAM3-inspired: decouple recognition from segmentation
        # GAP(f*4) → Linear(f*4, 1) = f*4 + 1 = 65 params for f=16
        self.presence_head = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),  # (B, f*4, H, W) → (B, f*4, 1, 1)
            nn.Flatten(),             # (B, f*4)
            nn.Linear(f * 4, 1),      # (B, 1) — presence logit
        )
        
        # Decoder path (dropout in all decoders for fine-grained uncertainty)
        self.dec3 = DecoderStage(f*4, f*4, f*4, expand_ratio=expand_ratio, dropout_p=dropout_p)
        self.dec2 = DecoderStage(f*4, f*2, f*2, expand_ratio=expand_ratio, dropout_p=dropout_p)
        self.dec1 = DecoderStage(f*2, f,   f,   expand_ratio=expand_ratio, dropout_p=dropout_p)
        
        # Segmentation head: 1x1 conv, no activation (use BCEWithLogitsLoss)
        self.head = nn.Conv2d(f, out_channels, kernel_size=1)
        
        # Weight initialization (Kaiming for ReLU6 networks)
        self._init_weights()
    
    def _init_weights(self):
        """Kaiming initialization — critical for stable training of deep nets."""
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
    
    def forward(self, x):
        """Forward pass returning segmentation logits and presence logit.
        
        Returns:
            tuple: (seg_logits, presence_logit)
                - seg_logits: (B, out_ch, H, W) — pixel-wise segmentation logits
                - presence_logit: (B, 1) — object presence logit (> 0 means object present)
        """
        # Stem
        x = self.stem(x)
        
        # Encoder
        skip1, x = self.enc1(x)
        skip2, x = self.enc2(x)
        skip3, x = self.enc3(x)
        
        # Bottleneck
        x = self.bottleneck(x)
        
        # Presence head — branch off bottleneck (no gradients blocked)
        presence_logit = self.presence_head(x)  # (B, 1)
        
        # Decoder with attention-gated skips
        x = self.dec3(x, skip3)
        x = self.dec2(x, skip2)
        x = self.dec1(x, skip1)
        
        # Segmentation head (raw logits)
        seg_logits = self.head(x)
        
        return seg_logits, presence_logit
    
    @torch.no_grad()
    def predict_with_early_exit(self, x):
        """Inference with early-exit: skip decoder if no object detected.
        
        For production patch-based inference where most patches are empty.
        Saves ~40% compute on empty patches by skipping the decoder entirely.
        
        Args:
            x: Input tensor (B, C, H, W)  — batch size MUST be 1 for early exit
            
        Returns:
            dict with:
                'seg_logits':  (B, out_ch, H, W) — segmentation logits (zeros if early exit)
                'presence':    (B, 1) — presence logit
                'has_object':  bool — whether object was detected
                'early_exit':  bool — whether decoder was skipped
        """
        self.eval()
        
        # Stem + Encoder + Bottleneck (must run regardless)
        feat = self.stem(x)
        skip1, feat = self.enc1(feat)
        skip2, feat = self.enc2(feat)
        skip3, feat = self.enc3(feat)
        feat = self.bottleneck(feat)
        
        # Presence check
        presence_logit = self.presence_head(feat)
        has_object = (presence_logit > self.presence_threshold).any().item()
        
        if not has_object:
            # Early exit — return zeros without running decoder
            seg_logits = torch.zeros(x.shape[0], 1, x.shape[2], x.shape[3], 
                                      device=x.device, dtype=x.dtype)
            return {
                'seg_logits': seg_logits,
                'presence': presence_logit,
                'has_object': False,
                'early_exit': True,
            }
        
        # Full decoder path
        feat = self.dec3(feat, skip3)
        feat = self.dec2(feat, skip2)
        feat = self.dec1(feat, skip1)
        seg_logits = self.head(feat)
        
        return {
            'seg_logits': seg_logits,
            'presence': presence_logit,
            'has_object': True,
            'early_exit': False,
        }
    
    def enable_mc_dropout(self):
        """Enable dropout layers at inference time for MC Dropout.
        
        Call this before mc_forward(). Sets model to eval mode but
        keeps Dropout2d layers in training mode so they remain active.
        """
        self.eval()  # freeze BN stats
        for m in self.modules():
            if isinstance(m, nn.Dropout2d):
                m.train()  # re-enable dropout
    
    @torch.no_grad()
    def mc_forward(self, x, n_samples=10):
        """Monte Carlo Dropout forward pass for uncertainty estimation.
        
        Runs N stochastic forward passes with dropout enabled,
        then computes mean prediction and pixel-wise uncertainty.
        
        Args:
            x: Input tensor (B, C, H, W)
            n_samples: Number of MC samples (more = better estimate, slower)
            
        Returns:
            dict with:
                'mean_logits': (B, out_ch, H, W) — averaged logits
                'mean_prob':   (B, out_ch, H, W) — averaged sigmoid probabilities
                'uncertainty': (B, out_ch, H, W) — predictive uncertainty (variance of probs)
                'entropy':     (B, out_ch, H, W) — predictive entropy
                'all_probs':   (N, B, out_ch, H, W) — all individual predictions
                'presence':    (B, 1) — averaged presence logit
        """
        self.enable_mc_dropout()
        
        predictions = []
        presence_preds = []
        for _ in range(n_samples):
            seg_logits, presence_logit = self.forward(x)
            probs = torch.sigmoid(seg_logits)
            predictions.append(probs)
            presence_preds.append(presence_logit)
        
        # Stack: (N, B, C, H, W)
        all_probs = torch.stack(predictions, dim=0)
        
        # Mean prediction
        mean_prob = all_probs.mean(dim=0)
        
        # Predictive uncertainty: variance across MC samples
        uncertainty = all_probs.var(dim=0)
        
        # Predictive entropy: H = -p*log(p) - (1-p)*log(1-p)
        eps = 1e-7
        entropy = -(mean_prob * torch.log(mean_prob + eps) + 
                    (1 - mean_prob) * torch.log(1 - mean_prob + eps))
        
        return {
            'mean_logits': mean_prob.logit(eps=eps),  # back to logit space
            'mean_prob': mean_prob,
            'uncertainty': uncertainty,
            'entropy': entropy,
            'all_probs': all_probs,
            'presence': torch.stack(presence_preds, dim=0).mean(dim=0),
        }
    
    # --- ONNX export helpers ---
    def get_input_names(self):  return ['input']
    def get_output_names(self): return ['seg_output', 'presence_output']
    def get_dynamic_axes(self):
        return {
            'input':       {0: 'batch_size', 2: 'height', 3: 'width'},
            'seg_output':  {0: 'batch_size', 2: 'height', 3: 'width'},
            'presence_output': {0: 'batch_size'},
        }
    def get_dummy_input(self, batch_size=1, height=256, width=256):
        return torch.randn(batch_size, 1, height, width)

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #67f46e66
class FocalLoss(nn.Module):
    """Focal Loss (Lin et al. 2017) for handling class imbalance.
    
    FL(p) = -α(1-p)^γ log(p)  for positive class
    
    With γ=2: easy negatives (p≈0 confidently) are downweighted by (1-0)^2=1,
    while hard examples (p≈0.5) get full weight. Perfect for sparse edge masks.
    """
    def __init__(self, alpha=0.25, gamma=2.0):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma
    
    def forward(self, logits, targets):
        bce = F.binary_cross_entropy_with_logits(logits, targets, reduction='none')
        p = torch.sigmoid(logits)
        pt = p * targets + (1 - p) * (1 - targets)  # p if y=1, (1-p) if y=0
        alpha_t = self.alpha * targets + (1 - self.alpha) * (1 - targets)
        focal_weight = alpha_t * (1 - pt) ** self.gamma
        return (focal_weight * bce).mean()


class DiceLoss(nn.Module):
    """Soft Dice Loss — optimizes spatial overlap directly.
    
    smooth term prevents 0/0 on negative (all-background) patches.
    """
    def __init__(self, smooth=1.0):
        super().__init__()
        self.smooth = smooth
    
    def forward(self, logits, targets):
        pred = torch.sigmoid(logits)
        intersection = (pred * targets).sum(dim=(2, 3))
        union = pred.sum(dim=(2, 3)) + targets.sum(dim=(2, 3))
        dice = (2 * intersection + self.smooth) / (union + self.smooth)
        return 1 - dice.mean()


class CombinedSegLoss(nn.Module):
    """Focal + Dice combined segmentation loss."""
    def __init__(self, focal_alpha=0.25, focal_gamma=2.0, dice_smooth=1.0):
        super().__init__()
        self.focal = FocalLoss(alpha=focal_alpha, gamma=focal_gamma)
        self.dice = DiceLoss(smooth=dice_smooth)
    
    def forward(self, logits, targets):
        return self.focal(logits, targets) + self.dice(logits, targets)

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #27eb2482
class EdgeModelWithPreprocessing(nn.Module):
    """Production model: preprocessing + EdgeAttentionUNet.
    
    Wraps the edge-optimized model with the same preprocessing
    pipeline (CLAHE, denoise, bias field correction) for drop-in
    replacement of ModelWithPreprocessing.
    """
    def __init__(
        self, 
        in_channels: int = 1,
        out_channels: int = 1,
        with_clahe: bool = True,
        with_denoise: bool = True,
        with_bias_field_correction: bool = True,
        init_features: int = 16,
        expand_ratio: int = 2,
        dropout_p: float = 0.1,
    ):
        super().__init__()
        self.with_clahe = with_clahe
        self.with_denoise = with_denoise
        self.with_bias_field_correction = with_bias_field_correction
        
        # Reuse existing preprocessing layers
        from new_test.patching.preprocessing_input_image import (
            ONNXFriendlyCLAHEOpset12, GaussianDenoiseLayer, BiasFieldCorrectionLayer
        )
        self.cl = ONNXFriendlyCLAHEOpset12(window_size=8, clip_limit=2.0)
        self.denoise = GaussianDenoiseLayer(kernel_size=5, sigma=1.0, channels=1)
        self.bias_field_correction = BiasFieldCorrectionLayer(in_channels=1, reduction=16)
        
        # Edge-optimized segmentation model
        self.model = EdgeAttentionUNet(
            in_channels=in_channels,
            out_channels=out_channels,
            init_features=init_features,
            expand_ratio=expand_ratio,
            dropout_p=dropout_p,
        )
    
    def forward(self, x):
        if self.with_clahe:
            x = self.cl(x)
        if self.with_denoise:
            x = self.denoise(x)
        if self.with_bias_field_correction:
            x = self.bias_field_correction(x)
        return self.model(x)

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #42d1d84c
class EdgeModelForTraining(nn.Module):
    """Training wrapper for EdgeAttentionUNet with presence-aware loss.
    
    Drop-in replacement for ModelForTraining with the edge-optimized backbone.
    Handles the dual-output (segmentation + presence) architecture:
    - Segmentation loss: user-provided criterion (Focal + Dice recommended)
    - Presence loss: BCE on auto-derived label (mask.sum() > 0)
    - Combined: total = seg_loss + λ * presence_loss
    
    Dropout is active during training (standard regularization) and can be
    re-enabled at inference via mc_forward() for uncertainty estimation.
    """
    def __init__(self, 
                 in_channels=1, 
                 out_channels=1,
                 with_clahe=True,
                 with_denoise=True, 
                 with_bias_field_correction=True,
                 init_features=16,
                 expand_ratio=2,
                 dropout_p=0.1,
                 presence_loss_weight=0.1):
        super().__init__()
        self.presence_loss_weight = presence_loss_weight
        self.model = EdgeModelWithPreprocessing(
            in_channels=in_channels,
            out_channels=out_channels,
            with_clahe=with_clahe,
            with_denoise=with_denoise,
            with_bias_field_correction=with_bias_field_correction,
            init_features=init_features,
            expand_ratio=expand_ratio,
            dropout_p=dropout_p,
        )
        
    def forward(self, x):
        return self.model(x)

    def training_step(self, batch, criterion):
        """Training step with combined segmentation + presence loss.
        
        Args:
            batch: (images, masks) tuple
            criterion: segmentation loss function (e.g. Focal + Dice)
            
        Returns:
            dict with 'total_loss', 'seg_loss', 'presence_loss', 'presence_acc'
        """
        images, masks = batch
        seg_logits, presence_logit = self.forward(images)
        
        # Segmentation loss (user's Focal + Dice)
        seg_loss = criterion(seg_logits, masks)
        
        # Presence loss — auto-derived from mask labels (zero annotation cost)
        # has_object: 1.0 if any foreground pixel, 0.0 if all background
        has_object = (masks.sum(dim=(1, 2, 3)) > 0).float().unsqueeze(1)  # (B, 1)
        presence_loss = F.binary_cross_entropy_with_logits(presence_logit, has_object)
        
        # Combined loss
        total_loss = seg_loss + self.presence_loss_weight * presence_loss
        
        # Presence accuracy for monitoring
        with torch.no_grad():
            presence_pred = (presence_logit > 0).float()
            presence_acc = (presence_pred == has_object).float().mean()
        
        return {
            'total_loss': total_loss,
            'seg_loss': seg_loss,
            'presence_loss': presence_loss,
            'presence_acc': presence_acc,
        }

# %% ../../nbs/47_patching.edge_segmentation_model.ipynb #79728246
def get_edge_model(
    in_channels=1,
    out_channels=1,
    init_features=16,
    expand_ratio=2,
    dropout_p=0.1,
):
    """Factory function for the edge-optimized segmentation model."""
    return EdgeAttentionUNet(
        in_channels=in_channels,
        out_channels=out_channels,
        init_features=init_features,
        expand_ratio=expand_ratio,

        dropout_p=dropout_p,
    )
