"""Remove images of smaller masks"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/48_patching.filter_image_for_smaller_mask.ipynb.

# %% auto #0
__all__ = ['process_single_mask', 'analyze_mask_objects', 'filter_images_based_on_mask_stats', 'main']

# %% ../../nbs/48_patching.filter_image_for_smaller_mask.ipynb #296e62bf
from cv_tools.core import *
from cv_tools.imports import *
from cv_tools.data_processing.smb_tools import *


# %% ../../nbs/48_patching.filter_image_for_smaller_mask.ipynb #653120e9
from platform import system
import polars as pl
from fastcore.all import *
from fastcore.script import *
from concurrent.futures import ProcessPoolExecutor
from multiprocessing import cpu_count

# %% ../../nbs/48_patching.filter_image_for_smaller_mask.ipynb #04ad3d12
def process_single_mask(mask_path):
    """Process a single mask and return object statistics"""
    try:
        # Read binary mask
        mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
        if mask is None:
            return {
                'mask_path': str(mask_path),
                'num_objects': 0,
                'min_pixels': 0,
                'max_pixels': 0,
                'min_area': 0.0,
                'max_area': 0.0
            }
            
        # Find connected components
        num_labels, labels = cv2.connectedComponents(mask)
            
        # Skip background (label 0)
        if num_labels <= 1:
            return {
                'mask_path': str(mask_path),
                'num_objects': 0,
                'min_pixels': 0,
                'max_pixels': 0,
                'min_area': 0.0,
                'max_area': 0.0
            }
            
        # Calculate pixel counts for each object
        pixel_counts = []
        areas = []
            
        for label_id in range(1, num_labels):  # Skip background (0)
            # Count pixels for this object
            pixel_count = np.sum(labels == label_id)
            pixel_counts.append(pixel_count)
                
            # Calculate area (assuming each pixel represents unit area)
            area = float(pixel_count)
            areas.append(area)
            
        return {
            'mask_path': str(mask_path),
            'num_objects': len(pixel_counts),
            'min_pixels': min(pixel_counts) if pixel_counts else 0,
            'max_pixels': max(pixel_counts) if pixel_counts else 0,
            'min_area': min(areas) if areas else 0.0,
            'max_area': max(areas) if areas else 0.0
        }
            
    except Exception as e:
        print(f"Error processing {mask_path}: {e}")
        return {
            'mask_path': str(mask_path),
            'num_objects': 0,
            'min_pixels': 0,
            'max_pixels': 0,
            'min_area': 0.0,
            'max_area': 0.0
        }
    

# %% ../../nbs/48_patching.filter_image_for_smaller_mask.ipynb #cd73244f
def analyze_mask_objects(
        mask_paths, 
        n_workers=None
        ):
    """Analyze binary masks to extract object statistics.
    
    Args:
        mask_paths: List of paths to binary mask images
        n_workers: Number of parallel workers (defaults to cpu_count)
    
    Returns:
        polars.DataFrame with columns: mask_path, num_objects, min_pixels, max_pixels, min_area, max_area
    """
    
    if n_workers is None:
        n_workers = cpu_count() -2
    
    # Process masks in parallel
    with ProcessPoolExecutor(max_workers=n_workers) as executor:
        results = list(executor.map(process_single_mask, mask_paths))
    
    # Create polars DataFrame
    df = pl.DataFrame(results)
    return df


# %% ../../nbs/48_patching.filter_image_for_smaller_mask.ipynb #624d8fe3
def filter_images_based_on_mask_stats(
        image_paths, 
        mask_paths, 
        thresh_pixels=390
        ):
    """Filter images based on mask statistics.
    
    """
    if not isinstance(image_paths, list) and not isinstance(image_paths, L):
        image_paths = Path(image_paths).ls()
    if not isinstance(mask_paths, list) and not isinstance(mask_paths, L):
        mask_paths = Path(mask_paths).ls()

    img_folder = Path(image_paths[0]).parent
    msk_folder = Path(mask_paths[0]).parent
    print(f' Image folder: {img_folder} and \nmask folder: {msk_folder}')

    print(f"Analyzing {len(mask_paths)} masks")
    mask_stats_df = analyze_mask_objects(mask_paths)
    smaller_pins = mask_stats_df.filter((pl.col('min_area') < thresh_pixels) & (pl.col('max_area') < thresh_pixels))
    print(f"Found {len(smaller_pins)} masks with area less than {thresh_pixels} pixels")
    smaller_pins_mask_paths = smaller_pins['mask_path'].to_list()



    smaller_pin_names = [Path(mask_path).name for mask_path in smaller_pins_mask_paths]
    smaller_pins_image_paths = list(filter(lambda x: x.name in smaller_pin_names, image_paths))
    # Get all image paths that are NOT in the smaller pins list
    print(f'Found {len(smaller_pins_image_paths)} smaller pin images')
    curated_image_names = list(filter(lambda x: Path(x).name not in smaller_pin_names, image_paths))
    curated_image_names = [Path(x).name for x in curated_image_names]
    print(f'Found {len(curated_image_names)} curated images')
    
    # Create curated folder paths
    curated_img_folder = Path(image_paths[0]).parent.parent / "curated_images"
    curated_mask_folder = Path(mask_paths[0]).parent.parent / "curated_masks"
    print(f'{curated_img_folder} and {curated_mask_folder} will be created if not exist')
    curated_img_folder.mkdir(exist_ok=True)
    curated_mask_folder.mkdir(exist_ok=True)
    print(f'Now creating curated folders, copying images and masks')
    
    # Copy curated images and masks in parallel
    from concurrent.futures import ThreadPoolExecutor
    import shutil
    
    def copy_file_pair(img_name):
        # Find source paths
        #src_img = next((p for p in image_paths if Path(p).name == img_name), None)
        #src_mask = next((p for p in mask_paths if Path(p).name == img_name), None)
        src_img = Path(img_folder, img_name)
        src_mask = Path(msk_folder, img_name)
		
        
        if src_img and src_mask:
            # Copy to curated folders
            shutil.copy2(src_img, curated_img_folder / img_name)
            shutil.copy2(src_mask, curated_mask_folder / img_name)
            return True
        return False
    
    with ThreadPoolExecutor(max_workers=os.cpu_count()-1) as executor:
        results = list(tqdm(executor.map(copy_file_pair, curated_image_names), total=len(curated_image_names), desc="Copying files"))
    
    print(f"Copied {sum(results)} curated image-mask pairs to {curated_img_folder}")
    return smaller_pins_image_paths


# %% ../../nbs/48_patching.filter_image_for_smaller_mask.ipynb #8436eb86
@call_parse
def main(
    image_paths: Param(type=str, help='Path to the image folder')='images_paths',
    mask_paths: Param(type=str, help='Path to the mask folder')='masks_paths',
    thresh_pixels: Param(type=int, help='Threshold for the number of pixels in the mask') = 390
):
    filter_images_based_on_mask_stats(image_paths, mask_paths, thresh_pixels)
