"""Inference with model with tiling+untiling"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/49_patching.inference_batch_image.ipynb.

# %% auto #0
__all__ = ['CV_TOOLS', 'front', 'current_lib', 'dilation_pt', 'erosion_pt', 'load_end_test_model_only_model',
           'load_end_test_model', 'TiledInferenceModel', 'TiledInferenceModelv2', 'frm_im22im1',
           'process_image_im1_im2_j', 'TwoImageModelPyTorch', 'create_two_image_model_pytorch', 'export_to_onnx',
           'load_whole_pipeline_model', 'InferenceTwoImageDataset', 'segmentation_collate_fn', 'create_pin_dl',
           'post_process_mask', 'predict_batch', 'split_images_into_chunks', 'create_bash_script_content',
           'generate_tflex_commands', 'load_file_list', 'process_image_pair_chunks', 'main_']

# %% ../../nbs/49_patching.inference_batch_image.ipynb #a4bd3c4e
from socket import gethostname
from typing import Callable, Tuple,List,Dict,Any
from fastcore.script import *
from fastcore.all import *
from fastprogress import progress_bar
import json


# %% ../../nbs/49_patching.inference_batch_image.ipynb #b34863e9
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from torchvision.datasets import ImageFolder
from torchvision.transforms import ToTensor
from torchvision.transforms.functional import to_tensor
from torchvision.transforms.functional import to_pil_image
from torchvision.transforms.functional import to_tensor

# %% ../../nbs/49_patching.inference_batch_image.ipynb #9e62f73b
CV_TOOLS = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools')
front = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/private_front_easy_pin_detection')
current_lib = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/new_test')
sys.path.append(str(CV_TOOLS))
sys.path.append(str(front))
sys.path.append(str(current_lib))

# %% ../../nbs/49_patching.inference_batch_image.ipynb #9a9b296a
import torch
from torch.nn import functional as F
from torchvision.transforms.functional import to_pil_image, to_grayscale, to_tensor


# %% ../../nbs/49_patching.inference_batch_image.ipynb #71ace8e5
from cv_tools.core import *
from cv_tools.imports import *
from cv_tools.data_processing.smb_tools import *


# %% ../../nbs/49_patching.inference_batch_image.ipynb #25f1af83
from private_front_easy_pin_detection.model_eval.chunking_batch_prediction import *


# %% ../../nbs/49_patching.inference_batch_image.ipynb #cdd8357a
from new_test.viz_utils import *


# %% ../../nbs/49_patching.inference_batch_image.ipynb #ea64bcbe
def dilation_pt(
    x, 
    iteration=1,
    kernel_size=3,
    padding=None):
    for i in range(iteration):
        x = F.max_pool2d(
            x,
            kernel_size=kernel_size,
            stride=1,
            padding=padding)
    return x
        
        

# %% ../../nbs/49_patching.inference_batch_image.ipynb #e648fd04
def erosion_pt(
               x,
               iteration=1,
               kernel_size=3,
                padding=None,
                ):
    neg_ = -x
    for i in range(iteration):
        
    
        neg_ = F.max_pool2d(
            neg_,
            kernel_size=kernel_size,
            stride=1,
            padding=padding)
    return - neg_



# %% ../../nbs/49_patching.inference_batch_image.ipynb #d85c5798
from torchvision.transforms.functional import to_pil_image

# %% ../../nbs/49_patching.inference_batch_image.ipynb #5ba88eb8
from new_test.patching.model_development import *
from new_test.patching.preprocessing_input_image import *
from new_test.patching.edge_segmentation_model import *
#from new_test.patching.training_pytorch import *

# %% ../../nbs/49_patching.inference_batch_image.ipynb #027de5c9
import torch

# %% ../../nbs/49_patching.inference_batch_image.ipynb #4b114d24
def load_end_test_model_only_model(
		in_channels=1, # Input channels
		out_channels=1, # Output channels
		model_path:str='/path/to/model', # Model path
		map_location:str='cpu', # Map location
		edge_model:bool=False, # Edge model
		dropout_p:float=0.1 # Dropout probability
		):
	"Load a trained end test model for inference"
	if edge_model:
		model_ = EdgeAttentionUNet(
			in_channels=in_channels,
			out_channels=out_channels,
			dropout_p=dropout_p
		)
	else:
		model_ = LightweightAttentionUNet(
			in_channels=in_channels,
			out_channels=out_channels
		)
	print(f'CUDA available: {torch.cuda.is_available()}')
	print(f" {'#'*100}")
	print(f'Loading model from {model_path} using {map_location} as map location')
	device = torch.device(map_location)
	print(f" {'#'*100}")
	checkpoint = torch.load(
		model_path, 
		map_location=device, 
		weights_only=False)
	model_.load_state_dict(
		checkpoint['model_state_dict']
	)
	model_.eval()
		
			
	return model_


# %% ../../nbs/49_patching.inference_batch_image.ipynb #e93ab536
def load_end_test_model(
		in_channels=1,
		out_channels=1,
		with_clahe:bool=True,
		with_denoise:bool=True,
		with_bias_field_correction:bool=True,
		training:bool=True,
		model_path:str='/path/to/model',
		map_location:str='cpu'



		
		):
	"Load a trained end test model for inference"
	model_ = get_end_test_model(
		in_channels=in_channels,
		out_channels=out_channels,
		with_clahe=with_clahe,
		with_denoise=with_denoise,
		with_bias_field_correction=with_bias_field_correction,
		training=training,
	)
	checkpoint = torch.load(model_path, map_location=map_location, weights_only=False)
	model_.load_state_dict(
		checkpoint['model_state_dict']
	)
	model_.eval()
		
			
	return model_


# %% ../../nbs/49_patching.inference_batch_image.ipynb #894129d6
from new_test.viz_utils import *

# %% ../../nbs/49_patching.inference_batch_image.ipynb #70b293bf
class TiledInferenceModel(nn.Module):
    def __init__(
            self, 
            model, 
            tile_size=256, 
            overlap=32, 
            merge_strategy='confidence_weighted', 
            confidence_threshold=0.5):
        super().__init__()
        self.model = model
        self.tile_size = tile_size
        self.overlap = overlap
        self._tiling= TileProcessorv4(
            tile_size=tile_size,
            overlap=overlap,
        )
        self._tile_merger = TileMergerv4(
            merge_strategy=merge_strategy,
            confidence_threshold=confidence_threshold
        )

    def forward(self, x):
        # Expected x shape: (batch_size, channels, height, width) e.g., (1, 2, 1152, 1632)
        with torch.no_grad():
            tiles, positions = self._tiling(x)
            print(f' tiles has a shape of {tiles.shape}')
            print(f'Tile size: {tiles[0].shape} \n num tiles: {len(tiles)}')
            tiled_predictions = self.model(tiles)
            if isinstance(tiled_predictions, tuple):
                tiled_predictions = tiled_predictions[0]
            pred_x = self._tile_merger(
                            tiled_predictions, 
                            positions,
                            x.shape[2], x.shape[3])
            return pred_x

# %% ../../nbs/49_patching.inference_batch_image.ipynb #0ef950b8
class TiledInferenceModelv2(nn.Module):
    def __init__(
            self, 
            model, 
            tile_size=256, 
            overlap=32, 
            merge_strategy='confidence_weighted', 
            confidence_threshold=0.5):
        super().__init__()
        self.model = model
        self.tile_size = tile_size
        self.overlap = overlap
        self._tiling= TileProcessorv4(
            tile_size=tile_size,
            overlap=overlap,
        )
        self._tile_merger = TileMergerv4(
            merge_strategy=merge_strategy,
            confidence_threshold=confidence_threshold
        )

    def forward(self, x):
        with torch.no_grad():
            tiles, positions = self._tiling(x)
            tiled_predictions = self.model(tiles)
            if isinstance(tiled_predictions, tuple):
                tiled_predictions = tiled_predictions[0]
            pred_x = self._tile_merger(
                            tiled_predictions, 
                            positions,
                            x.shape[2], x.shape[3])
            return pred_x

# %% ../../nbs/49_patching.inference_batch_image.ipynb #bb87d098
def frm_im22im1(
    fn:str
    ):
    'Remove image2 from the filename and return image1-> find same image1 and image2'
    return Path(fn).name.replace('image2', 'image1')

# %% ../../nbs/49_patching.inference_batch_image.ipynb #be97c0e0
def process_image_im1_im2_j(
    im2:np.ndarray,
    im1:np.ndarray
   )->[Tuple[np.ndarray, np.ndarray]]: # return two image of shape (None, 2, 1152, 1632)
    'process image 1 and image2 to make it work with two image model'
    #if len(im1.shape) <3:
        #im1 = np.expand_dims(im1, axis=-1)
        #print(im1.shape)
    #if len(im2.shape) <3:
        #im2 = np.expand_dims(im2, axis=-1)
        #print(im2.shape)



    im1 = im1.astype(np.float32)/255.0
    im2 = im2.astype(np.float32)/255.0
    p_img = np.stack((im1, im2), axis=-1)[None,...]
    return torch.from_numpy(p_img).permute(0,3,1,2)

# %% ../../nbs/49_patching.inference_batch_image.ipynb #86da8d64
def erosion_pt(
               x,
               iteration=1,
               kernel_size=3,
                padding=None,
                ):
    neg_ = -x
    for i in range(iteration):
        
    
        neg_ = F.max_pool2d(
            neg_,
            kernel_size=kernel_size,
            stride=1,
            padding=padding)
    return - neg_



# %% ../../nbs/49_patching.inference_batch_image.ipynb #526e866a
def dilation_pt(
    x, 
    iteration=1,
    kernel_size=3,
    padding=None):
    for i in range(iteration):
        x = F.max_pool2d(
            x,
            kernel_size=kernel_size,
            stride=1,
            padding=padding)
    return x
        
        

# %% ../../nbs/49_patching.inference_batch_image.ipynb #57771585
class TwoImageModelPyTorch(nn.Module):
    """PyTorch implementation of two-image model compatible with ONNX opset 12"""
    
    def __init__(
        self,
        base_model: nn.Module,
        im1_threshold: float = 0.3,
        pred_threshold: float = 0.5,
        dilation_iteration_rev: int = 2,
        dilation_iteration: int = 2
    ):
        super().__init__()
        self.base_model = base_model
        self.im1_threshold = im1_threshold
        self.pred_threshold = pred_threshold
        self.dilation_iteration_rev = dilation_iteration_rev
        self.dilation_iteration = dilation_iteration
        
        # Define morphological operations using MaxPool2d for dilation
        self.dilation_kernel = nn.MaxPool2d(
            kernel_size=3, 
            stride=1, 
            padding=1
        )
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward pass for two-image model
        Args:
            x: Input tensor of shape (B, 2, H, W) where channel 0 is image1, channel 1 is image2
        Returns:
            Output tensor of shape (B, 1, H, W)
        """
        # Split input into image1 and image2
        image1 = x[:, 0:1, :, :]  # Shape: (B, 1, H, W)
        image2 = x[:, 1:2, :, :]  # Shape: (B, 1, H, W)
        
        # Apply threshold to image1 (ONNX-compatible)
        image1_thresh = torch.where(
            image1 > self.im1_threshold,
            torch.ones_like(image1),
            torch.zeros_like(image1)
        )
        
        # Get model prediction on image2
        model_out = self.base_model(image2)
        
        # Apply threshold to model output (ONNX-compatible)
        model_out_thresh = torch.where(
            model_out >= self.pred_threshold,
            torch.ones_like(model_out),
            torch.zeros_like(model_out)
        )
        
        # Multiply model output with thresholded image1
        output = model_out_thresh * image1_thresh
        
        # Reverse dilation: negate output
        revers = -output
        
        # Apply dilation iterations (reverse)
        for _ in range(self.dilation_iteration_rev):
            revers = self.dilation_kernel(revers)
        
        # Negate back
        output = -revers
        
        # Apply final dilation iterations
        for _ in range(self.dilation_iteration):
            output = self.dilation_kernel(output)
        
        # Final multiplication with original model output
        final_output = model_out_thresh * output

        # final removal of small objects + fill the whole
        kernel_size=3
        padding=kernel_size//3
        # dilation 2 times to fill holes
        dilated_msk = dilation_pt(
            final_output, 
           kernel_size=kernel_size,
           padding=padding,
           iteration=2)

        # erosion 4 times to remove small objects
        eroted_msk = erosion_pt(
                    dilated_msk,
                    kernel_size=kernel_size,
                   padding=padding,
                   iteration=4)
        # dilation again 2 times to make same size
        dialted_msk2 = dilation_pt(
                        eroted_msk,
                        kernel_size=kernel_size,
                        padding=padding,
                        iteration=2)
        
        return dialted_msk2
        

def create_two_image_model_pytorch(
    base_model: nn.Module,
    im1_threshold: float = 0.3,
    pred_threshold: float = 0.5,
    dilation_iteration_rev: int = 2,
    dilation_iteration: int = 2,
    save_path: str = None
) -> TwoImageModelPyTorch:
    """
    Create PyTorch two-image model from base model
    
    Args:
        base_model: Base PyTorch model for single image inference
        im1_threshold: Threshold for image1 binarization
        pred_threshold: Threshold for model prediction binarization
        dilation_iteration_rev: Number of reverse dilation iterations
        dilation_iteration: Number of final dilation iterations
        save_path: Optional path to save the model
    
    Returns:
        TwoImageModelPyTorch instance
    """
    model = TwoImageModelPyTorch(
        base_model=base_model,
        im1_threshold=im1_threshold,
        pred_threshold=pred_threshold,
        dilation_iteration_rev=dilation_iteration_rev,
        dilation_iteration=dilation_iteration
    )
    
    if save_path is not None:
        print('=' * 42)
        print('Model saving started')
        Path(save_path).parent.mkdir(parents=True, exist_ok=True)
        torch.save(model.state_dict(), save_path)
        print('Model saving done')
        print('=' * 42)
    
    return model


# %% ../../nbs/49_patching.inference_batch_image.ipynb #64886538
def export_to_onnx(
    model: nn.Module,
    input_shape: tuple = (1, 2, 1152, 1632),
    onnx_path: str = None,
    opset_version: int = 12
):
    """
    Export PyTorch model to ONNX format
    
    Args:
        model: PyTorch model to export
        input_shape: Input tensor shape (B, C, H, W)
        onnx_path: Path to save ONNX model
        opset_version: ONNX opset version (default: 12)
    """
    model.eval()
    dummy_input = torch.randn(*input_shape)
    
    torch.onnx.export(
        model,
        dummy_input,
        onnx_path,
        export_params=True,
        opset_version=opset_version,
        do_constant_folding=True,
        input_names=['input'],
        output_names=['output'],
        dynamic_axes={
            'input': {0: 'batch_size'},
            'output': {0: 'batch_size'}
        }
    )
    print(f'Model exported to ONNX: {onnx_path}')

# %% ../../nbs/49_patching.inference_batch_image.ipynb #3cb2e076
def load_whole_pipeline_model(
    model_path: str,
    in_channels:int=1,
    out_channels:int=1,
    tile_size:int=256,
    overlap:int=32,
    im1_threshold:float=0.3,
    pred_threshold:float=0.5,
    dilation_iteration_rev:int=2,
    dilation_iteration:int=2,
    map_location: str = 'cpu',
    edge_model:bool=False,
    dropout_p:float=0.1,
    convert_to_onnx: bool = False,
    onnx_path: str = None,
    opset_version: int = 12,
    input_shape: tuple = (1, 2, 1152, 1632)
):
    "Load the whole pipeline model with optional ONNX conversion"
    model_ = load_end_test_model_only_model(
        in_channels=in_channels,
        out_channels=out_channels,
        model_path=model_path,
        map_location=map_location,
        edge_model=edge_model,
        dropout_p=dropout_p
    )
    tiled_model = TiledInferenceModel(
        model=model_,
        tile_size=tile_size,
        overlap=overlap
    )
    two_img_model = create_two_image_model_pytorch(
        base_model=tiled_model,
        im1_threshold=im1_threshold,
        pred_threshold=pred_threshold,
        dilation_iteration_rev=dilation_iteration_rev,
        dilation_iteration=dilation_iteration
    )
    two_img_model.eval()
    
    # Convert to ONNX if requested
    if convert_to_onnx:
        if onnx_path is None:
            onnx_path = f"{Path(model_path).stem}_whole_pipeline.onnx"
        
        export_to_onnx(
            model=two_img_model,
            input_shape=input_shape,
            onnx_path=onnx_path,
            opset_version=opset_version
        )
    
    return two_img_model

# %% ../../nbs/49_patching.inference_batch_image.ipynb #cad5f041
class InferenceTwoImageDataset(Dataset):
	def __init__(
			self, 
			im1_files:list, 
			im2_files:list,
			transform:Callable=None,
			img_size:tuple=(1152,1632),
			max_tries:int=2
			):
		store_attr()
		
		# Find common files between im1 and im2 based on filename matching
		self._find_common_files(im1_files, im2_files)
		
		self.im1_path = Path(im1_files[0]).parent
		self.im2_path = Path(im2_files[0]).parent
		self.max_tries = max_tries
		
		if transform is None:
			self.transform = transforms.Compose([
				transforms.Resize(img_size),
				transforms.ToTensor()
			])
		else:
			self.transform = transform

	def _find_common_files(self, im1_files:list, im2_files:list):
		"""Find common files between im1 and im2 directories based on filename matching"""
		# Extract base names for comparison
		im1_names = {Path(f).name.replace('image1', 'image2'): f for f in im1_files}
		im2_names = {Path(f).name: f for f in im2_files}
		
		# Find intersection
		common_names = set(im1_names.keys()) & set(im2_names.keys())
		
		# Create matched pairs
		self.im1_files = [im1_names[name] for name in common_names]
		self.im2_files = [im2_names[name] for name in common_names]
		
		# Sort to ensure consistent ordering
		paired_files = list(zip(self.im1_files, self.im2_files))
		paired_files.sort(key=lambda x: Path(x[1]).name)
		self.im1_files, self.im2_files = zip(*paired_files) if paired_files else ([], [])
		self.im1_files, self.im2_files = list(self.im1_files), list(self.im2_files)
		
		# Log the results
		total_im1 = len(im1_files)
		total_im2 = len(im2_files)
		common_count = len(self.im1_files)
		
		print(f"Dataset Statistics:")
		print(f"  Total image1 files: {total_im1}")
		print(f"  Total image2 files: {total_im2}")
		print(f"  Common paired files: {common_count}")
		print(f"  Missing pairs: {max(total_im1, total_im2) - common_count}")
		
		if common_count == 0:
			raise ValueError("No common files found between im1 and im2 directories!")
		
		if common_count < min(total_im1, total_im2):
			print(f"Warning: Only {common_count}/{min(total_im1, total_im2)} files have pairs")

	__repr__ = basic_repr(['im1_path', 'im2_path', 'num_pairs'])
	
	@property
	def num_pairs(self):
		return len(self.im1_files)

	def __len__(self):
		return len(self.im1_files)
		
	def __getitem__(self, idx):
		im1_file = self.im1_files[idx]
		im2_file = self.im2_files[idx]

		for attempt in range(self.max_tries):
			try:
				im1_img = Image.open(im1_file).convert('L')
				im2_img = Image.open(im2_file).convert('L')

				im1_img = self.transform(im1_img)
				im2_img = self.transform(im2_img)
				original_size = im2_img.size
				comb_img = torch.cat((im1_img, im2_img), dim=0)

				if torch.isnan(comb_img).any() or torch.isinf(comb_img).any():
					raise ValueError(f'Invalid image pair {im1_file} & {im2_file}')
			
				return {
					'image': comb_img,
					'im1_file': str(im1_file),
					'im2_file': str(im2_file),
					'original_size': original_size,
					'attempt':attempt
				}

			except Exception as e:
				print(f'Error loading image pair {im1_file} & {im2_file}: {e}')
				if attempt == self.max_tries - 1:
					dummy_tensor = torch.zeros(2, *self.transform.transforms[0].size[::-1])
					return {
						'image': dummy_tensor,
						'im1_file': str(im1_file),
						'im2_file': str(im2_file),
						'error': True
					}


# %% ../../nbs/49_patching.inference_batch_image.ipynb #12b93431
def segmentation_collate_fn(
        batch: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Custom collate function for medical image segmentation batch processing.
    
    Handles:
    - Variable image sizes
    - Error cases (corrupted images)
    - Metadata preservation
    
    Args:
        batch: List of dictionaries from ImageDataset.__getitem__()
               Each dict contains: {'image': tensor, 'path': str, 'original_size': tuple, 'error': bool (optional)}
    
    Returns:
        Dict containing batched data with proper error handling
    """
    
    # Separate valid and error samples
    non_corrupted_samples = []
    corrupted_samples = []
    
    for i, sample in enumerate(batch):
        if sample.get('error', False):
            corrupted_samples.append((i, sample))
        else:
            non_corrupted_samples.append((i, sample))
    
    # If no valid samples, return error batch
    if not non_corrupted_samples:
        return {
            'image': torch.stack([sample['image'] for _, sample in corrupted_samples]),
            'path': [sample['path'] for _, sample in corrupted_samples],
            'original_size': [sample['original_size'] for _, sample in corrupted_samples],
            'batch_indices': [i for i, _ in corrupted_samples],
            'all_errors': True,
            'non_corrupted_samples': torch.zeros(len(batch), dtype=torch.bool)
        }
    
    # Process valid samples
    images = []
    im1_paths = []
    im2_paths = []
    original_sizes = []
    batch_indices = []
    
    for i, sample in non_corrupted_samples:
        images.append(sample['image'])
        im1_paths.append(sample['im1_file'])
        im2_paths.append(sample['im2_file'])
        original_sizes.append(sample['original_size'])
        batch_indices.append(i)
    
    # Stack images (assumes same size after transform)
    try:
        stacked_images = torch.stack(images)
    except Exception as e:
        # Handle different sizes by padding to max size
        print(f"Warning: Image size mismatch in batch, applying padding: {e}")
        stacked_images = pad_images_to_same_size(images)
    
    # Create validity mask for the entire batch
    valid_mask = torch.zeros(len(batch), dtype=torch.bool)
    for i, _ in non_corrupted_samples:
        valid_mask[i] = True
    
    # Prepare batch dictionary
    collated_batch = {
        'image': stacked_images,
        'im1_file': im1_paths,
        'im2_file': im2_paths,
        'original_size': original_sizes,
        'batch_indices': batch_indices,
        'valid_mask': valid_mask,
        'all_errors': False
    }
    
    # Add error information if there are any
    if corrupted_samples:
        collated_batch['error_indices'] = [i for i, _ in corrupted_samples]
        collated_batch['error_paths'] = [sample['path'] for _, sample in corrupted_samples]
        collated_batch['has_errors'] = True
    else:
        collated_batch['has_errors'] = False
    
    return collated_batch

# %% ../../nbs/49_patching.inference_batch_image.ipynb #f821e3dc
def create_pin_dl(
    ds: Dataset,
    shuffle: bool = False,
    num_workers: int = 0,
    collate_fn: Callable = segmentation_collate_fn,
    pin_memory: bool = True,
    batch_size: int = 1,
):
    'Create dataloader based on dataset'
    dataloader_ = DataLoader(
        ds,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=pin_memory,
        collate_fn=collate_fn,
        persistent_workers=num_workers > 0,
        prefetch_factor=2 if num_workers > 0 else None
    )
    return dataloader_

# %% ../../nbs/49_patching.inference_batch_image.ipynb #f348e835
def post_process_mask(
		mask:np.ndarray, 
		threshold:float=0.5,
		original_size:tuple=None)->Image.Image: # So image size will be width, height
	"""
	Post process the mask and convert to pil image (to 255 scale)
	"""

	if isinstance(mask, torch.Tensor):
		pred = mask.detach().cpu().numpy()

	#print(f' len(pred.shape): {len(pred.shape)} and pred.shape[0]=: {pred.shape[0]}')

	# Handle multi-class
	if len(pred.shape) == 3 and pred.shape[0] > 1:
		pred_ = np.argmax(pred, axis=0)

	# single class

	elif len(pred.shape) == 3 and pred.shape[0] == 1:
		pred_ = pred[0]

	# In case of not thresholded
	if pred_.dtype in [np.float32, np.float64]:
		pred_ = (pred_ > threshold).astype(np.uint8) * 255

	# Convert to pil image
	mask_ = Image.fromarray(pred_)
	if original_size is not None:
		mask_ = mask_.resize(original_size, resample=Image.Resampling.NEAREST)
	return mask_


# %% ../../nbs/49_patching.inference_batch_image.ipynb #613559c6
def predict_batch(
        image_batch:dict, # dictionary with image and im2_file
		model:nn.Module, # model to use for prediction Normally two image model
		device:str='cpu', # device to use for prediction
		output_dir:str=None, # directory to save the results
		post_process:bool=True, # if True, post process the mask
		threshold:float=0.5, # threshold for post processing
		original_size:tuple=None, # original size of the image
		print_stats:bool=False # if True, print the stats of the mask
	):
	'Process each batch and save the results'

	batch_res = []
	images = image_batch['image'].to(device)
	print(images.shape)
	model = model.to(device)
	im2_files = image_batch['im2_file']

	with torch.no_grad():
		predictions = model(images)
		#print(f'prediction type: {type(predictions)}')
		#if isinstance(predictions, (list, tuple, torch.Tensor)):
			#preds = predictions[0]
		#elif isinstance(predictions, dict):
			#preds = predictions['out']

		# process each file
		for i in range(len(im2_files)):
			if 'error' in image_batch and i < len(image_batch.get('error',[])) :
				continue
			try:
				# Get prediction for this image
				pred = predictions[i]

				# if in case of post processing
				mask = post_process_mask(
					pred,
					threshold=threshold,
					original_size=original_size
				)
				# Print mask statistics
				mask_array = np.array(mask)
				unique_vals, counts = np.unique(mask_array, return_counts=True)
				total_pixels = mask_array.size

				im_path = im2_files[i]
				if print_stats:
					print(f"Mask stats for {Path(im_path).name}:")
					print(f"  Shape: {mask_array.shape}")
					print(f"  Unique values: {unique_vals}")
					print(f"  Pixel counts: {dict(zip(unique_vals, counts))}")
					print(f"  Foreground ratio: {counts[-1]/total_pixels:.4f}" if len(counts) > 1 else "  No foreground pixels")

				# Save the mask
				basename = Path(im_path).stem
				if output_dir is None:
					output_dir = 'data'
				
				output_path = Path(output_dir, f'{basename}.png')
				Path(output_path).parent.mkdir(parents=True, exist_ok=True)
				mask.save(output_path)
				batch_res.append({
					'input': im_path,
					'output': output_path,
					'status': 'success'
				})
			except Exception as e:
				batch_res.append({
					'input': im_path,
					'output': None,
					'status': 'error',
					'error': e
				})

	return batch_res

# %% ../../nbs/49_patching.inference_batch_image.ipynb #e404dd77
def split_images_into_chunks(
        im1_folder, # folder containing Image1 files
        im2_folder, # folder containing Image2 files
        images_per_job=50, # number of image pairs per job
        image_extensions=['.jpg', '.jpeg', '.png', '.tiff', '.bmp'], # image file extensions to include
        recursive=True)->List[List[Dict[str, str]]]: # search subfolders recursively
    """
    Split paired images into chunks for parallel processing
    
    
    """
    print("🔄 Step 1: Splitting images into chunks...")
    
    im1_path = Path(im1_folder)
    im2_path = Path(im2_folder)
    
    # Collect all im1 images
    im1_images = []
    for ext in image_extensions:
        if recursive:
            im1_images.extend(im1_path.rglob(f"*{ext}"))
            im1_images.extend(im1_path.rglob(f"*{ext.upper()}"))
        else:
            im1_images.extend(im1_path.glob(f"*{ext}"))
            im1_images.extend(im1_path.glob(f"*{ext.upper()}"))
    
    # Create paired image list
    paired_images = []
    for im1_file in im1_images:
        # Convert Image1 filename to Image2 filename
        im2_filename = im1_file.name.replace('image1', 'image2')
        im2_file = im2_path / im2_filename
        
        # Only include pairs where both files exist
        if im2_file.exists():
            paired_images.append({
                'im1': str(im1_file),
                'im2': str(im2_file)
            })
        else:
            print(f"Warning: Missing pair for {im1_file.name} -> {im2_filename}")
    
    if not paired_images:
        print(f"No paired images found between {im1_folder} and {im2_folder}")
        return []
    
    # Split into chunks
    chunks = []
    for i in range(0, len(paired_images), images_per_job):
        chunk = paired_images[i:i + images_per_job]
        chunks.append(chunk)
    
    print(f"Found {len(paired_images)} image pairs")
    print(f"Split into {len(chunks)} chunks of ~{images_per_job} pairs each")
    
    return chunks

# %% ../../nbs/49_patching.inference_batch_image.ipynb #c4498b54
def create_bash_script_content(
    python_script_path: str, # path to the python script
    chunk_info_file: Path, # path to the chunk info file
    chunk_result_dir: Path, # path to the chunk result directory
    model_path: str, # path to the model
    python_env: str = None, # conda/virtual environment name
    additional_args: str = "", # additional arguments for the python script
    chunk_data: Dict = None # chunk data dictionary
) -> str:
    """
    Create the content for a bash script that processes one chunk
    Returns:
        Bash script content as string
    """
    
    # Environment activation
    env_activation = ""
    if python_env:
        env_activation = f"""
# Activate environment
#source activate {python_env}
# loading virtual environment, loading cuda/11.8, intializes bash as a shell
dlenv
# or use: conda activate {python_env}
"""
    
    # Extract image file lists for direct passing
    im1_files = [pair['im1'] for pair in chunk_data['image_pairs']]
    im2_files = [pair['im2'] for pair in chunk_data['image_pairs']]
    
    # Create temporary file lists
    im1_list_file = chunk_result_dir / 'im1_files.txt'
    im2_list_file = chunk_result_dir / 'im2_files.txt'
    
    bash_content = f"""#!/bin/bash
#
# Tflex chunk processing script
# Generated automatically for parallel image inference
# Chunk ID: {chunk_data['chunk_id']}
# Image pairs: {len(chunk_data['image_pairs'])}
#

set -e  # Exit on any error

echo "🚀 Starting chunk {chunk_data['chunk_id']} processing..."
echo "📊 Processing {len(chunk_data['image_pairs'])} image pairs"
echo "🕐 Started at: $(date)"

{env_activation}

# Create output directory
mkdir -p {chunk_result_dir}

# Create image file lists
cat > {im1_list_file} << 'EOF'
{chr(10).join(im1_files)}
EOF

cat > {im2_list_file} << 'EOF'
{chr(10).join(im2_files)}
EOF

echo "📁 Image lists created"
echo "📄 IM1 files: {im1_list_file}"
echo "📄 IM2 files: {im2_list_file}"

# Run your Python script
echo "🐍 Running Python inference script..."
gpu_ "python {python_script_path} \\
    --model_path "{model_path}" \\
    --im1_files "{im1_list_file}" \\
    --im2_files "{im2_list_file}" \\
    --output_dir "{chunk_result_dir}" \\
    --batch_size {chunk_data['batch_size']} \\
    --num_workers {chunk_data['num_workers']} \\
    --img_size {chunk_data['img_size'][0]} {chunk_data['img_size'][1]} \\
    --device {chunk_data['device']} \\
    --chunk_info "{chunk_info_file}" \\
    {additional_args}"

# Check if Python script succeeded
if [ $? -eq 0 ]; then
    echo "✅ Chunk {chunk_data['chunk_id']} completed successfully"
    echo "📁 Results saved to: {chunk_result_dir}"
    echo "🕐 Finished at: $(date)"
else
    echo "❌ Chunk {chunk_data['chunk_id']} failed"
    echo "🕐 Failed at: $(date)"
    exit 1
fi

echo "🎉 Chunk {chunk_data['chunk_id']} processing complete!"
"""
    
    return bash_content

# %% ../../nbs/49_patching.inference_batch_image.ipynb #619c5648
def generate_tflex_commands(
        im1_folder:str,
		im2_folder:str,
		output_dir:str,
		python_script_path:str,
		model_path:str,
		images_per_job:int,
		batch_size:int,
		num_workers:int,
		img_size:tuple=(1152,1632),
		device:str='cpu',
		tflex_file:str='tflex_commands.txt',
		python_env:str=None,
		additional_args:str=""

	):
	# Create output directory structure
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    chunks_dir = output_path / 'chunks'
    results_dir = output_path / 'results'
    logs_dir = output_path / 'logs'
    scripts_dir = output_path / 'scripts'
    
    chunks_dir.mkdir(exist_ok=True)
    results_dir.mkdir(exist_ok=True)
    logs_dir.mkdir(exist_ok=True)
    scripts_dir.mkdir(exist_ok=True)
    
    # Step 1: Split images into chunks
    chunks = split_images_into_chunks(
        im1_folder=im1_folder,
        im2_folder=im2_folder,
        images_per_job=images_per_job
    )
    
    if not chunks:
        raise ValueError("No image chunks created. Check your input folders.")
    
    # Step 2: Generate bash scripts and tflex commands
    tflex_commands = []
    
    for chunk_idx, chunk in enumerate(chunks):
        # Create chunk-specific paths
        chunk_name = f"chunk_{chunk_idx:04d}"
        chunk_result_dir = results_dir / chunk_name
        chunk_result_dir.mkdir(exist_ok=True)
        
        # Save chunk information to JSON
        chunk_info_file = chunks_dir / f"{chunk_name}_info.json"
        chunk_data = {
            'chunk_id': chunk_idx,
            'image_pairs': chunk,
            'batch_size': batch_size,
            'num_workers': num_workers,
            'img_size': img_size,
            'device': device,
            'output_dir': str(chunk_result_dir),
            'model_path': model_path
        }
        
        with open(chunk_info_file, 'w') as f:
            json.dump(chunk_data, f, indent=2)
        
        # Create bash script for this chunk
        bash_script_path = scripts_dir / f"{chunk_name}_process.sh"
        log_file = logs_dir / f"{chunk_name}.log"
        error_file = logs_dir / f"{chunk_name}.err"
        
        # Generate bash script content
        bash_content = create_bash_script_content(
            python_script_path=python_script_path,
            chunk_info_file=chunk_info_file,
            chunk_result_dir=chunk_result_dir,
            model_path=model_path,
            python_env=python_env,
            additional_args=additional_args,
            chunk_data=chunk_data
        )
        
        # Write bash script
        with open(bash_script_path, 'w') as f:
            f.write(bash_content)
        
        # Make bash script executable
        import os
        os.chmod(bash_script_path, 0o755)
        
        # Generate tflex command (just calls the bash script)
        tflex_command = f"bash {bash_script_path} > {log_file} 2> {error_file}"
        tflex_commands.append(tflex_command)
    
    # Step 3: Write tflex commands file
    tflex_file_path = output_path / tflex_file
    with open(tflex_file_path, 'w') as f:
        for cmd in tflex_commands:
            f.write(f"{cmd}\n")
    
    # Step 4: Create summary file
    summary = {
        'total_chunks': len(chunks),
        'total_image_pairs': sum(len(chunk) for chunk in chunks),
        'images_per_job': images_per_job,
        'batch_size': batch_size,
        'img_size': img_size,
        'device': device,
        'python_script': python_script_path,
        'model_path': model_path,
        'tflex_file': str(tflex_file_path),
        'output_structure': {
            'chunks_dir': str(chunks_dir),
            'results_dir': str(results_dir),
            'logs_dir': str(logs_dir),
            'scripts_dir': str(scripts_dir)
        }
    }
    
    summary_file = output_path / 'processing_summary.json'
    with open(summary_file, 'w') as f:
        json.dump(summary, f, indent=2)
    
    print(f"✅ Generated {len(tflex_commands)} bash scripts and tflex commands")
    print(f"📁 Tflex file: {tflex_file_path}")
    print(f"📊 Summary: {summary_file}")
    print(f"🔧 Total image pairs: {summary['total_image_pairs']}")
    print(f"📜 Bash scripts: {scripts_dir}")
    
    return str(tflex_file_path)




# %% ../../nbs/49_patching.inference_batch_image.ipynb #cf74239a
def load_file_list(file_path:str)->List[str]:
	"""Load list of files from text file"""
	with open(file_path, 'r') as f:
		return [line.strip() for line in f if line.strip()]

# %% ../../nbs/49_patching.inference_batch_image.ipynb #48fe59a7
def process_image_pair_chunks(
	model:nn.Module,
	im1_files:List[str],
	im2_files:List[str],
	batch_size:int,
	num_workers:int,
	device:str,
	post_process:bool=True,
	threshold:float=0.5,
	original_size:tuple=None,
	print_stats:bool=False,
	output_dir:str=None,
	
):
	'Process image pairs in chunks'
	
	inf_ds = InferenceTwoImageDataset(
		im1_files=im1_files,
		im2_files=im2_files,
		max_tries=2
	)
	inf_dl = create_pin_dl(
		ds=inf_ds,
		shuffle=False,
		num_workers=num_workers,
		collate_fn=segmentation_collate_fn,
		pin_memory=True,
		batch_size=batch_size
	)

	print(f"🔄 Processing {len(inf_dl)} batches")
	
	results = []
	with torch.no_grad():
		for batch_idx, batch in enumerate(inf_dl):
			try:
				batch_res = predict_batch(
					image_batch=batch,
					model=model,
					device=device,
					output_dir=output_dir,
					post_process=post_process,
					threshold=threshold,
					original_size=original_size,
					print_stats=print_stats
				)
				results.append(batch_res)
				if (batch_idx + 1) % 10 == 0:
					print(f"✅ Processed {batch_idx + 1}/{len(inf_dl)} batches")
					
			except Exception as e:
				print(f"❌ Error processing batch {batch_idx}: {e}")
				continue
				
	return results

# %% ../../nbs/49_patching.inference_batch_image.ipynb #c28955d3
@call_parse
def main_(
        model_path:Param(type=str, help='Path to the model file')='/model/path',
        im1_files_path:Param(type=str, help='A text file containing the list of IM1 files')='/im1/file/list.txt',
        im2_files_path:Param(type=str, help='A text file containing the list of IM2 files')='/im2/file/list.txt',
        output_dir:Param(type=str, help='Output directory')='/output/dir',
		pred_output_dir:Param(type=str, help='Prediction output directory')='/pred/output/dir',
        batch_size:Param(type=int, help='Batch size')='1',
        num_workers:Param(type=int, help='Number of workers')='0',
        img_size:Param(type=tuple, help='Image size')=(1152,1632),
        device:Param(type=str, help='Device')='cpu',
        python_env:Param(type=str, help='Python environment')='None',
        additional_args:Param(type=str, help='Additional arguments')='',
		overlap:Param(type=int, help='Overlap between tiles')=32,
		tile_size:Param(type=int, help='Tile size')=256,
		im1_threshold:Param(type=float, help='IM1 threshold')=0.3,
		edge_model:Param(type=bool, help='Edge model')=False,
		pred_threshold:Param(type=float, help='Prediction threshold')=0.5,
		dilation_iteration_rev:Param(type=int, help='Dilation iteration reverse')=2,
		dilation_iteration:Param(type=int, help='Dilation iteration')=2,
		map_location:Param(type=str, help='Map location')='cpu',
		convert_to_onnx:Param(type=bool, help='Convert to ONNX',action=store_true)=False,
		onnx_path:Param(type=str, help='ONNX path')='None',
		opset_version:Param(type=int, help='ONNX opset version')=12,
		input_shape:Param(type=tuple, help='Input shape')=(1,2,1152,1632),
	):
	'End to end pipeline script for inference'
	# load model
	model = load_whole_pipeline_model(
		model_path,
		in_channels=1,
		out_channels=1,
		tile_size=tile_size,
		overlap=overlap,
		im1_threshold=im1_threshold,
		pred_threshold=pred_threshold,
		dilation_iteration_rev=dilation_iteration_rev,
		dilation_iteration=dilation_iteration,
		map_location=device,
		convert_to_onnx=convert_to_onnx,
		onnx_path=onnx_path,
		opset_version=opset_version,
		input_shape=input_shape,
		edge_model=edge_model
		)
	

	model.eval()
	pred_output_dir = Path(pred_output_dir)
	pred_output_dir.mkdir(exist_ok=True, parents=True)

	# load files 
	im1_files = load_file_list(im1_files_path)
	im2_files = load_file_list(im2_files_path)

	# process image pairs in chunks
	results = process_image_pair_chunks(
		model=model,
		im1_files=im1_files,
		im2_files=im2_files,
		batch_size=batch_size,
		num_workers=num_workers,
		device=device,
		post_process=True,
		threshold=pred_threshold,
		original_size=None,
		print_stats=True,
		output_dir=pred_output_dir
	)
	

