"""Create a model which patch image , do preprocesing, unpatch and do postprocessing"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/46_patching.model_development.ipynb.

# %% auto #0
__all__ = ['CV_TOOLS', 'custom_lib_path', 'CURRETNT_NB', 'SpatialAttention', 'DepthwiseSeparableConv', 'EncoderBlock',
           'DecoderBlock', 'LightweightAttentionUNet', 'np_to_torch', 'ModelWithPreprocessing', 'ModelForTraining',
           'get_end_test_only_model', 'export_model_to_onnx']

# %% ../../nbs/46_patching.model_development.ipynb #31dc89bb
import sys
from pathlib import Path
from fastcore.script import *
from fastcore.all import *
from torch import nn
import torch
import torch.nn.functional as F
import time
#try:
    #import onnxruntime as ort
#except ImportError:
    #print("Installing onnxruntime...")
    #import subprocess
    #subprocess.check_call(["pip", "install", "onnxruntime"])
    #import onnxruntime as ort

from private_front_easy_pin_detection.dataloader_creation import *


# %% ../../nbs/46_patching.model_development.ipynb #25d386a9
from new_test.patching.preprocessing_input_image import *
#from private_front_easy_pin_detection.model_development import *

# %% ../../nbs/46_patching.model_development.ipynb #ac300aec
CV_TOOLS = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools')
sys.path.append(str(CV_TOOLS))


# %% ../../nbs/46_patching.model_development.ipynb #330935ad
custom_lib_path = Path(r'/home/ai_warstein/homes/goni/custom_libs')
sys.path.append(str(custom_lib_path))


# %% ../../nbs/46_patching.model_development.ipynb #90ce573a
from cv_tools.imports import *
from cv_tools.core import *
from dotenv import load_dotenv


# %% ../../nbs/46_patching.model_development.ipynb #25ace947
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

# %% ../../nbs/46_patching.model_development.ipynb #87e9ca2b
load_dotenv(dotenv_path=f'/home/ai_sintercra/homes/hasan/projects/git_data/new_test/new_test/.env')

# %% ../../nbs/46_patching.model_development.ipynb #87d0320b
from new_test.patching.preprocessing_input_image import *

# %% ../../nbs/46_patching.model_development.ipynb #ee3fc0ea
class SpatialAttention(nn.Module):
    def __init__(self, in_channels):
        super(SpatialAttention, self).__init__()
        self.conv = nn.Conv2d(in_channels, 1, kernel_size=1)
        
    def forward(self, x):
        # Generate attention map
        attention = self.conv(x)
        attention = torch.sigmoid(attention)
        
        # Apply attention
        return x * attention

# %% ../../nbs/46_patching.model_development.ipynb #266c007e
class DepthwiseSeparableConv(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, padding=1):
        super(DepthwiseSeparableConv, self).__init__()
        self.depthwise = nn.Conv2d(
            in_channels, in_channels, kernel_size=kernel_size,
            stride=stride, padding=padding, groups=in_channels, bias=False
        )
        self.pointwise = nn.Conv2d(
            in_channels, out_channels, kernel_size=1, bias=True
        )
        
    def forward(self, x):
        x = self.depthwise(x)
        x = self.pointwise(x)
        return x

# %% ../../nbs/46_patching.model_development.ipynb #efbcad3f
class EncoderBlock(nn.Module):
    def __init__(self, in_channels, out_channels, use_depthwise=False):
        super(EncoderBlock, self).__init__()
        
        if use_depthwise:
            self.conv1 = DepthwiseSeparableConv(in_channels, out_channels)
            self.conv2 = DepthwiseSeparableConv(out_channels, out_channels)
        else:
            self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)
            self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1)
            
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.bn2 = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU6(inplace=True)
        
    def forward(self, x):
        x = self.relu(self.bn1(self.conv1(x)))
        x = self.relu(self.bn2(self.conv2(x)))
        return x

# %% ../../nbs/46_patching.model_development.ipynb #64285d06
class DecoderBlock(nn.Module):
    def __init__(self, in_channels, out_channels, use_depthwise=False):
        super(DecoderBlock, self).__init__()
        
        self.up = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        
        if use_depthwise:
            self.conv1 = DepthwiseSeparableConv(in_channels, out_channels)
            self.conv2 = DepthwiseSeparableConv(out_channels, out_channels)
        else:
            self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1)
            self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1)
            
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.bn2 = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU6(inplace=True)
        self.attention = SpatialAttention(out_channels)
        
    def forward(self, x, skip):
        x = self.up(x)
        
        # Handle cases where dimensions don't match exactly
        diffY = skip.size()[2] - x.size()[2]
        diffX = skip.size()[3] - x.size()[3]
        
        x = F.pad(x, [diffX // 2, diffX - diffX // 2, diffY // 2, diffY - diffY // 2])
        
        # Concatenate skip connection
        x = torch.cat([skip, x], dim=1)
        
        x = self.relu(self.bn1(self.conv1(x)))
        x = self.relu(self.bn2(self.conv2(x)))
        x = self.attention(x)
        
        return x

# %% ../../nbs/46_patching.model_development.ipynb #433c8e82
class LightweightAttentionUNet(nn.Module):
    def __init__(self, in_channels=1, out_channels=1):
        super(LightweightAttentionUNet, self).__init__()
        
        # Initial number of filters (reduced from standard U-Net)
        init_features = 16
        
        # Encoder path
        self.encoder1 = EncoderBlock(in_channels, init_features)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)
        
        self.encoder2 = EncoderBlock(init_features, init_features*2)
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)
        
        self.encoder3 = EncoderBlock(init_features*2, init_features*4, use_depthwise=True)
        self.pool3 = nn.MaxPool2d(kernel_size=2, stride=2)
        
        # Bottleneck
        self.bottleneck = EncoderBlock(init_features*4, init_features*8, use_depthwise=True)
        
        # Decoder path
        self.decoder3 = DecoderBlock(init_features*8 + init_features*4, init_features*4, use_depthwise=True)
        self.decoder2 = DecoderBlock(init_features*4 + init_features*2, init_features*2)
        self.decoder1 = DecoderBlock(init_features*2 + init_features, init_features)
        
        # Final output layer
        self.final_conv = nn.Conv2d(init_features, out_channels, kernel_size=1)
        
    def forward(self, x):
        # Encoder
        enc1 = self.encoder1(x)
        x = self.pool1(enc1)
        
        enc2 = self.encoder2(x)
        x = self.pool2(enc2)
        
        enc3 = self.encoder3(x)
        x = self.pool3(enc3)
        
        # Bottleneck
        x = self.bottleneck(x)
        
        # Decoder
        x = self.decoder3(x, enc3)
        x = self.decoder2(x, enc2)
        x = self.decoder1(x, enc1)
        
        # Final output
        x = self.final_conv(x)
        
        #return torch.sigmoid(x)  # Sigmoid for binary segmentation
        return x

    def get_input_names(self):
        return ['input']
        
    def get_output_names(self):
        return ['output']
        
    def get_dynamic_axes(self):
        return {
            'input': {0: 'batch_size', 2: 'height', 3: 'width'},
            'output': {0: 'batch_size', 2: 'height', 3: 'width'}
        }
        
    def get_dummy_input(self, batch_size=1, height=1152, width=1632):
        return torch.randn(batch_size, 1, height, width)

# %% ../../nbs/46_patching.model_development.ipynb #ca1022eb
def np_to_torch(x):
   'float -> 1,1,img_size -> Tensor'
   #x:[0,1]
   x = x.astype(np.float32)
   x = x[None, None,...]
   x = Tensor(x)
   return x

# %% ../../nbs/46_patching.model_development.ipynb #502f5aa1
class ModelWithPreprocessing(nn.Module):
    def __init__(
        self, 
        in_channels:int=1,  # number of channels in the input image
        out_channels:int=1, # number of channels in the output image
        with_clahe:bool=True, # whether to apply clahe
        with_denoise:bool=True, # whether to apply denoise
        with_bias_field_correction:bool=True, # whether to apply bias field correction
    ):
        """
        Model with preprocessing + postprocessing + tiling.
        """
        super(ModelWithPreprocessing, self).__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.with_clahe = with_clahe
        self.with_denoise = with_denoise
        self.with_bias_field_correction = with_bias_field_correction

        # clahe
        
        self.cl = ONNXFriendlyCLAHEOpset12(
            window_size=8,
            clip_limit=2.0,
        )
        # blurring 
        self.denoise = GaussianDenoiseLayer(
            kernel_size=5,
            sigma=1.0,
            channels=1
        )
        # bias field correction
        self.bias_field_correction = BiasFieldCorrectionLayer(
            in_channels=1,
            reduction=16
        )
        self.model = LightweightAttentionUNet(
            in_channels=self.in_channels,
            out_channels=self.out_channels
        )
    __repr__ = basic_repr()
        
    def forward(self, x):
        if self.with_clahe:
            x = self.cl(x)
        if self.with_denoise:
            x = self.denoise(x)
        if self.with_bias_field_correction:
            x = self.bias_field_correction(x)
        x = self.model(x)
        
            
        return x

# %% ../../nbs/46_patching.model_development.ipynb #6f262d0a
class ModelForTraining(nn.Module):
    """Model wrapper optimized for training with proper loss computation and memory efficiency.
    
    Key features for training:
    - Disabled tiling to reduce memory overhead during backprop
    - Disabled postprocessing for faster forward passes
    - Direct output suitable for loss computation
    - Maintains all preprocessing steps for data consistency
    """
    def __init__(self, 
                 in_channels=1, 
                 out_channels=1,
                 with_clahe=True,
                 with_denoise=True, 
                 with_bias_field_correction=True):
        super(ModelForTraining, self).__init__()
        self.model = ModelWithPreprocessing(
            in_channels=in_channels,
            out_channels=out_channels,
            with_clahe=with_clahe,
            with_denoise=with_denoise,
            with_bias_field_correction=with_bias_field_correction
        )
        
    def forward(self, x):
        """Forward pass optimized for training.
        
        Args:
            x: Input tensor of shape (B, C, H, W)
            
        Returns:
            Raw model output suitable for loss computation
        """
        return self.model(x)
    
    def training_step(self, batch, criterion):
        """Convenience method for training step.
        
        Args:
            batch: Tuple of (images, masks)
            criterion: Loss function (e.g., BCEWithLogitsLoss)
            
        Returns:
            loss: Computed loss value
        """
        images, masks = batch
        outputs = self.forward(images)
        loss = criterion(outputs, masks)
        return loss


# %% ../../nbs/46_patching.model_development.ipynb #5980ac5e
def get_end_test_only_model(
    in_channels=1,
    out_channels=1
):
    return LightweightAttentionUNet(
        in_channels=in_channels,
        out_channels=out_channels
    )

# %% ../../nbs/46_patching.model_development.ipynb #1ec4faa6
def export_model_to_onnx(
    model, # nn.Module: PyTorch model to export
    output_path, # str: Path to save ONNX model
    input_shape=(1, 1, 1152, 1632), # tuple: Shape of input tensor
    input_names=None, # list: Names of input tensors
    output_names=None, # list: Names of output tensors
    dynamic_axes=None # dict: Dynamic axes for inputs and outputs
    )->str: # Path to exported ONNX model
    """
    Export PyTorch model to ONNX format.
    
    """
    # Create dummy input
    dummy_input = torch.randn(input_shape)
    
    # Set default input and output names if not provided
    if input_names is None:
        input_names = ['input']
    if output_names is None:
        output_names = ['output']
    
    ## Set default dynamic axes if not provided
    #if dynamic_axes is None:
        #dynamic_axes = {
            #'input': {0: 'batch_size', 2: 'height', 3: 'width'},
            #'output': {0: 'batch_size', 2: 'height', 3: 'width'}
        #}
    
    # Export model to ONNX
    torch.onnx.export(
        model,                       # PyTorch model
        dummy_input,                 # Dummy input
        output_path,                 # Output path
        export_params=True,          # Export model parameters
        opset_version=12,            # ONNX opset version
        do_constant_folding=True,    # Fold constants
        input_names=input_names,     # Input names
        output_names=output_names,   # Output names
        verbose=False                # Verbose output
    )
    
    return output_path

# %% ../../nbs/46_patching.model_development.ipynb #680188ca
CURRETNT_NB='/home/ai_sintercra/homes/hasan/projects/git_data/new_test/nbs'
