"""Do some preprocessing and create onnx layer with those input operator"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/45_patching.preprocessing_input_image.ipynb.

# %% auto #0
__all__ = ['CV_TOOLS', 'custom_lib_path', 'CURRETNT_NB', 'get_gaussian_kernel', 'GaussianDenoiseLayer',
           'BiasFieldCorrectionLayer', 'get_common_names', 'plot_image_grid', 'TileProcessorv4', 'TileMergerv4',
           'plot_tiles', 'ONNXFriendlyCLAHEOpset12']

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #d51cabee
import sys
from pathlib import Path
from platform import system
from fastcore.script import *
from fastcore.all import *


# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #924da3f2
CV_TOOLS = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools')
sys.path.append(str(CV_TOOLS))


# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #ee927453
custom_lib_path = Path(r'/home/ai_warstein/homes/goni/custom_libs')
sys.path.append(str(custom_lib_path))


# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #0d26b081
from cv_tools.imports import *
from cv_tools.core import *
from dotenv import load_dotenv
import matplotlib.pyplot as plt

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #0d67db0b
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #05b2105c
def get_gaussian_kernel(kernel_size=5, sigma=1.0, channels=1):
    """Returns a 2D Gaussian kernel for depthwise convolution."""
    # Create 1D kernel
    x = torch.arange(kernel_size) - kernel_size // 2
    gauss = torch.exp(-x**2 / (2 * sigma**2))
    gauss = gauss / gauss.sum()
    # Outer product to get 2D kernel
    kernel2d = gauss[:, None] * gauss[None, :]
    kernel2d = kernel2d / kernel2d.sum()
    # Expand to (channels, 1, k, k) for depthwise conv
    kernel = kernel2d.expand(channels, 1, kernel_size, kernel_size).contiguous()
    return kernel

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #3fa50f81
class GaussianDenoiseLayer(nn.Module):
    """
    ONNX-compatible Gaussian denoising layer.
    Args:
        kernel_size: Size of the Gaussian kernel (odd integer).
        sigma: Standard deviation of the Gaussian.
        channels: Number of input channels.
    """
    def __init__(self, kernel_size=5, sigma=1.0, channels=1):
        super().__init__()
        kernel = get_gaussian_kernel(kernel_size, sigma, channels)
        self.register_buffer('weight', kernel)
        self.groups = channels
        self.padding = kernel_size // 2

    def forward(self, x):
        # x: (B, C, H, W)
        return F.conv2d(x, self.weight, padding=self.padding, groups=self.groups)

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #b9448f34
class BiasFieldCorrectionLayer(nn.Module):
    """
    ONNX-compatible bias field correction layer.
    Learns a smooth multiplicative mask to correct intensity inhomogeneity.
    Args:
        in_channels: Number of input channels.
        reduction: Downsampling factor for the bias field (higher = smoother).
    """
    def __init__(self, in_channels=1, reduction=16):
        super().__init__()
        self.in_channels = in_channels
        self.reduction = reduction
        # Learnable low-res bias field
        self.bias_field = nn.Parameter(torch.ones(1, in_channels, reduction, reduction))

    def forward(self, x):
        B, C, H, W = x.shape
        # Upsample bias field to input size
        bias = F.interpolate(self.bias_field, size=(H, W), mode='bilinear', align_corners=False)
        # Multiplicative correction, clamp to avoid division by zero
        corrected = x / (bias + 1e-6)
        return corrected

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #5bcd6630
load_dotenv(dotenv_path=f'/home/ai_sintercra/homes/hasan/projects/git_data/new_test/new_test/.env')

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #1620fb24
CURRETNT_NB='/home/ai_sintercra/homes/hasan/projects/git_data/new_test/nbs'

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #bb1810ba
def get_common_names(images, masks):
    return set(get_name_(images)).intersection(set(get_name_(masks)))

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #fb6e0100
def plot_image_grid(images, titles=None, figsize=(15, 10), n_cols=2):
    """
    Plot a grid of images with optional titles.
    
    Args:
        images (list): List of images to plot
        titles (list, optional): List of titles for each image
        figsize (tuple): Figure size (width, height)
        n_cols (int): Number of columns in the grid
    """
    n_images = len(images)
    n_rows = (n_images + n_cols - 1) // n_cols
    
    fig, axes = plt.subplots(n_rows, n_cols, figsize=figsize)
    axes = axes.flatten() if n_images > 1 else [axes]
    
    for idx, (ax, img) in enumerate(zip(axes, images)):
        ax.imshow(img, cmap='gray')
        if titles is not None and idx < len(titles):
            ax.set_title(titles[idx])
        ax.axis('off')
    
    # Hide empty subplots
    for idx in range(n_images, len(axes)):
        axes[idx].axis('off')
        axes[idx].set_visible(False)
    
    plt.tight_layout()
    return fig

# Example usage:
# images_to_plot = [img_n, img_b[0,0].numpy(), img_n]  # Your images here
# titles = ['Original', 'Processed', 'Another View']
# fig = plot_image_grid(images_to_plot, titles=titles, n_cols=2)


# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #fa729adb
class TileProcessorv4(nn.Module):
    """
    ONNX opset 12 compatible PyTorch module for splitting images into overlapping tiles.
    Uses vectorized operations for better performance while maintaining opset 12 compatibility.
    """
    def __init__(self, tile_size=256, overlap=32):
        super().__init__()
        self.tile_size = tile_size
        self.overlap = overlap
        self.stride = tile_size - overlap
        
    def forward(self, x):
        """
        Split input tensor into overlapping tiles using vectorized ONNX opset 12 compatible operations.
        
        Args:
            x: Input tensor [B, C, H, W]
            
        Returns:
            tiles: Tensor of tiles [N, C, tile_size, tile_size]
            positions: List of (row, col, start_h, start_w) for each tile
        """
        B, C, H, W = x.shape
        
        # Calculate number of tiles needed using basic operations
        num_tiles_h = (H - self.overlap + self.stride - 1) // self.stride
        num_tiles_w = (W - self.overlap + self.stride - 1) // self.stride
        
        # Calculate required padding
        padded_h = num_tiles_h * self.stride + self.overlap
        padded_w = num_tiles_w * self.stride + self.overlap
        
        # Calculate padding amounts
        pad_h = max(0, padded_h - H)
        pad_w = max(0, padded_w - W)
        
        # Apply padding if needed
        if pad_h > 0 or pad_w > 0:
            x = F.pad(x, (0, pad_w, 0, pad_h), mode='reflect')
        
        # Vectorized tile extraction using advanced indexing (opset 12 compatible)
        # Create coordinate grids for all tiles at once
        
        # Generate all starting positions
        h_starts = torch.arange(0, num_tiles_h, device=x.device) * self.stride
        w_starts = torch.arange(0, num_tiles_w, device=x.device) * self.stride
        
        # Create meshgrid for all tile positions
        h_grid, w_grid = torch.meshgrid(h_starts, w_starts, indexing='ij')
        h_grid = h_grid.flatten()  # [num_tiles_h * num_tiles_w]
        w_grid = w_grid.flatten()  # [num_tiles_h * num_tiles_w]
        
        # Create offset grids for tile coordinates
        tile_h_coords = torch.arange(self.tile_size, device=x.device).unsqueeze(1).expand(self.tile_size, self.tile_size)
        tile_w_coords = torch.arange(self.tile_size, device=x.device).unsqueeze(0).expand(self.tile_size, self.tile_size)
        
        # Vectorized tile extraction
        tiles = []
        for i in range(len(h_grid)):
            h_start = h_grid[i]
            w_start = w_grid[i]
            
            # Calculate absolute coordinates for this tile
            abs_h_coords = h_start + tile_h_coords
            abs_w_coords = w_start + tile_w_coords
            
            # Extract tile using advanced indexing (opset 12 compatible)
            tile = x[:, :, abs_h_coords, abs_w_coords]
            tiles.append(tile)
        
        # Stack all tiles
        tiles = torch.stack(tiles, dim=0)  # [N, B, C, tile_size, tile_size]
        tiles = tiles.squeeze(1)  # Remove batch dimension: [N, C, tile_size, tile_size]
        
        # Generate positions
        positions = []
        for i in range(num_tiles_h):
            for j in range(num_tiles_w):
                start_h = i * self.stride
                start_w = j * self.stride
                positions.append((i, j, start_h, start_w))
        
        return tiles, positions

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #1006d596
class TileMergerv4(nn.Module):
    """
    ONNX opset 12 compatible module for merging overlapping binary mask tiles.
    Uses only basic operations supported in opset 12.
    """
    def __init__(self, merge_strategy='confidence_weighted', confidence_threshold=0.5):
        super().__init__()
        self.merge_strategy = merge_strategy  # 'majority_vote', 'confidence_weighted', 'adaptive'
        self.confidence_threshold = confidence_threshold
        
    def _create_distance_weight_mask_opset12(self, tile_size, device):
        """Create distance-based weight mask using only opset 12 compatible operations."""
        # Create coordinate grids without indexing parameter (opset 12 compatible)
        y_coords = torch.arange(tile_size, device=device, dtype=torch.float32)
        x_coords = torch.arange(tile_size, device=device, dtype=torch.float32)
        
        # Manual meshgrid creation (opset 12 compatible)
        y = y_coords.unsqueeze(1).expand(tile_size, tile_size)
        x = x_coords.unsqueeze(0).expand(tile_size, tile_size)
        
        # Calculate distance from center using basic operations
        center = tile_size / 2.0 - 0.5
        dx = x - center
        dy = y - center
        
        # Distance calculation using basic ops
        dist_squared = dx * dx + dy * dy
        dist_from_center = torch.sqrt(dist_squared + 1e-8)  # Add epsilon for numerical stability
        
        # Maximum distance (corner to center)
        max_dist = torch.sqrt(torch.tensor(2.0 * center * center, device=device))
        
        # Convert to weight (higher at center, lower at edges)
        weight = 1.0 - (dist_from_center / max_dist)
        weight = torch.clamp(weight, 0.1, 1.0)  # Minimum weight to avoid zero weights
        
        return weight
        
    def _majority_vote_merge_opset12(self, tiles, positions, original_h, original_w):
        """ONNX opset 12 compatible majority voting merge."""
        device = tiles.device
        N, C, tile_size, _ = tiles.shape
        
        # Calculate padded dimensions using basic operations
        max_h = original_h
        max_w = original_w
        for pos in positions:
            max_h = max(max_h, pos[2] + tile_size)
            max_w = max(max_w, pos[3] + tile_size)
        
        # Initialize vote accumulators
        vote_sum = torch.zeros(1, C, max_h, max_w, device=device, dtype=torch.float32)
        vote_count = torch.zeros(1, 1, max_h, max_w, device=device, dtype=torch.float32)
        
        # Threshold tiles to binary using basic comparison
        binary_tiles = (tiles > self.confidence_threshold).float()
        
        # Accumulate votes using basic indexing
        for i in range(len(positions)):
            row, col, start_h, start_w = positions[i]
            end_h = start_h + tile_size
            end_w = start_w + tile_size
            
            # Add vote using basic tensor operations
            vote_sum[:, :, start_h:end_h, start_w:end_w] = (
                vote_sum[:, :, start_h:end_h, start_w:end_w] + binary_tiles[i:i+1]
            )
            vote_count[:, :, start_h:end_h, start_w:end_w] = (
                vote_count[:, :, start_h:end_h, start_w:end_w] + 1.0
            )
        
        # Majority vote using basic operations
        vote_count = torch.clamp(vote_count, min=1.0)  # Avoid division by zero
        vote_ratio = vote_sum / vote_count
        majority_mask = (vote_ratio > 0.5).float()
        
        # Crop to original dimensions using basic slicing
        result = majority_mask[:, :, :original_h, :original_w]
        return result
        
    def _confidence_weighted_merge_opset12(self, tiles, positions, original_h, original_w):
        """ONNX opset 12 compatible confidence-weighted merge."""
        device = tiles.device
        N, C, tile_size, _ = tiles.shape
        
        # Calculate padded dimensions
        max_h = original_h
        max_w = original_w
        for pos in positions:
            max_h = max(max_h, pos[2] + tile_size)
            max_w = max(max_w, pos[3] + tile_size)
        
        # Initialize accumulators
        weighted_sum = torch.zeros(1, C, max_h, max_w, device=device, dtype=torch.float32)
        weight_sum = torch.zeros(1, 1, max_h, max_w, device=device, dtype=torch.float32)
        
        # Create distance-based weight mask
        distance_weight = self._create_distance_weight_mask_opset12(tile_size, device)
        
        # Accumulate weighted predictions
        for i in range(len(positions)):
            row, col, start_h, start_w = positions[i]
            end_h = start_h + tile_size
            end_w = start_w + tile_size
            
            tile = tiles[i:i+1]
            
            # Calculate confidence weight using basic operations
            tile_centered = tile - 0.5
            confidence = torch.abs(tile_centered) * 2.0  # Range [0, 1]
            
            # Combine distance and confidence weights using basic operations
            distance_expanded = distance_weight.unsqueeze(0).unsqueeze(0)
            confidence_factor = 0.5 + confidence
            combined_weight = distance_expanded * confidence_factor
            
            # Accumulate using basic operations
            weighted_sum[:, :, start_h:end_h, start_w:end_w] = (
                weighted_sum[:, :, start_h:end_h, start_w:end_w] + tile * combined_weight
            )
            weight_sum[:, :, start_h:end_h, start_w:end_w] = (
                weight_sum[:, :, start_h:end_h, start_w:end_w] + combined_weight
            )
        
        # Normalize using basic operations
        weight_sum = torch.clamp(weight_sum, min=1e-8)
        merged = weighted_sum / weight_sum
        
        # Apply threshold to get binary mask
        binary_result = (merged > self.confidence_threshold).float()
        
        # Crop to original dimensions
        result = binary_result[:, :, :original_h, :original_w]
        return result
        
    def _adaptive_merge_opset12(self, tiles, positions, original_h, original_w):
        """ONNX opset 12 compatible adaptive merge."""
        device = tiles.device
        N, C, tile_size, _ = tiles.shape
        
        # Get both results using opset 12 compatible methods
        majority_result = self._majority_vote_merge_opset12(tiles, positions, original_h, original_w)
        confidence_result = self._confidence_weighted_merge_opset12(tiles, positions, original_h, original_w)
        
        # Calculate average confidence map
        max_h = original_h
        max_w = original_w
        for pos in positions:
            max_h = max(max_h, pos[2] + tile_size)
            max_w = max(max_w, pos[3] + tile_size)
        
        confidence_map = torch.zeros(1, C, max_h, max_w, device=device, dtype=torch.float32)
        count_map = torch.zeros(1, 1, max_h, max_w, device=device, dtype=torch.float32)
        
        # Calculate average confidence for each pixel
        for i in range(len(positions)):
            row, col, start_h, start_w = positions[i]
            end_h = start_h + tile_size
            end_w = start_w + tile_size
            
            tile = tiles[i:i+1]
            tile_centered = tile - 0.5
            tile_confidence = torch.abs(tile_centered) * 2.0
            
            confidence_map[:, :, start_h:end_h, start_w:end_w] = (
                confidence_map[:, :, start_h:end_h, start_w:end_w] + tile_confidence
            )
            count_map[:, :, start_h:end_h, start_w:end_w] = (
                count_map[:, :, start_h:end_h, start_w:end_w] + 1.0
            )
        
        count_map = torch.clamp(count_map, min=1.0)
        avg_confidence = confidence_map / count_map
        avg_confidence = avg_confidence[:, :, :original_h, :original_w]
        
        # Use majority vote for high-confidence regions, weighted for low-confidence
        high_confidence_mask = (avg_confidence > 0.7).float()
        low_confidence_mask = 1.0 - high_confidence_mask
        
        # Blend results using basic operations
        result = (high_confidence_mask * majority_result + 
                 low_confidence_mask * confidence_result)
        
        return result
        
    def _morphological_postprocess_opset12(self, mask, kernel_size=3):
        """ONNX opset 12 compatible morphological operations using max/min pooling."""
        # Opening (erosion followed by dilation) using basic pooling operations
        # Erosion approximation using negative max pooling
        padding = kernel_size // 2
        
        # Erosion: min pooling (implemented as negative max pooling)
        mask_neg = -mask
        eroded_neg = F.max_pool2d(mask_neg, kernel_size=kernel_size, stride=1, padding=padding)
        eroded = -eroded_neg
        
        # Dilation: max pooling
        opened = F.max_pool2d(eroded, kernel_size=kernel_size, stride=1, padding=padding)
        
        # Closing (dilation followed by erosion)
        # Dilation: max pooling
        dilated = F.max_pool2d(opened, kernel_size=kernel_size, stride=1, padding=padding)
        
        # Erosion: min pooling (implemented as negative max pooling)
        dilated_neg = -dilated
        closed_neg = F.max_pool2d(dilated_neg, kernel_size=kernel_size, stride=1, padding=padding)
        closed = -closed_neg
        
        return closed
        
    def forward(self, tiles, positions, original_h, original_w, apply_postprocessing=True):
        """
        ONNX opset 12 compatible binary mask merging.
        
        Args:
            tiles: Tensor of prediction tiles [N, C, tile_size, tile_size] (values in [0,1])
            positions: List of (row, col, start_h, start_w) for each tile
            original_h: Original image height
            original_w: Original image width
            apply_postprocessing: Whether to apply morphological post-processing
            
        Returns:
            merged: Binary mask [1, C, original_h, original_w]
        """
        if tiles.shape[0] == 0:
            return torch.zeros(1, tiles.shape[1], original_h, original_w, 
                             device=tiles.device, dtype=tiles.dtype)
        
        # Choose merging strategy using opset 12 compatible methods
        if self.merge_strategy == 'majority_vote':
            merged = self._majority_vote_merge_opset12(tiles, positions, original_h, original_w)
        elif self.merge_strategy == 'confidence_weighted':
            merged = self._confidence_weighted_merge_opset12(tiles, positions, original_h, original_w)
        elif self.merge_strategy == 'adaptive':
            merged = self._adaptive_merge_opset12(tiles, positions, original_h, original_w)
        else:
            # Default to confidence_weighted if unknown strategy
            merged = self._confidence_weighted_merge_opset12(tiles, positions, original_h, original_w)
        
        # Apply morphological post-processing using opset 12 compatible operations
        if apply_postprocessing:
            merged = self._morphological_postprocess_opset12(merged, kernel_size=3)
        
        return merged

# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #86835332
def plot_tiles(tiles, positions):
    """Plot all tiles in a grid layout"""
    n_tiles = tiles.shape[0]
    n_cols = int(np.ceil(np.sqrt(n_tiles)))
    n_rows = int(np.ceil(n_tiles / n_cols))
    
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, 15))
    axes = axes.flatten()
    
    for i in range(n_tiles):
        axes[i].imshow(tiles[i,0].cpu(), cmap='gray')
        axes[i].set_title(f'Tile {i}')
        axes[i].axis('off')
    
    # Hide empty subplots
    for i in range(n_tiles, len(axes)):
        axes[i].axis('off')
        axes[i].set_visible(False)
    
    plt.tight_layout()
    plt.show()



# %% ../../nbs/45_patching.preprocessing_input_image.ipynb #16843c88
class ONNXFriendlyCLAHEOpset12(nn.Module):
    """CLAHE implementation that's compatible with ONNX opset 12.
    This version avoids operations that aren't supported in opset 12.
    """
    def __init__(self, window_size=8, clip_limit=4.0, eps=1e-6):
        super().__init__()
        self.window_size = window_size
        self.clip_limit = clip_limit
        self.eps = eps
        
        # Pre-register kernels as buffers to avoid torch.tensor() in forward
        self.register_buffer('laplacian_kernel', 
                           torch.tensor([[-1,-1,-1], [-1,8,-1], [-1,-1,-1]], dtype=torch.float32).view(1, 1, 3, 3))
        self.register_buffer('sobel_h_kernel', 
                           torch.tensor([[-1,-2,-1], [0,0,0], [1,2,1]], dtype=torch.float32).view(1, 1, 3, 3))
        self.register_buffer('sobel_v_kernel', 
                           torch.tensor([[-1,0,1], [-2,0,2], [-1,0,1]], dtype=torch.float32).view(1, 1, 3, 3))
        
    def forward(self, x):
        # Input: [B,C,H,W], values in [0,1]
        B, C, H, W = x.shape
        
        # Create multi-scale pooling for adaptive local statistics
        pool_sizes = [max(2, self.window_size//4), max(4, self.window_size//2), self.window_size]
        enhanced_outputs = []
        
        # Pad input once for all operations - use constant padding for ONNX compatibility
        x_padded = F.pad(x, (2, 2, 2, 2), mode='constant', value=0)
        x_squared = x_padded * x_padded  # Use multiplication instead of ** for better ONNX support
        
        # 1. MULTI-SCALE LOCAL CONTRAST NORMALIZATION
        for kernel_size in pool_sizes:
            # Use 75% overlap between patches
            stride = max(1, kernel_size // 4)
            
            # Calculate local statistics with overlapping patches
            local_mean = F.avg_pool2d(x_padded, kernel_size=kernel_size, stride=stride)
            local_sqr = F.avg_pool2d(x_squared, kernel_size=kernel_size, stride=stride)
            
            # Resize both tensors at once - use nearest for better ONNX support
            local_mean = F.interpolate(local_mean, size=(H, W), mode='nearest')
            local_sqr = F.interpolate(local_sqr, size=(H, W), mode='nearest')
            
            # Calculate variance and apply clipping
            local_var = local_sqr - local_mean * local_mean
            mean_var = torch.mean(local_var) * self.clip_limit
            local_var = torch.clamp(local_var, 0, mean_var)
            
            # Calculate std and normalize
            local_std = torch.sqrt(local_var + self.eps)
            normalized = (x - local_mean) / (local_std + self.eps)
            normalized = torch.clamp(normalized * 1.5, -1.5, 1.5)
            
            enhanced_outputs.append(normalized)
        
        # 2. EDGE ENHANCEMENT - Pre-compute padded input
        x_edge_padded = F.pad(x, (1, 1, 1, 1), mode='constant', value=0)
        
        # Use pre-registered kernels and repeat for channels
        laplacian_k = self.laplacian_kernel.repeat(C, 1, 1, 1)
        sobel_h_k = self.sobel_h_kernel.repeat(C, 1, 1, 1)
        sobel_v_k = self.sobel_v_kernel.repeat(C, 1, 1, 1)
        
        # Apply convolutions
        edges_lap = F.conv2d(x_edge_padded, laplacian_k, groups=C)
        edges_sobel_h = F.conv2d(x_edge_padded, sobel_h_k, groups=C)
        edges_sobel_v = F.conv2d(x_edge_padded, sobel_v_k, groups=C)
        
        # Combine edge responses - avoid sqrt for better ONNX compatibility
        edges_sobel = torch.sqrt(edges_sobel_h * edges_sobel_h + edges_sobel_v * edges_sobel_v + self.eps)
        
        # Normalize edge responses - use more stable normalization
        edges_lap_abs = torch.abs(edges_lap)
        edges_lap_max = torch.max(edges_lap_abs.view(B, C, -1), dim=2, keepdim=True)[0].unsqueeze(-1)
        edges_lap = edges_lap / (edges_lap_max + self.eps)
        
        edges_sobel_max = torch.max(edges_sobel.view(B, C, -1), dim=2, keepdim=True)[0].unsqueeze(-1)
        edges_sobel = edges_sobel / (edges_sobel_max + self.eps)
        
        # 3. COMBINE ENHANCEMENTS
        combined = enhanced_outputs[0] * 0.5 + enhanced_outputs[1] * 0.3 + enhanced_outputs[2] * 0.2
        edge_enhanced = combined + edges_lap * 0.5 + edges_sobel * 0.3
        
        # 4. CONTRAST STRETCHING
        min_val = torch.min(edge_enhanced.view(B, C, -1), dim=2, keepdim=True)[0].unsqueeze(-1)
        max_val = torch.max(edge_enhanced.view(B, C, -1), dim=2, keepdim=True)[0].unsqueeze(-1)
        normalized = (edge_enhanced - min_val) / (max_val - min_val + self.eps)
        
        # 5. ADAPTIVE GAMMA CORRECTION - simplified for ONNX compatibility
        # Use conditional operations that are better supported
        dark_mask = (normalized < 0.4).float()
        mid_mask = ((normalized >= 0.4) * (normalized < 0.7)).float()
        bright_mask = (normalized >= 0.7).float()
        
        # Apply gamma corrections
        gamma_dark = torch.pow(normalized, 0.7)
        gamma_mid = torch.pow(normalized, 0.9)
        gamma_bright = torch.pow(normalized, 1.2)
        
        # Combine gamma corrections
        gamma_corrected = dark_mask * gamma_dark + mid_mask * gamma_mid + bright_mask * gamma_bright
        
        return torch.clamp(gamma_corrected, 0, 1)


