"""Training model with pytorch"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/47_patching.training_pytorch.ipynb.

# %% auto #0
__all__ = ['CV_TOOLS', 'front', 'current_lib', 'custom_lib_path', 'CURRETNT_NB', 'PinSegmentationDataset',
           'get_training_augmentation', 'get_validation_augmentation', 'get_dataloader', 'get_end_test_model', 'main_']

# %% ../../nbs/47_patching.training_pytorch.ipynb #ba91b293
import sys
from pathlib import Path
from fastcore.all import *
from fastcore.script import *
import monai

# %% ../../nbs/47_patching.training_pytorch.ipynb #568099e0
from torch.utils.data import Dataset, DataLoader
from torch.optim.lr_scheduler import CosineAnnealingLR
import torch
import socket


# %% ../../nbs/47_patching.training_pytorch.ipynb #7da2af53
CV_TOOLS = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools')
front = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/private_front_easy_pin_detection')
current_lib = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/new_test')
sys.path.append(str(CV_TOOLS))
sys.path.append(str(front))
sys.path.append(str(current_lib))


# %% ../../nbs/47_patching.training_pytorch.ipynb #b325c028
custom_lib_path = Path(r'/home/ai_warstein/homes/goni/custom_libs')
sys.path.append(str(custom_lib_path))
sys.path.append(str())

# %% ../../nbs/47_patching.training_pytorch.ipynb #d723ba8f
from cv_tools.imports import *
from cv_tools.core import *
from dotenv import load_dotenv


# %% ../../nbs/47_patching.training_pytorch.ipynb #d87ed35a
load_dotenv(dotenv_path=f'/home/ai_sintercra/homes/hasan/projects/git_data/new_test/new_test/.env')

# %% ../../nbs/47_patching.training_pytorch.ipynb #34ca6a1c
from new_test.patching.model_development import *


# %% ../../nbs/47_patching.training_pytorch.ipynb #bdc9f4c2
from private_front_easy_pin_detection.dataloader_creation import *
from private_front_easy_pin_detection.training_pipeline import *

# %% ../../nbs/47_patching.training_pytorch.ipynb #c1d80804
# Custom Dataset class
class PinSegmentationDataset(Dataset):
    def __init__(self, image_dir, mask_dir, transform=None):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.images = Path(image_dir).ls()
        self.masks = Path(mask_dir).ls()
        self.transform = transform

        super().__init__()
        store_attr()
    __repr__ = basic_repr()

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = self.images[idx]
        name = Path(img_path).name
        mask_path = Path(self.mask_dir, name)
        image = Image.open(img_path).convert('L')
        mask = Image.open(mask_path).convert('L')


        if self.transform:
            # Apply same transform to both image and mask using same random state
            seed = torch.randint(0, 2**32, (1,)).item()
            torch.manual_seed(seed)
            image = self.transform(image)
            torch.manual_seed(seed)
            mask = self.transform(mask)
        else:
            # Convert to tensors if no transform
            image = torch.from_numpy(image, dtype=torch.float32).unsqueeze(0)  # Add channel dimension
            mask = torch.from_numpy(mask, dtype=torch.float32).unsqueeze(0)    # Add channel dimension

        # Ensure mask is binary
        mask = torch.where(mask > 0.5, 1.0, 0.0)

        return image, mask


# %% ../../nbs/47_patching.training_pytorch.ipynb #fa77dcd7
from torchvision import transforms as T

# %% ../../nbs/47_patching.training_pytorch.ipynb #ff415efd
def get_training_augmentation(
    IMAGE_HEIGHT: int = 256,
    IMAGE_WIDTH: int = 256,

):
    from torchvision import transforms as T
    
    train_transform = T.Compose([
        T.RandomResizedCrop(size=(IMAGE_HEIGHT, IMAGE_WIDTH), scale=(0.8, 1.0), ratio=(0.75, 1.33)),
        #T.RandomPerspective(distortion_scale=0.3, p=0.3),
        T.RandomHorizontalFlip(p=0.4),
        T.RandomVerticalFlip(p=0.4),
        T.RandomRotation(degrees=5),
        #T.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.05),
        #T.GaussianBlur(kernel_size=3, sigma=(0.1, 2.0)),
        T.ToTensor(),
    ])
    return train_transform


# %% ../../nbs/47_patching.training_pytorch.ipynb #579f6154
def get_validation_augmentation(
    IMAGE_HEIGHT: int = 256,
    IMAGE_WIDTH: int = 256,

):
    val_transform = T.Compose([
        T.Resize((IMAGE_HEIGHT, IMAGE_WIDTH)),
        T.ToTensor(),
    ])
    return val_transform

# %% ../../nbs/47_patching.training_pytorch.ipynb #f22ad709
def get_dataloader(
    trn_im_path:str, 
    trn_msk_path:str,
    val_im_path:str,
    val_msk_path:str,
    tst_im_path:str=None,
    batch_size:int = 32,
    IMAGE_HEIGHT:int=256,
    IMAGE_WIDTH:int=256,
    num_workers:int=4   
    ):
    'Create datalaoder'
    trn_transform = get_training_augmentation(
        IMAGE_HEIGHT=IMAGE_HEIGHT,
        IMAGE_WIDTH=IMAGE_WIDTH,
    )
    val_transform = get_validation_augmentation(
        IMAGE_HEIGHT=IMAGE_HEIGHT,
        IMAGE_WIDTH=IMAGE_WIDTH,
    )
    if val_im_path is None:
        trn_ds = PinSegmentationDataset(
            image_dir=trn_im_path, 
            mask_dir=trn_msk_path,
            transform=trn_transform)
        trn_ds, val_ds = split_ds(trn_ds, val_split=0.2)
        # changing the trnsforms in case of validation and training datasets
        trn_ds.dataset.transform = trn_transform
        val_ds.dataset.transform = val_transform
    else:
        trn_ds = PinSegmentationDataset(
            image_dir=trn_im_path, 
            mask_dir=trn_msk_path,
            transform=trn_transform)
        val_ds = PinSegmentationDataset(
            image_dir=val_im_path, 
            mask_dir=val_msk_path,
            transform=val_transform)

    trn_dataloader = DataLoader(
        trn_ds, 
        batch_size=batch_size, 
        shuffle=True, 
        num_workers=num_workers
    )
    val_dataloader = DataLoader(
        val_ds, 
        batch_size=batch_size, 
        shuffle=False, 
        num_workers=num_workers
    )
    if tst_im_path:
        tst_ds = InferenceDataset(tst_im_path, transform=val_transform)
        tst_dl = DataLoader(tst_ds, batch_size=batch_size, shuffle=False, num_workers=num_workers)
        return trn_dataloader, val_dataloader, tst_dl
    else:
        return trn_dataloader, val_dataloader


# %% ../../nbs/47_patching.training_pytorch.ipynb #2abaf70d
def get_end_test_model(
	in_channels:int=1,
	out_channels:int=1,
	training:bool=True,
	with_clahe:bool=True,
	with_denoise:bool=True,
	with_bias_field_correction:bool=True
	):
	if training:
		model = ModelForTraining(
			in_channels=in_channels,
			out_channels=out_channels,
			with_clahe=with_clahe,
			with_denoise=with_denoise,
			with_bias_field_correction=with_bias_field_correction
		)
	else:
		model = ModelForInference(
			in_channels=in_channels,
			out_channels=out_channels,
			with_clahe=with_clahe,
			with_denoise=with_denoise,
			with_bias_field_correction=with_bias_field_correction)
	return model
	

# %% ../../nbs/47_patching.training_pytorch.ipynb #ea70cf40
CURRETNT_NB='/home/ai_sintercra/homes/hasan/projects/git_data/new_test/nbs'

# %% ../../nbs/47_patching.training_pytorch.ipynb #ae86bb8d
@call_parse
def main_(
		trn_im_path:Param(type=str, help='Training image path')='',
		trn_msk_path:Param(type=str, help='Training mask path')='',
		val_im_path:Param(type=str, help='Validation image path')='',
		val_msk_path:Param(type=str, help='Validation mask path')='',
		batch_size:Param(type=int, help='Batch size') = 16,
		num_workers:Param(type=int, help='Number of workers') = 1,
		in_channels:Param(type=int, help='Number of input channels') = 1,
		out_channels:Param(type=int, help='Number of output channels') = 1,
		#training:Param(type=bool, help='Training') = True,
		#with_clahe:Param(type=bool, help='With CLAHE') = False,
		#with_denoise:Param(type=bool, help='With denoise') = True,
		#with_bias_field_correction:Param(type=bool, help='With bias field correction') = True,
		lr:Param(type=float, help='Learning rate') = 0.001,
		num_epochs:Param(type=int, help='Number of epochs') = 10,
		device:Param(type=str, help='Device') = 'cuda' if torch.cuda.is_available() else 'cpu',
		threshold:Param(type=float, help='Threshold') = 0.5,
		save_path:Param(type=str, help='Save path') = None,
		model_fn:Param(type=str, help='Model function') = None
):
	#model = get_end_test_model(
		#in_channels=in_channels,
		#out_channels=out_channels,
		#training=training,
		#with_clahe=with_clahe,
		#with_denoise=with_denoise,
		#with_bias_field_correction=with_bias_field_correction)
	model = get_end_test_only_model(
		in_channels=in_channels,
		out_channels=out_channels,
	)

	# Creating dataloaders
	trn_dl, val_dl = get_dataloader(
		trn_im_path=Path(trn_im_path),
		trn_msk_path=Path(trn_msk_path),
		val_im_path=Path(val_im_path),
		val_msk_path=Path(val_msk_path),
		batch_size=batch_size,
		num_workers=num_workers)
	
	# Creating optimizer
	optimizer = torch.optim.Adam(
		model.parameters(), lr=lr)
	metrics = [
		calculate_foreground_iou]
	scheduler = CosineAnnealingLR(
		optimizer,
		T_max=num_epochs,
		eta_min=0.0001)

	loss_fn = monai.losses.FocalLoss(
		include_background=True, 
		gamma=2,
		alpha=0.25,
		use_softmax=False)


	train_and_validate(
		model=model,
		num_epochs=num_epochs,
		optimizer=optimizer,
		scheduler=scheduler,
		train_dataloader=trn_dl,
		val_dataloader=val_dl,
		loss_fn=loss_fn,
		metrics=metrics,
		threshold=0.5,
		device=device,
		save_path=save_path,
		model_fn=model_fn)
	
	

