# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/000_three_channel_data_creation.ipynb.

# %% auto #0
__all__ = ['get_m_name', 'get_pin_type', 'ref_fn_frm_fn', 'pin_count_dict', 'pin_count_from_fn']

# %% ../nbs/000_three_channel_data_creation.ipynb #25039789
from pathlib import Path
from typing import List, Tuple, Dict
import re
import os
import cv2

# %% ../nbs/000_three_channel_data_creation.ipynb #df55d855
from cv_tools.core import *

# %% ../nbs/000_three_channel_data_creation.ipynb #d7c28331
def get_m_name(fn, pat=re.compile(r'(IN|In|OUT|Out).(\d+)')):
    if pat.search(fn) is not None:
        return pat.search(Path(fn).name).group(2)
    else:
        return "9999999"

# %% ../nbs/000_three_channel_data_creation.ipynb #59fe083e
def get_pin_type()->Dict[str,str]:
    return {

        '17': 'solder1B',
        '18': 'solder2B',
        '19': 'pressfitSMART',
        '21': 'pressfit1B',
        '25': 'pressfit2B',
        '34': 'pressfitSMART',
        '36': 'pressfit1B',
        '37': 'pressfit2B',
        '43': 'pressfit2B',
        '46':'pressfit2B',
        '47': 'pressfit2B',
        '49': 'pressfit2B',
        '50': 'pressfit2B',
        '51': 'pressfit1B',
        '53': 'pressfit1B',
        '55': 'pressfit1B',
        '57': 'solder2B',
        '68': 'solder2B',
        '69': 'solder1B',
        '72': 'pressfit2B',
        '75': 'pressfit1B',
        '77': 'pressfit1B',
        '79':'pressfit2B',
        '85': 'pressfit1B',
        '86': 'pressfit1B',
        '87': 'pressfit2B',
        '88': 'pressfit1B',
        '91': 'pressfit2B',
        '92': 'pressfit2B',
        '94': 'pressfit1B',
        '96': 'pressfit2B',
        '97': 'pressfit2B',
        '98': 'pressfit2B',
        '103':'pressfit2B',
        '105': 'pressfit2B',
        '106': 'pressfit1B',
        '108': 'pressfit1B',
        '109': 'pressfit2B',
        '114': 'pressfit1B',
        '117': 'pressfit2B',
        '122': 'pressfit2B',
        '123': 'pressfit2B',
        '125': 'pressfit1B',
        '126': 'pressfit1B',
        '148':'pressfit1B',
        '1': 'OneType',
        '9999999':'undefined_or_generated',
        '999':'undefined_or_generated'
    }

# %% ../nbs/000_three_channel_data_creation.ipynb #4067adf8
def ref_fn_frm_fn(
    fn:str
    )->str:
    name_ = Path(fn).name
    mod_name = get_m_name(name_)
    pin_type = get_pin_type()[mod_name]
    try:
        if '2B' in pin_type:
            return 'ref_image_2B.png'
        elif '1B' in pin_type:
            return 'ref_image_1B.png'
        elif 'SMART' in pin_type:
            return 'ref_image_SMART.png'
    except Exception as e:
        print(e)
        print(f"Cannot find ref image name from {Path(fn).name}")

# %% ../nbs/000_three_channel_data_creation.ipynb #5e428257
def pin_count_dict()->Dict[str,int]:
    return {
        '1': 37, '17': 23, '18': 35, '19': 35, 
        '21': 19, '25': 27,'34': 32, '36': 22, 
        '37': 33, '43': 30, '46':35, '47': 22, '49': 34, 
        '50': 35, '51': 23, '53': 20,'55': 21, 
        '57': 22, '68': 33, '69': 27, '72': 32, 
        '75': 18, '77': 23, '79':36,'85': 24, '86': 18, 
        '87':30,
        '88': 20, '91': 38, '92': 33, '94': 22, 
        '96': 36, '97': 36, '98': 31, '103':33,'105': 33, 
        '106': 16,'108': 22, '109':30,'114': 22, '117': 33, 
        '122': 33, '123': 29, '125': 22, '126': 27, 
        '148': 33
    }

# %% ../nbs/000_three_channel_data_creation.ipynb #b735a093
def pin_count_from_fn(
        fn:str, # filename of mask file
    ):
    'get number of pins found from a mask filename'
    img = read_img(fn, cv=True,gray=True)
    
    lbl, _ = cv2.connectedComponents(img)
    return lbl - 1
