# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/22_extract_pins_from_mask.ipynb.

# %% auto #0
__all__ = ['path', 'custom_lib_path', 'dotenv_p', 'CV_TOOLS', 'PRIVATE_EASY_PIN_DETECTION', 'frm_cntr_to_bbox',
           'compare_sim_and_save', 'compare_sim_and_save_folder', 'parse_args_', 'main_']

# %% ../nbs/22_extract_pins_from_mask.ipynb #41761207
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import cv2
from typing import NewType, List, Tuple, Union, Dict
from pathlib import Path
from scipy.ndimage import label, find_objects
from tqdm.auto import tqdm
from argparse import ArgumentParser, BooleanOptionalAction
import matplotlib as mpl
from fastcore.all import *
from argparse import ArgumentParser, BooleanOptionalAction

# %% ../nbs/22_extract_pins_from_mask.ipynb #404de52e
path=Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/2023_easy_pin_detection/nbs')
custom_lib_path=Path(r'/home/ai_warstein/custom_libs/goni/custom_libs')
sys.path.append(str(custom_lib_path))
from dotenv import load_dotenv
dotenv_p = load_dotenv(Path(Path(path).parent, 'private_easy_pin_detection/.env'))
CV_TOOLS = os.getenv('CV_TOOLS')
PRIVATE_EASY_PIN_DETECTION = os.getenv('PRIVATE_EASY_PIN_DETECTION')
sys.path.append(CV_TOOLS)
sys.path.append(PRIVATE_EASY_PIN_DETECTION)

# %% ../nbs/22_extract_pins_from_mask.ipynb #52b8a854
from cv_tools.core import *
#from labeling_test.grouding_dino_labeling import *

# %% ../nbs/22_extract_pins_from_mask.ipynb #3b716264
def frm_cntr_to_bbox(cntr):
    x,y,w,h = cv2.boundingRect(cntr)
    return x,y,w,h

# %% ../nbs/22_extract_pins_from_mask.ipynb #0a8d10d7
def compare_sim_and_save(
        im_path:str,
        msk_path:str,
        offset:int=40,
        save_im_path:str=None,
        save_msk_path:str=None,
        show:bool=False

    ):
    'Compare first pins with others and then saved dissimilar ones'
    if save_im_path: Path(save_im_path).mkdir(exist_ok=True,parents=True)
    if save_msk_path: Path(save_msk_path).mkdir(exist_ok=True,parents=True)

    try:
        img = read_img(im_path)
    except Exception as e:
        print('image could not be read')
        print(e)
    # mask is read only to get position of selected pins
    msk = read_img(msk_path)

    pins, not_pins =  [], []
    cntrs = find_contours_binary(msk)

    cntrs_ = filter(lambda x: cv2.contourArea(x) > 10, cntrs)
    s_cntrs = filter(lambda x: cv2.contourArea(x) <= 10, cntrs)
    for idx, i in enumerate(s_cntrs):
        x, y, w, h = frm_cntr_to_bbox(i)
        pin_img_s = img[y-offset:y+h+offset,x-offset:x+w+offset]
        if save_im_path:
            cv2.imwrite(f'{save_im_path}/{Path(im_path).stem}_s_c_{idx}.png',i[0])
                
        if save_msk_path:
            cv2.imwrite(f'{save_msk_path}/{Path(im_path).stem}_s_c_{idx}.png',i[1])
    for idx , i in enumerate(cntrs_):
        x,y,w,h = frm_cntr_to_bbox(i)
        pin_img_s = img[y-offset:y+h+offset,x-offset:x+w+offset]
        pin_img = img[y:y+h,x:x+w]
        pin_msk = msk[y:y+h,x:x+w]
        if idx == 0:
            ref_img = pin_img

        else:
            pin_img_r = cv2.resize(
                pin_img,
                (ref_img.shape[1],ref_img.shape[0])
            )
            sim = ssim_(
                ref_img,
                pin_img_r,
                win_size=None,
            )
            if sim < 0.45:
                not_pins.append([pin_img_s, pin_msk])
            else:
                pins.append([pin_img_s, pin_msk])
    
    # there is a possibility my reffernce pin is not actual pin
    # then similarity will be low for all pins , but here i am 
    # checking which has bigger length, pins will be always bigger length
    if (len(pins) > len(not_pins)) and len(not_pins) > 0:
        for idx,i in enumerate(not_pins):
            if show: show_(i)
            if save_im_path:
                cv2.imwrite(f'{save_im_path}/{Path(im_path).stem}_{idx}.png',i[0])
                
            if save_msk_path:
                cv2.imwrite(f'{save_msk_path}/{Path(im_path).stem}_{idx}.png',i[1])
        
    elif (len(pins)< len(not_pins)) and len(pins) > 0:
        for i in pins:
            if show: show_(i)
            if save_im_path:
                cv2.imwrite(f'{save_im_path}/{Path(im_path).stem}_{idx}.png',i[0])
            if save_msk_path:
                cv2.imwrite(f'{save_msk_path}/{Path(im_path).stem}_{idx}.png',i[1])

# %% ../nbs/22_extract_pins_from_mask.ipynb #67174705
def compare_sim_and_save_folder(
        im_path:str, #Could be image list or path to folder
        msk_path:str,#where the masks are saved, will be searched with same name as image
        filter_w:str=None, # whether to filter for specififc words in the files
        offset:int=40,# how much extra area to consider around pin
        save_im_path:str=None, # where to save the images
        save_msk_path:str=None, # where to save the masks
        show:bool=False # whether to show the images or not

    ):

    if filter_w is not None:
        im_list = Path(im_path).filter_(filter_w)
    else:
        im_list = Path(im_path).ls()

    for i in tqdm(im_list, total=len(im_list)):
        name_=Path(i).name
        compare_sim_and_save(
            im_path=i,
            msk_path=f'{msk_path}/{name_}',
            offset=offset,
            save_im_path=save_im_path,
            save_msk_path=save_msk_path,
        )


# %% ../nbs/22_extract_pins_from_mask.ipynb #ff460459
def parse_args_():
    parser = ArgumentParser()
    parser.add_argument(
        '--im_path',
        type=str,
        help='Path to images'
    )
    parser.add_argument(
        '--msk_path',
        type=str,
        help='Path to masks'
    )
    parser.add_argument(
        '--filter_w',
        type=str,
        help='Filter for specific words in the files'
    )
    parser.add_argument(
        '--offset',
        type=int,
        default=40,
        help='How much extra area to consider around pin'
    )
    parser.add_argument(
        '--save_im_path',
        default=None,
        help='Where to save the images'
    )
    parser.add_argument(
        '--save_msk_path',
        default=None,
        help='Where to save the masks'
    )
    return parser.parse_args()

# %% ../nbs/22_extract_pins_from_mask.ipynb #e9fa5de3
def main_():
    args = parse_args_()
    compare_sim_and_save_folder(
        im_path=args.im_path,
        msk_path=args.msk_path,
        filter_w=args.filter_w,
        offset=args.offset,
        save_im_path=args.save_im_path,
        save_msk_path=args.save_msk_path,
    )

# %% ../nbs/22_extract_pins_from_mask.ipynb #d864aec7
if __name__ == '__main__':
    main_()
