# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/17_three_channel_mask_creation.ipynb.

# %% auto #0
__all__ = ['load_model', 'predct_msk']

# %% ../nbs/17_three_channel_mask_creation.ipynb #8d51f558
import os 
from fastcore.all import *
from fastcore.test import *
from fastcore.basics import *
from pathlib import Path    
from tqdm.auto import tqdm
import shutil
import yaml

# %% ../nbs/17_three_channel_mask_creation.ipynb #869e42a7
def load_model(config):
    model = tf.keras.models.load_model(config['model']['save_path'] )
    return model

# %% ../nbs/17_three_channel_mask_creation.ipynb #29e258b4
def predct_msk(
        model:tf.keras.Model,
        im_file:str,
        threshold:float=0.5,
        save_path:str=None
  ):

  img = read_normalize(im_file=im_file, config=config)
  pred = model.predict(img)
  msk = pred[0] > threshold
  msk = msk * 255.0
  msk = msk.astype(np.uint8)
  if save_path:
    cv2.imwrite(save_path, msk)
