# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_mask_accuracy.ipynb.

# %% auto #0
__all__ = ['custom_lib_path', 'current_lib_path', 'CV_TOOLS', 'P_EPD', 'desired_im_folder', 'process_pin_count', 'process_mask',
           'process_mask_folder', 'extract_problems', 'pin_type_accuracy']

# %% ../nbs/01_mask_accuracy.ipynb #89426fa2
import pandas as pd
from pathlib import Path
import numpy as np
from tqdm import tqdm
from fastcore.all import *
import matplotlib as mpl
import matplotlib.pyplot as plt
from fastcore.all import *
import shutil
import cv2
from typing import Union, List, Tuple, Dict
import pandas as pd
from skimage import io, morphology, measure
from scipy.ndimage import (label, sum, binary_fill_holes)
import os
from tqdm.auto import tqdm
import argparse

# %% ../nbs/01_mask_accuracy.ipynb #a8f1fcb2
custom_lib_path = Path("/home/ai_warstein/homes/goni/custom_libs")
current_lib_path = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/new_test')
sys.path.append(str(current_lib_path))
sys.path.append(str(custom_lib_path))
from dotenv import load_dotenv
load_dotenv(dotenv_path="/home/ai_sintercra/homes/hasan/projects/git_data/2023_easy_pin_detection/private_easy_pin_detection/.env")

CV_TOOLS = os.getenv("CV_TOOLS")
P_EPD= os.getenv("PRIVATE_EASY_PIN_DETECTION")
sys.path.append(CV_TOOLS)
sys.path.append(P_EPD)

# %% ../nbs/01_mask_accuracy.ipynb #83d7fe85
from new_test.core import *
from private_easy_pin_detection.extract_patches import *
from private_easy_pin_detection.pin_map import *
from cv_tools.core import *
from cv_tools.cv_ops import *

# %% ../nbs/01_mask_accuracy.ipynb #20160801
def desired_im_folder(
        im_path:Path,#folder for images
        msk_path:Union[Path, None ],#folder for masks
        tmp_path:Path, #folder for templates
        recipe_name:str,
        img_sn_pin_save:Union[Path, str, None]=None, #folder for saving the single pin images 
        msk_sn_pin_save:Union[Path, str, None]=None, #folder for saving the single pin masks
        save_path:Union[Path, str, None]=None #folder for saving the last part
    ):
    'Save only desired positions part from the image or mask'
    
    mask_names = get_name_(msk_path.ls())
    im_names = list(filter(lambda x: x.name in mask_names, msk_path.ls()))

    print(f'Number of images: {len(im_names)}')


    for i in tqdm(im_names, total=len(im_names)):
        name_ = Path(i).name
        full_, _ = desired_im(
            im_path=Path(im_path, name_),
            msk_path=Path(msk_path, name_),
            tmp_path=tmp_path,
            recipe_name=recipe_name,
            img_sn_pin_save_path=img_sn_pin_save,
            msk_sn_pin_save_path=msk_sn_pin_save,
        )
        if save_path is not None:
            cv2.imwrite(str(Path(save_path, name_)), full_)





# %% ../nbs/01_mask_accuracy.ipynb #88b23fa1
def process_pin_count(
    df: pd.DataFrame,  # dataframe containing pin count and difference
):
    return (
        df.assign(
            pin_type=lambda df_: df_['device_name'].astype(str).fillna('Undefined').map(
                lambda x: get_pin_type().get(x, '0'), na_action='ignore'),
            pin_type_g=lambda df_: np.where(
                df_['pin_type'].astype(str).str.contains('pressfit'),
                'pressfit', 'solder'),
            expected=lambda df_: df_['device_name'].astype(str).fillna('Undefined').map(
                lambda x: pin_count_dict().get(x, '0'), na_action='ignore').astype(float),
            expected_vs_diff=lambda df_: df_['pin_no'] - df_['expected']
        )
    )

# %% ../nbs/01_mask_accuracy.ipynb #64815e1b
def process_mask(
        msk_img:np.ndarray, # binary mask
        remove_object_size:80000, # object size
        fill_holes_: bool = True,
        fit_rect_: bool = True,
        show_msk: bool = False
        ):
    if remove_object_size is not None:
        new_mask = remove_small_objects(
            binary_mask=msk_img,
            size_threshold=remove_object_size)
    else:
        new_mask = msk_img
    if fill_holes_:
        new_mask = fill_holes_in_objects(new_mask)
    if fit_rect_:
        new_mask = convert_to_rotated_rectangles(binary_mask=new_mask)
    if show_msk:
        show_(new_mask)
    return new_mask

# %% ../nbs/01_mask_accuracy.ipynb #8703bfd2
def process_mask_folder(
        path:Union[str, Path], # path to mask folder
        remove_object_size:int=80000,
        fil_holes_:bool=True,
        fit_rect_:bool=True,
        save_path:Union[str, Path]=None,
     ):
    'Process(remove small object, fill_holes, fit_rect) all masks inside path'
    fns = Path(path).ls()
    Path(save_path).mkdir(exist_ok=True, parents=True)  
    for i in tqdm(fns, total=len(fns)):
        msk_img = read_img(f'{i}', cv=True, gray='True')
        name_= Path(i).name
        pr_msk = process_mask(
            msk_img=msk_img,
            remove_object_size=remove_object_size,
            fill_holes_=fil_holes_,
            fit_rect_=fit_rect_,
            show_msk=False)
        pr_msk = (pr_msk*255).astype('uint8')
        if save_path is not None:
            cv2.imwrite(f'{save_path}/{name_}', pr_msk)

        

# %% ../nbs/01_mask_accuracy.ipynb #afab31ed
def extract_problems(
        pr_img:np.ndarray, # processed image
        img:np.ndarray,  # actual image
        save_path:Union[Path, None]=None,
        save_name:Union[str, None]=None,
        msk:Union[np.ndarray, None]=None, # actual mask
        save_:bool=False,
        img_show_:bool=False,
        pr_img_show_:bool=False,
        msk_show_:bool=False,
        concat_image_path:Union[Path, None]=None,
        concat_image_name:str=None
        ):
    'cut specific parts from the processed image, where model failed'
    hsv = cv2.cvtColor(pr_img, cv2.COLOR_RGB2HSV)
    # searching for blue color, after reading processed image, it seems problem pins are not red, but blue
    # therefore blue color is searched
    mask = cv2.inRange(hsv, (100,90, 255 ), (120,255, 255))
    label_img = measure.label(mask)
    props = measure.regionprops_table(
        label_img,
        img,
        properties=[
            'label',
            'area',
            'bbox',
            'orientation',
            'euler_number',
            'filled_area',
            'solidity',#circle or not
            'equivalent_diameter']
    )
    if save_:
        Path(save_path).mkdir(exist_ok=True, parents=True)
    if concat_image_path is not None:
        Path(concat_image_path).mkdir(exist_ok=True, parents=True)
    for i in range(len(props['bbox-0'])):
        x_min, y_min, x_max, y_max = props['bbox-0'][i],props['bbox-1'][i], props['bbox-2'][i], props['bbox-3'][i]
        if save_:
            cv2.imwrite(f'{save_path}/{save_name}_{i}.png',img[x_min:x_max, y_min:y_max])
        if img_show_:
            show_(img[x_min:x_max, y_min:y_max])
        if pr_img_show_:
            show_(pr_img[x_min:x_max, y_min:y_max])
        if msk_show_:
            show_(msk[x_min:x_max, y_min:y_max])
        if concat_image_path is not None:
            cnct_img = np.concatenate([img[x_min:x_max, y_min:y_max]], axis=0)
            cv2.imwrite(f'{concat_image_path}/{concat_image_name}', cnct_img)

# %% ../nbs/01_mask_accuracy.ipynb #b3449d79
def pin_type_accuracy(
    df: pd.DataFrame
):
    "Calculate each pin type accuracy"

    df_fail = df.query('expected_vs_diff != 0')['pin_type'].value_counts(
    ).reset_index().rename(columns={'count': 'pin_type', 'count': 'count'})
    print(f'Total number of pins didnot match: {df_fail["count"].sum()}')

    for i in df_fail['pin_type'].unique():
        total_c = len(df.query('pin_type == @i'))
        fail = df_fail.query('pin_type == @i')['count'].values[0]
        print(f'{i} accuracy: {round((total_c-fail)/total_c*100,5)}%')

    print(f' Addtional pin count {"#"*50}')
    df_fail_a = df.query('expected_vs_diff > 0')['pin_type'].value_counts(
    ).reset_index().rename(columns={'count': 'pin_type', 'count': 'count'})
    for i in df_fail_a['pin_type'].unique():
        fail = df_fail_a.query('pin_type == @i')['count'].values[0]
        print(f'{i} had additional pin count = {fail}')

    print(f' Missing pin count {"#"*50}')
    df_fail_m = df.query('expected_vs_diff < 0')['pin_type'].value_counts(
    ).reset_index().rename(columns={'count': 'pin_type', 'count': 'count'})
    for i in df_fail_m['pin_type'].unique():
        fail = df_fail_m.query('pin_type == @i')['count'].values[0]
        print(f'{i} has missing pin count = {fail}')
