# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/17_split_image_and_join_image.ipynb.

# %% auto #0
__all__ = ['get_common_files', 'split_image_to_patches', 'reconstruct_from_patches', 'create_onnx_model_patch', 'patching',
           'reconstruc_from_patches', 'from_im_to_patch_pred']

# %% ../nbs/17_split_image_and_join_image.ipynb #0af572cf
import onnx
import numpy as np
from onnx import helper, numpy_helper
import onnxruntime as ort
import tf2onnx
import cv2
from typing import List, Tuple, Dict, Any
from tqdm.auto import tqdm
import shutil

# %% ../nbs/17_split_image_and_join_image.ipynb #ff275fd4
import tensorflow as tf
from tensorflow.keras.layers import Input, Lambda
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Conv2DTranspose, concatenate, BatchNormalization, Activation, Concatenate

# %% ../nbs/17_split_image_and_join_image.ipynb #f0d70515
from cv_tools.core import *
from pathlib import Path
import os
from typing import Tuple, List, Union

# %% ../nbs/17_split_image_and_join_image.ipynb #4e6558a6
def get_common_files(im_path, msk_path):
    im_files = get_name_(im_path.ls())
    print(f' Number of images: {len(im_files)}')
    msk_files = get_name_(msk_path.ls())
    print(f' Number of masks: {len(msk_files)}')
    common_files = set(im_files).intersection(set(msk_files))
    print(f' Number of common files: {len(common_files)}')
    return common_files

# %% ../nbs/17_split_image_and_join_image.ipynb #b1060d21
def split_image_to_patches(x, patch_size=128):
    # Calculate dynamic padding if needed
    _, height, width, _ = x.shape
    pad_height = (patch_size - height % patch_size) % patch_size
    pad_width = (patch_size - width % patch_size) % patch_size
    x = tf.pad(x, [[0, 0], [0, pad_height], [0, pad_width], [0, 0]], mode='CONSTANT')
    print(x.shape)
    # Reshape into patches
    resized_height, resized_width = x.shape[1], x.shape[2]
    x = tf.reshape(x, (-1, resized_height // patch_size, patch_size, resized_width // patch_size, patch_size, 1))
    x = tf.transpose(x, [0, 1, 3, 2, 4, 5])
    return tf.reshape(x, (-1, patch_size, patch_size, 1))

# %% ../nbs/17_split_image_and_join_image.ipynb #b9e4b26c
def reconstruct_from_patches(
        patches, 
        original_shape, 
        patch_size=128):
    # Assuming patches are square and the batch dimension is flat
    num_patches_per_row = tf.math.ceil(tf.cast(original_shape[1], float) / patch_size)
    num_patches_per_col = tf.math.ceil(tf.cast(original_shape[2], float) / patch_size)


    # Reshape to grid
    patches = tf.reshape(patches, (-1, num_patches_per_row, num_patches_per_col, patch_size, patch_size, original_shape[-1]))
    patches = tf.transpose(patches, [0, 1, 3, 2, 4, 5])
    patches = tf.reshape(patches, (-1, num_patches_per_row * patch_size, num_patches_per_col * patch_size, original_shape[-1]))
    
    # Crop to original dimensions
    return patches[:, :original_shape[1], :original_shape[2], :]

# %% ../nbs/17_split_image_and_join_image.ipynb #534a45b4
def create_onnx_model_patch(
    input_im_shape:Tuple[int, int, int],
    model:tf.keras.models.Model, # Normal model without pre and post processing
    onnx_m_name:str, # Name of the onnx model
    onnx_m_save_path:str, # where to save the  models
    patch_size:int=128

    ):
    'Create onnx model for for patching'
    inputs = Input(shape=input_im_shape)
    patches = Lambda(
        lambda x: split_image_to_patches(
                            x, patch_size=patch_size
                            ))(inputs)
    batch_output = model(patches)
    outputs = Lambda(
        lambda x: reconstruct_from_patches(
                            x, (1,) + input_im_shape, patch_size=patch_size,
                            ))(batch_output)
    new_model = Model(inputs=inputs, outputs=outputs)

    if onnx_m_name is None:
        onnx_m_name = f"converted_model.onnx"

    onnx_model, _ = tf2onnx.convert.from_keras(
        new_model, opset=13, output_path=f"{onnx_m_save_path}/{onnx_m_name}")
    return onnx_model

# %% ../nbs/17_split_image_and_join_image.ipynb #fbe014ff
def patching(
        img,
        patch_size:int=128):
        patch_size_ = [1, patch_size, patch_size, 1]
        strides = [1, patch_size, patch_size, 1]

        patches_e = tf.image.extract_patches(
                images=tf.expand_dims(img[None,...], axis=-1), rates=[1, 1, 1, 1], sizes=patch_size_, strides=strides, padding='VALID')
        
        patch_dim = patches_e.shape[1] * patches_e.shape[2]
        print(f'aft patching: {patches_e.shape}')
        print(patch_dim)
        patches_r = tf.reshape(patches_e, [patch_dim, patch_size, patch_size, 1])

        print(f'aft patching reshape: {patches_r.shape}')
        return patches_r


# %% ../nbs/17_split_image_and_join_image.ipynb #e89b55f2
def reconstruc_from_patches(
        pred_img, 
        img_s:Tuple[int, int, int],
        patch_size:int=128

    ):
    
    n_p_h = img_s[0] // patch_size
    n_p_w = img_s[1] // patch_size


    pred_img_r = tf.reshape(pred_img, [n_p_h, n_p_w, patch_size, patch_size])

    r_img = np.zeros(img_s, dtype=np.float32)

    n_patches_h = n_p_h
    n_patches_w = n_p_w

    for i in range(n_patches_h):
        for j in range(n_patches_w):
            r_img[i * patch_size: (i+1)*patch_size, j * patch_size: (j+1)*patch_size] = pred_img_r[i, j]
    return r_img

# %% ../nbs/17_split_image_and_join_image.ipynb #22d87c02
def from_im_to_patch_pred(
        im_path:Union[str, Path], # image path 
        m_path:Union[str, Path], # model path with filename
        patch_size:int=128,
		threshold:float=0.9

        )->Tuple[np.ndarray, np.ndarray, np.ndarray]: # return image, normalized image, reconstructed mask
   ' Read, normalize image and patch it and batch it and create prediction and reconstruct it'
   img = read_img(im_path)
   # Normalize
   img_n = img / 255.0
   # patching
   p_img = patching(img_n, patch_size=patch_size )
   # loading model
   model = tf.keras.models.load_model(model_path, compile=False)

   # prediction
   pred_img = model.predict(p_img)
   pred_im_t = pred_img > threshold
   r_img = reconstruc_from_patches(pred_im_t, img.shape, patch_size=128)
   return img,img_n, r_img




# %% ../nbs/17_split_image_and_join_image.ipynb #bfe0bba1
def split_image_to_patches(x, patch_size=128):
    # Calculate dynamic padding if needed
    _, height, width, _ = x.shape
    pad_height = (patch_size - height % patch_size) % patch_size
    pad_width = (patch_size - width % patch_size) % patch_size
    x = tf.pad(x, [[0, 0], [0, pad_height], [0, pad_width], [0, 0]], mode='CONSTANT')
    print(x.shape)
    # Reshape into patches
    resized_height, resized_width = x.shape[1], x.shape[2]
    x = tf.reshape(x, (-1, resized_height // patch_size, patch_size, resized_width // patch_size, patch_size, 1))
    x = tf.transpose(x, [0, 1, 3, 2, 4, 5])
    return tf.reshape(x, (-1, patch_size, patch_size, 1))

# %% ../nbs/17_split_image_and_join_image.ipynb #cc10521b
def reconstruct_from_patches(patches, original_shape, patch_size=128.0):
    # Assuming patches are square and the batch dimension is flat
    num_patches_per_row = tf.math.ceil(tf.cast(original_shape[1], float) / patch_size)
    num_patches_per_col = tf.math.ceil(tf.cast(original_shape[2], float) / patch_size)


    # Reshape to grid
    patches = tf.reshape(patches, (-1, num_patches_per_row, num_patches_per_col, patch_size, patch_size, original_shape[-1]))
    patches = tf.transpose(patches, [0, 1, 3, 2, 4, 5])
    patches = tf.reshape(patches, (-1, num_patches_per_row * patch_size, num_patches_per_col * patch_size, original_shape[-1]))
    
    # Crop to original dimensions
    return patches[:, :original_shape[1], :original_shape[2], :]
