# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/19_model_accuracy_and_copy_failed_image.ipynb.

# %% auto #0
__all__ = ['path', 'custom_lib_path', 'dotenv_p', 'CV_TOOLS', 'PRIVATE_EASY_PIN_DETECTION', 'get_logger', 'create_df',
           'get_add_and_mis_fns', 'create_folder', 'move_images', 'move_', 'parse_args_', 'main_']

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #41996713
import numpy as np
import pandas as pd
from pathlib import Path
import logging
from tqdm.auto import tqdm
from fastcore.all import *
import shutil
from argparse import ArgumentParser

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #01ab28be
path=Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/2023_easy_pin_detection/nbs')
custom_lib_path=Path(r'/home/ai_warstein/custom_libs/goni/custom_libs')
sys.path.append(str(custom_lib_path))
from dotenv import load_dotenv
dotenv_p = load_dotenv(Path(Path(path).parent, 'private_easy_pin_detection/.env'))
CV_TOOLS = os.getenv('CV_TOOLS')
PRIVATE_EASY_PIN_DETECTION = os.getenv('PRIVATE_EASY_PIN_DETECTION')
sys.path.append(CV_TOOLS)
sys.path.append(PRIVATE_EASY_PIN_DETECTION)

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #de66f379
from cv_tools.core import *

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #e1ac5f6a
from private_easy_pin_detection.core import *
from private_easy_pin_detection.pin_map import *

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #cf8b647d
def get_logger(file_name):
    # Create a logger object
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)
    
    # Create a file handler
    file_handler = logging.FileHandler(file_name)
    file_handler.setLevel(logging.DEBUG)
    
    # Create a formatter
    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    file_handler.setFormatter(formatter)
    
    # Add the file handler to the logger
    logger.addHandler(file_handler)
    
    return logger

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #e9b355da
def create_df(mask_path):
    df = pd.DataFrame()
    
    len_ = len(Path(mask_path).ls(file_exts='.png'))
    try:
        print(f' number of files found = {len_}')
        for idx, i in tqdm(enumerate(Path(mask_path).ls(file_exts='.png')), 
                            total=len_, desc='creating df'):
            df.loc[idx, 'rec_name'] = get_m_name(f'{i}')
            df.loc[idx, 'file_path'] = f'{i}'
            df.loc[idx, 'fn']  = Path(i).name
            df.loc[idx, 'act_pc'] = pin_count_from_fn(f'{i}')


    
        not_pin = [i for i in set(df['rec_name'].values) if i not in pin_count_dict().keys()]
        if not not_pin:
            print("\033[92m" + f'Number of recipe not found = {not_pin}' + "\033[0m")  # Print in red
        else:
            print("\033[91m" + f'Number of recipe not found = {not_pin}' + "\033[0m")  # Print in green
        df['expected_pc'] = df['rec_name'].map(pin_count_dict())
        df['diff'] = df['act_pc'] - df['expected_pc']
    except Exception as e:
        print(f'Error in create_df = {e}')
    return df


# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #c4a80e1b
def get_add_and_mis_fns(df:pd.DataFrame)->tuple[np.array, np.array, np.array]:
    'Getting additional and missing pins and passsed files separate'
    failed_images_df = df.query('diff != 0')
    print(f'Number of failed images = {len(failed_images_df)}')
    missing_files = list(failed_images_df.query('diff <0')['file_path'].values)
    additional_pins = list(failed_images_df.query('diff >0')['file_path'].values)
    passed_images = list(df.query('diff == 0')['file_path'].values)

    return missing_files, additional_pins, passed_images

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #2929061e
def create_folder(
        folder_name, # full path
        )->None:
    'When folder name is given, then image, mask and overlay folders are created'
    folder_im_path = Path(folder_name, 'images')
    folder_msk_path = Path(folder_name, 'masks')
    folder_overlay_path = Path(folder_name, 'overlay')
    folder_im_path.mkdir(parents=True, exist_ok=True)
    folder_msk_path.mkdir(parents=True, exist_ok=True)
    folder_overlay_path.mkdir(parents=True, exist_ok=True)

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #6459bf00
def move_images(
        name:str, # name of the image file
        im_src:Path,
        msk_src:Path,
        pr_im_src:Path,
        im_dst:Path,
        msk_dst:Path,
        pr_im_dst:Path,
    ):
    'Copy images, masks and overlay images to the destination folders'
    shutil.copyfile(
        f'{im_src}/{name}', 
        f'{im_dst}/{name}')
    shutil.move(
        f'{msk_src}/{name}', 
        f'{msk_dst}/{name}')
    shutil.move(
        f'{pr_im_src}/{name}',
         f'{pr_im_dst}/{name}')


# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #1dd1e1f2
def move_(
    im_path:str,
    msk_path:str,
    overlay_msk_path:str,
        path:str,# whether missing, additional or passed
        file_list:list[str],
        case='missing'
        )->None:
    'If file exist then copy images, masks and overlay images to the destination folders'
    if len(file_list) >=1:
        if case in ['missing', 'additional']:
            create_folder(f'{path}/failed/{case}')
            new_path = Path(f'{path}/failed/{case}')
            for i in tqdm(file_list, total=len(file_list)):
                name_ = Path(i).name
        
                move_images(
                    im_src=im_path,
                    msk_src=msk_path,
                    pr_im_src=overlay_msk_path,
                    name=name_, 
                    im_dst=Path(new_path, 'images'),
                    msk_dst=Path(new_path, 'masks'),
                    pr_im_dst=Path(new_path, 'overlay')
                    )
        else:
            create_folder(f'{path}/passed')
            for i in tqdm(file_list, total=len(file_list)):
                name_ = Path(i).name
                move_images(
                    im_src=im_path,
                    msk_src=msk_path,
                    pr_im_src=overlay_msk_path,
                    name=name_, 
                    im_dst=Path(f'{path}/passed/images'),
                    msk_dst=Path(f'{path}/passed/masks'),
                    pr_im_dst=Path(f'{path}/passed/overlay')
                    )
   

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #6c1c7866
def parse_args_():
    parser = ArgumentParser()
    parser.add_argument(
        '-m', '--mask_path',
        help='Path to the mask folder',
        required=True
    )
    parser.add_argument(
        '-i', '--im_path',
        help='Path to the image folder',
        required=True
    )
    parser.add_argument(
        '-o', '--overlay_path',
        help='Path to the overlay image folder',
        required=True
    )
    parser.add_argument(
        '-l', '--log_file'
        )
    return parser.parse_args()

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #1800d7c6
def main_():
    args = parse_args_() 
    im_path = Path(args.im_path)
    msk_path = Path(args.mask_path)
    overlay_path = Path(args.overlay_path)

    move_images_ = partial(
        move_images,
        im_src=im_path,
        msk_src=msk_path,
        pr_im_src=overlay_path,
    )
    logger = get_logger(args.log_file)

    logger.info('Started creating dataframe')
    df = create_df(msk_path)
    logger.info('Dataframe creation is done')
    logger.info('Started getting missing and additional files')
    print(f'{"#"*50}')
    print(f'{"*"*50}')
    logger.info('Started creating failed and passed iamges')

    # getting missing, addional and passed images
    missing_images, a_images, p_images = get_add_and_mis_fns(df)
    logger.info('Started creating failed and passed iamges')
    print(f'{"#"*50}')

    print(f'{"*"*50}')
    logger.info(f'Number of addtional pins ={len(a_images)}')
    logger.info(f'Number of missing pins ={len(missing_images)}')
    logger.info(f'Number of passed pins ={len(p_images)}')
    logger.info('Working on addtional images')
    move_(
        im_path=im_path,
        msk_path=msk_path,
        overlay_msk_path=overlay_path,
        path=msk_path,
        file_list=a_images,
        case='additional'
    )

    logger.info('Working on Missing pin images')
    move_(
        im_path=im_path,
        msk_path=msk_path,
        overlay_msk_path=overlay_path,
        path=msk_path,
        file_list=missing_images,
        case='missing'
    )
    logger.info('Working on images')
    move_(
        im_path=im_path,
        msk_path=msk_path,
        overlay_msk_path=overlay_path,
        path=msk_path,
        file_list=p_images,
        case='passed'
    )
    print(f'{"#"*50} Done')

# %% ../nbs/19_model_accuracy_and_copy_failed_image.ipynb #684ce7a0
if __name__ == '__main__':
    main_()
