# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/23_patch_image_128.ipynb.

# %% auto #0
__all__ = ['custom_lib_path', 'CURRENT_DIR', 'CV_TOOLS', 'NORMAL_FRONT_PIN', 'OpencvImage', 'patchify_', 'patchify_path',
           'get_common_files', 'min_pixel_msk', 'min_pixel_msk_each_pin', 'parse_args_', 'main_']

# %% ../nbs/23_patch_image_128.ipynb #4904bc8c
import numpy as np
from pathlib import Path
import cv2
import matplotlib.pyplot as plt
from PIL import Image
from fastcore.all import *
from fastcore.basics import *
import matplotlib as mpl
from typing import NewType, Union, Tuple, List
from tqdm.auto import tqdm
import shutil
from argparse import ArgumentParser
import yaml
from scipy.ndimage import label

# %% ../nbs/23_patch_image_128.ipynb #72cb4ecb
custom_lib_path = Path("/home/ai_warstein/homes/goni/custom_libs")
sys.path.append(str(custom_lib_path))
CURRENT_DIR = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/new_test')
CV_TOOLS = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools')
NORMAL_FRONT_PIN = Path(r'/home/ai_sintercra/homes/hasan/easy_front/easy-front-pin-detection')
import sys
sys.path.append(str(CURRENT_DIR))
sys.path.append(str(CV_TOOLS))
sys.path.append(str(NORMAL_FRONT_PIN))

# %% ../nbs/23_patch_image_128.ipynb #672aa84c
from cv_tools.core import *
OpencvImage = NewType('OpencvImage', np.ndarray)

# %% ../nbs/23_patch_image_128.ipynb #52d0b666
def patchify_(
    img:OpencvImage,
    patch_size:int=128,
    msk:Union[OpencvImage,None]=None,
    stem_:str='image_name', # without extension of image name
	min_pixel:int=350,
    save_patch_path:Union[Path,None]=None,
    save_msk_patch:Union[Path,None]=None,

    ):
    'patch iamges and extra part will be zero'
    h, w = img.shape[:2]

    n_p_w = (w + patch_size  - 1 ) // patch_size 
    n_p_h = (h + patch_size  - 1 ) // patch_size


    padded_w = n_p_w  * patch_size
    padded_h = n_p_h  * patch_size
    padded_img = np.zeros((padded_h, padded_w), dtype=img.dtype)
    if msk is not None:
        padded_msk = np.zeros((padded_h, padded_w), dtype=msk.dtype)
        padded_msk[:h, :w] = msk



    if save_msk_patch is not None:
        Path(save_msk_patch).mkdir(exist_ok=True, parents=True)

    
    padded_img[:h, :w] = img



    patches = []
    b_img = np.zeros_like(img)
    for i in range(n_p_h):
        for j in range(n_p_w):

            x = j * patch_size
            y = i * patch_size
            patch = padded_img[y:y+patch_size, x:x+patch_size]
            patch_msk = padded_msk[y:y+patch_size, x:x+patch_size]
            if cv2.countNonZero(patch_msk) > 10:
                cntrs = find_contours_binary(msk)
                new_cntrs = list(filter(lambda x: cv2.contourArea(x)>=min_pixel, cntrs))
                # checking each pin to have specific pixel count
                # if all pin inside the mask has more than min_pixel then copy image and mask
                # checking whether number of pins which has mix pixel 
                # is equal to number of pins in the mask
                if len(new_cntrs) == len(cntrs):
                    if save_patch_path is not None:
                        save_patch_path.mkdir(exist_ok=True, parents=True)
                        cv2.imwrite(str(save_patch_path/f'{stem_}_{i}_{j}.png'), patch)
                    if save_msk_patch is not None:
                        cv2.imwrite(
                            str(
                                save_msk_patch/f'{stem_}_{i}_{j}.png'), 
                                padded_msk[y:y+patch_size, x:x+patch_size])
                        b_img[y:y+patch_size, x:x+patch_size] = img[y:y+patch_size, x:x+patch_size]
                    patches.append(patch)
    return patches, b_img


# %% ../nbs/23_patch_image_128.ipynb #ebe447a7
def patchify_path(
    im_path:Union[Path, str],
    patch_size:int=128,
    save_im_path:Union[Path, str, None]=None,
    save_msk_path:Union[Path, str, None]=None,
    msk_path:Union[Path, str]=None,
	min_pixel:int=350,

  ):
  for i in tqdm(im_path.ls(), total=len(im_path.ls())):
    img = read_img(i)
    if msk_path is not None:
      msk = read_img(msk_path/i.name)
    else:
      msk = None
    parts, b_img = patchify_(
        img=img, 
        patch_size=patch_size,
        stem_=i.stem,
        msk=msk,
		min_pixel=min_pixel,
        save_patch_path=save_im_path,
        save_msk_patch=save_msk_path
        )

# %% ../nbs/23_patch_image_128.ipynb #579546ba
def get_common_files(im_path, msk_path):
    im_files = get_name_(im_path.ls())
    print(f' Number of images: {len(im_files)}')
    msk_files = get_name_(msk_path.ls())
    print(f' Number of masks: {len(msk_files)}')
    common_files = set(im_files).intersection(set(msk_files))
    print(f' Number of common files: {len(common_files)}')
    return common_files

# %% ../nbs/23_patch_image_128.ipynb #baa0300b
def min_pixel_msk(
        im_src:Union[Path, str],
        im_dst:Union[Path, str],
        msk_src:Union[Path, str],
        msk_dst:Union[Path, str],
        min_pixel:int=300
            ):
    'Search for mask and if mask has more than pixel then copy image and mask'

    common_files = get_common_files(im_src, msk_src)

    for i in tqdm(common_files, total=len(common_files)):

        msk = read_img(f'{msk_src}/{i}')
        pxl_cnt  = cv2.countNonZero(msk)
        if pxl_cnt >min_pixel:
            shutil.copyfile(f'{im_src}/{i}', f'{im_dst}/{i}')
            shutil.copyfile(f'{msk_src}/{i}', f'{msk_dst}/{i}')

# %% ../nbs/23_patch_image_128.ipynb #7a6f7d95
def min_pixel_msk_each_pin(
        im_src:Union[Path, str],
        im_dst:Union[Path, str],
        msk_src:Union[Path, str],
        msk_dst:Union[Path, str],
        min_pixel:int=300
            ):
    'Search for mask and if mask has more than pixel then copy image and mask'

    common_files = get_common_files(im_src, msk_src)

    for i in tqdm(common_files, total=len(common_files)):

        msk = read_img(f'{msk_src}/{i}')
        if cv2.countNonZero(msk) > 10:
            cntrs = find_contours_binary(msk)
            #for cnt in cntrs:
                #pa_ = cv2.contourArea(cnt)
                #print(pa_)
            new_cntrs = list(filter(lambda x: cv2.contourArea(x)>=min_pixel, cntrs))

            # checking each pin to have specific pixel count
            # if all pin inside the mask has more than min_pixel then copy image and mask
            # checking whether number of pins which has mix pixel 
            # is equal to number of pins in the mask
            if len(new_cntrs) == len(cntrs):


                shutil.copyfile(f'{im_src}/{i}', f'{im_dst}/{i}')
                shutil.copyfile(f'{msk_src}/{i}', f'{msk_dst}/{i}')

# %% ../nbs/23_patch_image_128.ipynb #f4f116b8
def parse_args_():
    parser = ArgumentParser()
    parser.add_argument(
        '--im_path',
        type=str,
        required=True,
        help='Path of the image'
    )
    parser.add_argument(
        '--msk_path',
        type=str,
        required=True,
        help='Path of the mask'
    )
    parser.add_argument(
        '--min_pixel',
        type=int,
        required=True,
        help='Minimum pixel count'
    )
    parser.add_argument(
        '--patch_size',
        type=int,
        default=128,
        help='Patch size'
    )
    parser.add_argument(
        '--save_im_path',
        type=str,
        default=None,
        help='Path to save image patches'
    )
    parser.add_argument(
        '--save_msk_path',
        type=str,
        default=None,
        help='Path to save mask patches'
    )
    return parser.parse_args()

# %% ../nbs/23_patch_image_128.ipynb #5f398f13
def main_():
    args = parse_args_()
    im_path = Path(args.im_path)
    msk_path = Path(args.msk_path)
    save_im_path = Path(args.save_im_path) if args.save_im_path is not None else None
    save_msk_path = Path(args.save_msk_path) if args.save_msk_path is not None else None
    patchify_path(
        im_path=im_path, 
        patch_size=args.patch_size, 
        save_im_path=save_im_path, 
        save_msk_path=save_msk_path, 
        msk_path=msk_path,
        min_pixel=args.min_pixel
        )

# %% ../nbs/23_patch_image_128.ipynb #837bf6c9
if __name__ == '__main__':
    main_()
