# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_pin_map.ipynb.

# %% auto #0
__all__ = ['get_full_image', 'test', 'split_image_no', 'desired_im', 'pin_map17', 'get_all_columns_17', 'pin_map18',
           'get_all_columns_18', 'pin_map19', 'get_all_columns_19', 'frm_im2_im1_name', 'frm_im1_im2_name',
           'frm_im2_pr_name', 'pin_map21', 'get_all_columns_21', 'pin_map25', 'get_all_columns_25', 'pin_map37',
           'get_all_columns_37', 'pin_map43', 'get_all_columns_43', 'pin_map46', 'get_all_columns_46', 'pin_map47',
           'get_all_columns_47', 'pin_map49', 'get_all_columns_49', 'pin_map50', 'get_all_columns_50', 'pin_map51',
           'get_all_columns_51', 'pin_map55', 'get_all_columns_55', 'pin_map57', 'get_all_columns_57', 'pin_map68',
           'get_all_columns_68', 'pin_map77', 'get_all_columns_77', 'pin_map79', 'get_all_columns_79', 'pin_map87',
           'get_all_columns_87', 'pin_map88', 'get_all_columns_88', 'pin_map91', 'get_all_columns_91', 'pin_map92',
           'get_all_columns_92', 'pin_map96', 'get_all_columns_96', 'pin_map97', 'get_all_columns_97', 'pin_map103',
           'get_all_columns_103', 'pin_map105', 'get_all_columns_105', 'pin_map108', 'get_all_columns_108',
           'pin_map122', 'get_all_columns_122', 'pin_map123', 'get_all_columns_123', 'pin_map125',
           'get_all_columns_125', 'full_image_108', 'desired_im_108', 'extract_pins', 'parse_args_', 'main']

# %% ../nbs/02_pin_map.ipynb #2b0bc96d
from typing import List, Dict, Union
import numpy as np
from pathlib import Path
from cv_tools.core import *
import inspect
import cv2
from argparse import ArgumentParser
import matplotlib as mpl
from tqdm.auto import tqdm
import os
from fastcore.basics import *
from fastcore.all import *
from collections import Counter
import shutil
from PIL import Image

# %% ../nbs/02_pin_map.ipynb #d8f7ad92
def get_full_image(
        img:np.ndarray,
        im_name:str,
        col_bbox:Dict[int, List[int]],
        recipe_no:str,
        save_path:Union[str, None]=None,
   ):
  'Get image of all the columns'

  num_cols_ = split_image_no()[recipe_no]



  pin_map_func =f'pin_map{recipe_no}'

  last_mask = np.zeros_like(img)
  pin_index_func=globals()[pin_map_func]
  all_cols = []
  num_cols = len(pin_index_func().keys())

  for col_no in range(num_cols):
        col_bbox_coord = col_bbox[col_no]

        col_data = img[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]]
        pin_indexes = pin_index_func()[col_no]
        single_col_parts = split_image(col_data, num_cols_, 'vertical')
        parts=[]
        for idx, part in enumerate(single_col_parts):
            if idx in pin_indexes:
                part = part
                if save_path is not None:
                    cv2.imwrite(f'{save_path}/{im_name}_col_{col_no}_{idx}.png', part)
                #TODO: add pin mask
            else:
                part = np.zeros_like(part)
            parts.append(part)
        sn_col=np.concatenate(parts, axis=0)

        last_mask[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]] = sn_col
        all_cols.append(sn_col)
  full_part = np.concatenate(all_cols, axis=1)
  return last_mask, full_part


# %% ../nbs/02_pin_map.ipynb #50fbc781
def test(
        im_path:str,
        im_name:str,
        tmp_path:str,
        recipe_no:str,

    ):
    img = read_img(f'{im_path}/{im_name}')
    name_ = im_name
    pin_map_func = f'pin_map{recipe_no}'
    last_mask = np.zeros_like(img)
    pin_index_func=globals()[pin_map_func]
    all_cols=[]
    num_cols = len(pin_index_func().keys())
    bbox_func = globals()[f'get_all_columns_{recipe_no}']
    col_bbox = bbox_func(
                            img,
                            read_img(tmp_path)
                            )

    last_part, img_part = get_full_image(
        img=img,
        im_name=name_,
        col_bbox=col_bbox,
        recipe_no=recipe_no
        )
    show_(img_part)

# %% ../nbs/02_pin_map.ipynb #a7eece05
def split_image_no():
   return {
      '17':9,
      '18':11, 
      '19':11,
      '21':9,
      '25':11,
      '37':11,
      '43':11,
      '46':11,
      '47':11,
      '49':11,
      '50':11,
      '51':9,
      '55':9,
      '57':9,
      '68':11,
      '77':9,
      '79':11,
      '87':11,
      '88':9,
      '91':11,
      '92':11,
      '94':9,
      '96':11,
      '97':11,
      '103':11,
      '105':11,
      '108':9, 
      '122':11,
      '123':11,
      '125':9,
      '148': 11
      }

# %% ../nbs/02_pin_map.ipynb #f030b698
def get_full_image(
        img:np.ndarray,
        im_name:str,
        col_bbox:Dict[int, List[int]],
        recipe_no:str,
        save_path:Union[str, None]=None,
   ):
  'Get image of all the columns'

  num_cols_ = split_image_no()[recipe_no]



  pin_map_func =f'pin_map{recipe_no}'

  last_mask = np.zeros_like(img)
  pin_index_func=globals()[pin_map_func]
  all_cols = []
  num_cols = len(pin_index_func().keys())

  for col_no in range(num_cols):
        col_bbox_coord = col_bbox[col_no]

        col_data = img[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]]
        pin_indexes = pin_index_func()[col_no]
        single_col_parts = split_image(col_data, num_cols_, 'vertical')
        parts=[]
        for idx, part in enumerate(single_col_parts):
            if idx in pin_indexes:
                part = part
                if save_path is not None:
                    cv2.imwrite(f'{save_path}/{im_name}_col_{col_no}_{idx}.png', part)
                #TODO: add pin mask
            else:
                part = np.zeros_like(part)
            parts.append(part)
        sn_col=np.concatenate(parts, axis=0)

        last_mask[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]] = sn_col
        all_cols.append(sn_col)
  full_part = np.concatenate(all_cols, axis=1)
  return last_mask, full_part


# %% ../nbs/02_pin_map.ipynb #f0400528
def desired_im( 
              im_path:Union[str,Path],
              tmp_path:Union[str,Path],
              msk_path:Union[str, Path,None],
              img_sn_pin_save_path:Union[str, None]=None,
              msk_sn_pin_save_path:Union[str, None]=None,
              recipe_name:str='91',
                ):
    ''

    # reading all the images
    img = read_img(im_path, cv=True, gray=True) 
    tmp_img = read_img(tmp_path, cv=True, gray=True)
    if msk_path is not None:
        msk_img = read_img(msk_path, cv=True, gray=True)
    

    name_ = Path(im_path).name

    bbox_func = globals()[f'get_all_columns_{recipe_name}']


    col_bbox = bbox_func(
                                img,
                                tmp_img
                                )

    last_part, img_part = get_full_image(
        img=img,
        im_name=name_,
        save_path=img_sn_pin_save_path,
        col_bbox=col_bbox,
        recipe_no=recipe_name
        )
    if msk_path is not None:
        last_part, mask_part = get_full_image(
                                img=msk_img,
                                im_name=name_,
                                col_bbox=col_bbox,
                                recipe_no=recipe_name,
                                save_path=msk_sn_pin_save_path,
                                )
        return last_part, mask_part
    else:
        return last_part, img_part
    

   

# %% ../nbs/02_pin_map.ipynb #83da6d3b
def pin_map17(

   )->Dict:
   'Return recipe no 125 pin positions'
   return {
    0:[0, 8],
    1:[0, 8],
    2:[8],
    3:[0,8],
    4:[0,8],
    5:[3,8],
    6:[0,3,8],
    7:[0, 6, 8],
    8:[2, 4, 6, 8],
    9:[],
    10:[0,8],
   }

def get_all_columns_17(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' Get bounding box for all columns in 57 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=150
    y1=927
    x0 = x - 77
    c_d={}
    for i in range(11):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #38d9a9d7
def pin_map18(

) -> Dict:
   'Return recipe no 18 pin positions'
   return {
    0:[0, 1, 4, 7, 10],
    1:[0, 10],
    2:[10],
    3:[10],
    4:[0,10],
    5:[0,10],
    6:[0,10],
    7:[10],
    8:[10],
    9:[0,3, 7, 10],
    10:[0, 3, 10],
    11:[0],
    12:[5,6],
    13:[2,3],
    14:[0,7,10],
    15:[0,7,10]
   }

def get_all_columns_18(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' Get bounding box for all columns in 57 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=105
    y1=1070
    x0 = x - 264
    c_d={}
    for i in range(16):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #91746d2f
def pin_map19(

) -> Dict:
   'Return recipe no 19 pin positions'
   return {
    0:[0, 3, 10],
    1:[0, 5, 10],
    2:[0, 10],
    3:[10],
    4:[10],
    5:[0,10],
    6:[0,10],
    7:[0,10],
    8:[10],
    9:[10],
    10:[0, 4, 7,10],
    11:[0, 1, 4],
    12:[],
    13:[],
    14:[0,8,10],
    15:[0, 2, 3, 5, 6, 8,10]
   }

def get_all_columns_19(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' Get bounding box for all columns in 57 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=145
    y1=1085
    x0 = x - 530
    c_d={}
    for i in range(16):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #7ca934f7
def frm_im2_im1_name(name_:str):
    return name_.replace('image2', 'image1')

# %% ../nbs/02_pin_map.ipynb #04e38fd0
def frm_im1_im2_name(name_:str):
    return name_.replace('image1', 'image2')

# %% ../nbs/02_pin_map.ipynb #10ea1a96
def frm_im2_pr_name(name_:str):
    return name_.replace('image2', 'processed_image')

# %% ../nbs/02_pin_map.ipynb #143dc355
def pin_map21(

   )->Dict:
   '1B Return recipe no 51 pin positions'
   return {
    0:[0,3,4, 8],
    1:[0, 8],
    2:[],
    3:[],
    4:[0,5, 8],
    5:[0,5],
    6:[0,8],
    7:[],
    8:[5],
    9:[0,5],
    10:[0,7,8],
   }

def get_all_columns_21(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' 1B Get bounding box for all columns in 51 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=93
    y1=880
    x0 = x - 88
    c_d={}
    for i in range(11):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #7a4390a5
def pin_map25(

   )->Dict:
   '2B Return recipe no 46 pin positions'
   return {
    0:[0, 4,5,10],
    1:[10],
    2:[],
    3:[10],
    4:[0,10],
    5:[10],
    6:[0,10],
    7:[0],
    8:[0,9,10],
    9:[0,9,10],
    10:[10],
    11:[],
    12:[10],
    13:[10],
    14:[10],
    15:[0,2,4,5,10],
   }

def get_all_columns_25(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' 2B Get bounding box for all columns in 46 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=50
    y1=1005
    x0 = x - 270
    c_d={}
    for i in range(16):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #d567b9fb
def pin_map37(

   )->Dict:
   '2B Return recipe no 37 pin positions'
   return {
    0:[0, 1,2,3,4,5,6,7,8,9,10],
    1:[0,3,6,10],
    2:[],
    3:[],
    4:[],
    5:[],
    6:[10],
    7:[6],
    8:[6],
    9:[6,10],
    10:[6],
    11:[],
    12:[],
    13:[],
    14:[0,6,10],
    15:[0,1,2,4,5,6,8,9,10],
   }

def get_all_columns_37(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' 2B Get bounding box for all columns in 37 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=104
    y1=1055
    x0 = x - 260
    c_d={}
    for i in range(16):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #6885ff69
def pin_map43(

   )->Dict:
   '2B Return recipe no 43 pin positions'
   return {
    0:[0,4,5,6,7,10],
    1:[0,10],
    2:[],
    3:[],
    4:[8],
    5:[8],
    6:[3,4],
    7:[0,7,10],
    8:[0,7,10],
    9:[3,4],
    10:[8],
    11:[8],
    12:[],
    13:[],
    14:[0,10],
    15:[0,4,5,6,7,10],
   }

def get_all_columns_43(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' 2B Get bounding box for all columns in 37 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=52
    y1=1015
    x0 = x - 265
    c_d={}
    for i in range(16):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #7e6b7b55
def pin_map46(

   )->Dict:
   'Return recipe no 46 pin positions'
   return {
    0:[0, 9,10],
    1:[0],
    2:[6,10],
    3:[10],
    4:[0,1, 3,7],
    5:[0,7,10],
    6:[0,1,3,10],
    7:[6],
    8:[0,10],
    9:[0,8,10],
    10:[1,8],
    11:[0,10],
    12:[3,10],
    13:[6],
    14:[0,10],
    15:[0,10],
   }

def get_all_columns_46(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' Get bounding box for all columns in 46 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=102
    y1=1062
    x0 = x - 270
    c_d={}
    for i in range(16):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #d358a01c
def pin_map47(

   )->Dict:
   'Return recipe no 46 pin positions'
   return {
    0:[0, 6,7,10],
    1:[0,10],
    2:[],
    3:[],
    4:[],
    5:[],
    6:[3,4],
    7:[0,7,10],
    8:[0,7,10],
    9:[3,4],
    10:[],
    11:[],
    12:[],
    13:[],
    14:[0,10],
    15:[0,6,7,10],
   }

def get_all_columns_47(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' Get bounding box for all columns in 46 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=55
    y1=1010
    x0 = x - 275
    c_d={}
    for i in range(16):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #fe3c89ae
def pin_map49(

   )->Dict:
   '2BReturn recipe no 50 pin positions'
   return {
    0:[0, 2,3, 4,5, 7,9, 10],
    1:[0,7],
    2:[3,10],
    3:[10],
    4:[],
    5:[10],
    6:[5,9],
    7:[3],
    8:[10],
    9:[0,3,10],
    10:[0,3],
    11:[],
    12:[2],
    13:[2],
    14:[0,10],
    15:[0,3,4,6,7,9,10],
   }

def get_all_columns_49(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' 2B Get bounding box for all columns in 50 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=60
    y1=1010
    x0 = x - 270
    c_d={}
    for i in range(16):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #0d81ea21
def pin_map50(

   )->Dict:
   '2BReturn recipe no 50 pin positions'
   return {
    0:[0, 1, 4, 7, 10],
    1:[0, 10],
    2:[10],
    3:[10],
    4:[0,10],
    5:[0,10],
    6:[0,10],
    7:[10],
    8:[10],
    9:[0,3,7,10],
    10:[0,3,10],
    11:[0],
    12:[5,6],
    13:[2,3],
    14:[0,7,10],
    15:[0,7,10],
   }

def get_all_columns_50(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' 2B Get bounding box for all columns in 50 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=102
    y1=1065
    x0 = x - 260
    c_d={}
    for i in range(16):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #f2a4e0e1
def pin_map51(

   )->Dict:
   '1B Return recipe no 51 pin positions'
   return {
    0:[0, 8],
    1:[0, 8],
    2:[8],
    3:[0,8],
    4:[0,8],
    5:[3, 8],
    6:[0,3,8],
    7:[0,6,8],
    8:[2,4,6,8],
    9:[],
    10:[0,8],
   }

def get_all_columns_51(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' 1B Get bounding box for all columns in 51 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=150
    y1=930
    x0 = x - 87
    c_d={}
    for i in range(11):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #a23aae97
def pin_map55(

   )->Dict:
   ' 1B Return recipe no 55 pin positions'
   return {
    0:[0, 1,2, 3, 8],
    1:[0, 8],
    2:[8],
    3:[],
    4:[4],
    5:[3,5],
    6:[8],
    7:[0,5,8],
    8:[0],
    9:[0],
    10:[0,6,7,8],
   }

def get_all_columns_55(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' 1B Get bounding box for all columns in 55 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=150
    y1=927
    x0 = x - 97
    c_d={}
    for i in range(11):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #38b44b54
def pin_map57(

   )->Dict:
   'Return recipe no 57 pin positions'
   return {
    0:[0, 2, 3, 6, 8],
    1:[0, 8],
    2:[0,8],
    3:[],
    4:[5],
    5:[5],
    6:[],
    7:[5],
    8:[5],
    9:[0,8],
    10:[0,1, 3, 5,6,7,8],
   }

def get_all_columns_57(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' Get bounding box for all columns in 57 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=150
    y1=927
    x0 = x - 77
    c_d={}
    for i in range(11):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #4f8fa4c4
def pin_map68():
  '2B Pin mapping for recipe 68'
  return {
        0:[0,1,2,3,4,5,6,7,8,9,10],
        1:[0, 3,6,10],
        2:[],
        3:[],
        4:[],
        5:[],
        6:[10],
        7:[6],
        8:[6],
        9:[6,10],
        10:[6],
        11:[],
        12:[],
        13:[],
        14:[0,6,10],
        15:[0,1,2,4,5,6,8,9,10]
        }

#| export
def get_all_columns_68(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  '2B based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=45
  y1=1015
  x0 = x - 278
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #292d2f37
def pin_map77():
    '1B Pin mapping for recipe 77'
    return {
        0:[0,4,6,8],
        1:[0,8],
        2:[],
        3:[0,2],
        4:[0],
        5:[8],
        6:[0,2,4,6,8],
        7:[0],
        8:[],
        9:[0,2,8],
        10:[0,4,6,8],
        }

def get_all_columns_77(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' Get bounding box for all columns in 77 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=95
    y1=880
    x0 = x - 87
    c_d={}
    for i in range(11):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #b0906925
def pin_map79():
  '2B Pin mapping for recipe 79'
  return {
        0:[0,1,2,6,7,10],
        1:[0, 1,10],
        2:[4],
        3:[],
        4:[0,1,8,9],
        5:[],
        6:[0,4,5],
        7:[0],
        8:[],
        9:[4,5],
        10:[5],
        11:[0,1, 8,9],
        12:[5],
        13:[4],
        14:[0,1, 10],
        15:[0,1,2,6,7,10]
        }

#| export
def get_all_columns_79(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  '2B based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=102
  y1=1065
  x0 = x - 270
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #9b27ea02
def pin_map87():
  'Pin mapping for recipe 87'
  return {
        0:[3,4,10],
        1:[0, 10],
        2:[0,10],
        3:[],
        4:[0,10],
        5:[0,10],
        6:[4],
        7:[4,8],
        8:[6,7,8],
        9:[1,2],
        10:[6,10],
        11:[0,6,10],
        12:[10],
        13:[0],
        14:[0,10],
        15:[0,10]
        }

# %% ../nbs/02_pin_map.ipynb #6c24c5a5
def get_all_columns_87(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  'based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=102
  y1=1065
  x0 = x - 270
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #18b6a0f3
def pin_map88():
    '1B Pin mapping for recipe 88'
    return {
        0:[0,7,8],
        1:[2],
        2:[0],
        3:[0,8],
        4:[0,5],
        5:[0,5],
        6:[0,2,5],
        7:[0,8],
        8:[8],
        9:[0,2],
        10:[0],
        }

def get_all_columns_88(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' Get bounding box for all columns in 88 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=100
    y1=880
    x0 = x - 87
    c_d={}
    for i in range(11):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #ba65ab4c
def pin_map91():
  'Pin mapping for recipe 91'
  return {
        0:[0,10],
        1:[0, 6],
        2:[0,6,10],
        3:[3],
        4:[3,8,9,10],
        5:[0],
        6:[0,4,5,10],
        7:[0],
        8:[3,4,10],
        9:[],
        10:[0,3,4,8,9,10],
        11:[0,8,9,10],
        12:[],
        13:[0, 5,6,10],
        14:[0],
        15:[0,10]
        }

# %% ../nbs/02_pin_map.ipynb #099a0dc4
def get_all_columns_91(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  'based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=62
  y1=1005
  x0 = x - 280
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #6375ca9f
def pin_map92():
  'Pin mapping for recipe 92'
  return {
        0:[0,1,2, 3, 4, 5, 6,7,8,9,10],
        1:[0,3, 6,10],
        2:[],
        3:[],
        4:[],
        5:[],
        6:[10],
        7:[6],
        8:[6],
        9:[6,10],
        10:[6],
        11:[],
        12:[],
        13:[],
        14:[0,6,10],
        15:[0,1,2,4,5,6, 8,9,10]
        }

def get_all_columns_92(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  'based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=55
  y1=1010
  x0 = x - 275
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #249366ad
def pin_map96():
  'Pin mapping for recipe 96'
  return {
        0:[0,10],
        1:[0,10],
        2:[0,10],
        3:[10],
        4:[8,9,10],
        5:[],
        6:[0,10],
        7:[0,4,9,10],
        8:[1,2,4,9,10],
        9:[0,9,10 ],
        10:[0,5],
        11:[0,5,9,10],
        12:[10],
        13:[10],
        14:[0,10],
        15:[0,10]
        }

def get_all_columns_96(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  'based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=55
  y1=1010
  x0 = x - 265
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #3edfe564
def pin_map97():
  'Pin mapping for recipe 97'
  return {
        0:[0,10],
        1:[0,10],
        2:[0,10],
        3:[10],
        4:[8,9,10],
        5:[],
        6:[0,9,10],
        7:[0,4,9,10],
        8:[1,2,4,9,10],
        9:[0,10 ],
        10:[0,5],
        11:[0,5,9,10],
        12:[10],
        13:[10],
        14:[0,10],
        15:[0,10]
        }

def get_all_columns_97(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  'based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=60
  y1=1000
  x0 = x - 280
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #e7ddbf20
def pin_map103():
  '2B Pin mapping for recipe 105'
  return {
        0:[0,2,6,7,9,10],
        1:[0],
        2:[0,10],
        3:[10],
        4:[0],
        5:[10],
        6:[0,10],
        7:[0,7,6],
        8:[9,10],
        9:[0,10],
        10:[0],
        11:[0,9,10],
        12:[10],
        13:[0],
        14:[0,10],
        15:[0,9,10]
        }

def get_all_columns_103(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  '2B based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=110
  y1=1055
  x0 = x - 265
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #b3d42781
def pin_map105():
  '2B Pin mapping for recipe 105'
  return {
        0:[0,4,5,9,10],
        1:[0,10],
        2:[0,10],
        3:[1,2],
        4:[0,10],
        5:[0,10],
        6:[10],
        7:[3,10],
        8:[6,7,9,10],
        9:[],
        10:[],
        11:[2,3,4],
        12:[9,10],
        13:[9,10],
        14:[],
        15:[0,3,9,10]
        }

def get_all_columns_105(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  '2B based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=55
  y1=1010
  x0 = x - 275
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #aefcc47c
def pin_map108():
    '1B Pin mapping for recipe 108'
    return {
        0:[0,1, 2,3, 5, 6,7,8],
        1:[],
        2:[],
        3:[8],
        4:[8],
        5:[],
        6:[],
        7:[4],
        8:[4],
        9:[0,1, 4, 7,8],
        10:[0, 1, 4, 7,8],
        }

def get_all_columns_108(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  '2B based on template image get all the columns'
  bbox = get_template_part(
  tst_img,
  tmp_img
  )
  x, y, w, h = bbox
  y0=160
  y1=935
  x0 = x - 77
  c_d={}
  for i in range(11):
      x1 = x0 + 87
      c_d[i] = [y0, y1, x0, x1]
      x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #9ec5c501
def pin_map122():
  'Pin mapping for recipe 122'
  return {
        0:[0,1,10],
        1:[3, 6],
        2:[3,6],
        3:[10],
        4:[1,7,8],
        5:[1, 10],
        6:[3, 6],
        7:[6,10],
        8:[1, 8],
        9:[1, 8],
        10:[3,6,10],
        11:[6],
        12:[1,10],
        13:[1,7,8],
        14:[10],
        15:[2, 3]
        }

def get_all_columns_122(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  'based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=44
  y1=1015
  x0 = x - 278
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #8866deeb
def pin_map123():
  'Pin mapping for recipe 122'
  return {
        0:[0,3,4,10],
        1:[0,10],
        2:[10],
        3:[10],
        4:[0],
        5:[0, 10],
        6:[0,5,10],
        7:[],
        8:[],
        9:[0, 5,6],
        10:[0,9,10],
        11:[0,9,10],
        12:[],
        13:[],
        14:[0,9,10],
        15:[0,9,10]
        }

def get_all_columns_123(
    tst_img:np.ndarray,# opencv image
    tmp_img:np.ndarray # opencv image
    ):
  'based on template image get all the columns'
  bbox = get_template_part(
    tst_img,
    tmp_img
    )
  x, y, w, h = bbox
  y0=55
  y1=1010
  x0 = x - 275
  c_d={}
  for i in range(16):
    x1 = x0 + 87
    c_d[i] = [y0, y1, x0, x1]
    x0 = x1
  return c_d

# %% ../nbs/02_pin_map.ipynb #e74ba55a
def pin_map125():
  'Pin mapping for recipe 125'
  return {
        0:[0,1,4,5,6,8],
        1:[8],
        2:[],
        3:[0],
        4:[0,5,8],
        5:[5,8],
        6:[0],
        7:[0],
        8:[],
        9:[0,2,3,4,6,7],
        10:[0],
        }

def get_all_columns_125(
        tst_img:np.ndarray, #open cv image
        tmp_img:np.ndarray, #open cv image
        ):
    ' Get bounding box for all columns in 57 template'
    bbox = get_template_part(
    tst_img,
    tmp_img
    )
    x, y, w, h = bbox
    y0=110
    y1=890
    x0 = x - 87
    c_d={}
    for i in range(11):
        x1 = x0 + 87
        c_d[i] = [y0, y1, x0, x1]
        x0 = x1
    return c_d

# %% ../nbs/02_pin_map.ipynb #b088c70e
def pin_map108(

   )->Dict:
   'Return recipe no 108 pin positions'
   return {
    0:[0,1,2,3,5,6,7, 8],
    1:[],
    2:[],#1
    3:[8],#1
    4:[8],
    5:[],
    6:[],
    7:[4],
    8:[4], #6
    9:[0,1,4,7,8],
    10:[0,1,4,7,8],
   }


def full_image_108(
    img:np.ndarray,
    col_bbox:Dict,
    num_cols:int=11,
   ):
    'get full image mask for 108 recipe'

    last_mask = np.zeros_like(img)
    # getting current function name
    fn = inspect.currentframe().f_code.co_name
    fn_ = fn.split('_')[-1]
    pin_map_func=f'pin_map{fn_}'

    pin_pos_func =globals()[pin_map_func]
    all_cols = []
    for col_no in range(num_cols):
        col_bbox_coord = col_bbox[col_no]
        col_data = img[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]]
        pin_indexes = pin_pos_func()[col_no]
        single_col_parts = split_image(col_data, 9, 'vertical')
        parts=[]
        for idx, part in enumerate(single_col_parts):
            if idx in pin_indexes:
                part = part
                #TODO: add pin mask
            else:
                part = np.zeros_like(part)
            parts.append(part)
        sn_col=np.concatenate(parts, axis=0)

        last_mask[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]] = sn_col
        all_cols.append(sn_col)
    full_part = np.concatenate(all_cols, axis=1)
    return last_mask, full_part


def desired_im_108( 
                  img:np.ndarray,
                  tmp_img:np.ndarray,
                  msk_img:np.ndarray=None,
                  num_cols:int=11,
                ):
    'From tempalte part get the desired image'

    # getting current function name
    fn = inspect.currentframe().f_code.co_name
    fn_ = fn.split('_')[-1]

    # assingning function name
    all_cols_func = globals()[f'get_all_columns_{fn_}']

    col_bbox = all_cols_func(
                                img,
                                tmp_img
                                )

    func_name = globals()[f'full_image_{fn_}']
    last_part, img_part = func_name(
        img=img,
        col_bbox=col_bbox,
        num_cols=num_cols,
        )
    if msk_img is not None:
        last_part, mask_part = func_name(
                                img=msk_img,
                                col_bbox=col_bbox,
                                num_cols=num_cols,
                                )
        return last_part, mask_part
    else:
        return last_part, img_part
    

# %% ../nbs/02_pin_map.ipynb #1e26c34e
def extract_pins(
        im_path:str, #folder where all the images are available 
        msk_path:str, # mask folder where all the masks are available
        tmp_path:str, # path to the template only path, here one file named recipe_name.png should be there
        recipe_name:str, # name of the recipe
        img_sn_pin_save_path:str, # path where the images with pins will be saved
        img_sn_pin_msk_save_path:str, # path where the images with pins and masks will be saved
        ):

    for i in Path(im_path).ls():
        if msk_path is not None:
            msk_name=f'{msk_path}/{Path(i).name}',
        else:
            msk_name=None
        tmp_img = read_img(f'{tmp_path}/{recipe_name}.png', gray=True, cv=True)

        desired_im(
            im_path=i,
            msk_path=msk_name,
            tmp_path=tmp_path,
        )

# %% ../nbs/02_pin_map.ipynb #a4f3faf2
def parse_args_():
    'get all the arguments'
    parser = ArgumentParser()
    parser.add_argument(
        '--im_path',
        help='folder where all the images are available',
    )
    parser.add_argument(    
        '--msk_path',
        help='mask folder where all the masks are available',
        type=str,
    )
    parser.add_argument(
        '--tmp_path',
        type=str,
        help='path to the template only path, here one file named recipe_name.png should be there',
    )
    parser.add_argument(
        '--recipe_name',
        type=str,
        help='name of the recipe',
    )
    parser.add_argument(
        '--img_sn_pin_save_path',
        type=str,
        default=None,
        help='path where the single pin images with pins will be saved',

    )
    parser.add_argument(
        '--msk_sn_pin_save_path',
        default=None,
        help='path where the single pin masks with pins will be saved',

    )

# %% ../nbs/02_pin_map.ipynb #9c08cae8
def main():
    args = parse_args_()
    extract_pins(
        im_path=args.im_path,
        msk_path=args.msk_path,
        tmp_path=args.tmp_path,
        recipe_name=args.recipe_name,
        img_sn_pin_save_path=args.img_sn_pin_save_path,
        img_msk_pin_save_path=args.msk_sn_pin_save_path,
    )

# %% ../nbs/02_pin_map.ipynb #294050e0
#if __name__ == '__main__':
   #main() 
