# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/15_three_channel_data_prep.ipynb.

# %% auto #0
__all__ = ['recipe_wise_sorting']

# %% ../nbs/15_three_channel_data_prep.ipynb #b655859d
def recipe_wise_sorting(path:str):
    'group files based on recipe'
    recipes = []
    recipe_keys={}
    recipe_groups = ['108', '109', '122', '17', '18', '50', '51', '57', '68', '87']
    for j in recipe_groups:
        recipe_list  = []
        for i in im_src.ls():
            recipe = get_m_name(f'{i}')


            if recipe == j:
                recipe_list.append(i)
        recipe_keys[j] = recipe_list
    return recipe_keys
    
