"""Creating a three channel dataset for better training"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/000_three_channel_data_creation.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../../../nbs/000_three_channel_data_creation.ipynb #8bdc8e87
def foo(): pass
