# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/28_preprocessing.image_registration.ipynb.

# %% auto #0
__all__ = ['ETImageRegistration', 'to_gray', 'fallback_alignment', 'register_image', 'extract_tile', 'get_tile_positions',
           'extract_tiles', 'display_imgs']

# %% ../../nbs/28_preprocessing.image_registration.ipynb #8019d030
from pathlib import Path
from fastcore.all import *
import numpy as np
import os
import sys
import yaml
import cv2
from fastcore.imports import *
from PIL import Image
from dataclasses import dataclass
from skimage.registration import phase_cross_correlation
from typing import List, Tuple

# %% ../../nbs/28_preprocessing.image_registration.ipynb #25c36e52
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import math


# %% ../../nbs/28_preprocessing.image_registration.ipynb #5e41eab4
@dataclass
class ETImageRegistration:
    registered_test_et: np.ndarray
    rotation_deg: float
    translation_xy: tuple[float, float]
    transformation_matrix: np.ndarray # 2x3 affine s
    dice_after: float
    registration_ok: bool
    

# %% ../../nbs/28_preprocessing.image_registration.ipynb #d706cdf1
def to_gray(img: np.ndarray) -> np.ndarray:
    """Convert image to grayscale if it's not already."""
    return cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) if img.ndim == 3  else img

# %% ../../nbs/28_preprocessing.image_registration.ipynb #c5e4312a
from cv_tools.core import *
from cv_tools.image_alignment import *

# %% ../../nbs/28_preprocessing.image_registration.ipynb #4ee92672
from loguru import logger

# %% ../../nbs/28_preprocessing.image_registration.ipynb #598c8367
def fallback_alignment(
    ref_gray: np.ndarray,
    tst_gray: np.ndarray,
    angle_limit: float,
    upsample_factor: int
    ) -> tuple[np.ndarray, float, tuple[float, float]]:
    """Fallback alignment using phase correlation + Fourier-Mellin."""

    # Helper function to convert image to log-polar FFT representation
    # This transforms rotation into translation for easier detection
    def log_polar_fft(img):
        # Apply Hanning window to reduce edge artifacts in FFT
        # Outer product creates 2D window from 1D Hanning windows
        windowed_img = img * np.outer(
            np.hanning(img.shape[0]),  # Vertical window
            np.hanning(img.shape[1])   # Horizontal window
        )
        
        # Compute 2D FFT and shift zero frequency to center
        fft_result = np.fft.fftshift(np.fft.fft2(windowed_img))
        
        # Take absolute value to get magnitude spectrum
        magnitude = np.abs(fft_result)
        
        # Apply log transform to compress dynamic range (log1p = log(1+x))
        return np.log1p(magnitude)

    # Get image dimensions for coordinate calculations
    h, w = ref_gray.shape

    # Define center point for polar transformation
    center = (w//2, h//2)
    
    # Set flags for polar warping: logarithmic + fill empty areas
    flags = cv2.WARP_POLAR_LOG + cv2.WARP_FILL_OUTLIERS

    # Transform reference image to log-polar coordinates
    # This converts rotations to horizontal shifts
    ref_polar = cv2.warpPolar(
        log_polar_fft(ref_gray),  # Input: log-polar FFT of reference
        (360, 360),               # Output size: 360x360 pixels
        center,                   # Center point for transformation
        min(center) * 0.8,        # Radius (80% of min dimension)
        flags                     # Transformation flags
    )

    # Transform test image to log-polar coordinates using same parameters
    tst_polar = cv2.warpPolar(
        log_polar_fft(tst_gray),  # Input: log-polar FFT of test image
        (360, 360),               # Same output size as reference
        center,                   # Same center point
        min(center) * 0.8,        # Same radius
        flags                     # Same transformation flags
    )

    # Find shift between polar images using phase correlation
    # This detects rotation (as horizontal shift in polar space)
    shift, _, _ = phase_cross_correlation(
        ref_polar,                # Reference polar image
        tst_polar,                # Test polar image
        upsample_factor=upsample_factor  # Subpixel accuracy factor
    )

    # Convert horizontal shift in polar space back to rotation angle
    # shift[0] is horizontal shift, convert to degrees
    rot_deg = float(shift[0] * 360.0 / 360.0)

    # Handle angle wrapping: if rotation > limit, try opposite direction
    # This handles 180-degree ambiguity in rotation detection
    if abs(rot_deg) > angle_limit:
        rot_deg -= np.sign(rot_deg) * 180.0

    # Create rotation matrix around image center
    M_rot = cv2.getRotationMatrix2D(center, rot_deg, 1.0)

    # Apply rotation to test image to correct for detected rotation
    test_rotated = cv2.warpAffine(
        tst_gray,                 # Input test image
        M_rot,                    # Rotation transformation matrix
        (w, h),                   # Output size (same as input)
        flags=cv2.INTER_LINEAR,   # Linear interpolation
    )

    # Now find translation between reference and rotated test image
    # This detects remaining translation after rotation correction
    shift_t_, _, _ = phase_cross_correlation(
        ref_gray.astype(np.float32),      # Reference as float32
        test_rotated.astype(np.float32),  # Rotated test as float32
        upsample_factor=upsample_factor   # Subpixel accuracy
    )

    # Extract translation components (dx, dy)
    dx, dy = float(shift_t_[0]), float(shift_t_[1])

    # Build combined affine transformation matrix
    # This combines rotation and translation into single matrix
    angle_rad = np.deg2rad(-rot_deg)  # Convert to radians, negate for correct direction
    cos_a, sin_a = np.cos(angle_rad), np.sin(angle_rad)  # Trigonometric values
    cx, cy = center  # Center coordinates

    # Create 2x3 affine matrix: [rotation + translation]
    # Formula accounts for rotation around center point + final translation
    warp_matrix = np.float32([
        [cos_a, -sin_a, cx + dx - cx * cos_a + cy * sin_a],  # Row 1: x transformation
        [sin_a, cos_a, cy + dy - cx * sin_a - cy * cos_a]    # Row 2: y transformation
    ])

    # Return transformation matrix, rotation angle, and translation
    return warp_matrix, rot_deg, (dx, dy)


# %% ../../nbs/28_preprocessing.image_registration.ipynb #3345e7ec
def register_image(
    ref_im: np.ndarray,
    tst_im: np.ndarray,
    angle_limit: float = 6.0, # degrees
    upsample_factor: int = 20, # for subpixel accuracy
    use_fallback: bool = False, # kept for API compatibility, ignored - failures always return tst_im unchanged
    ) -> ETImageRegistration:
    """Register tst_im to ref_im using ECC.
    
    If ECC fails to converge OR rotation exceeds angle_limit:
        returns tst_im unchanged with registration_ok=False.
    Always returns ETImageRegistration with the same output format.
    """

    def _to_gray(img: np.ndarray) -> np.ndarray:
        """Convert image to grayscale if it's not already."""
        return cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) if img.ndim == 3 else img

    def _compute_ncc(ref_gray, tst_gray):
        # Resize tst to match ref if shapes differ
        if ref_gray.shape != tst_gray.shape:
            tst_gray = cv2.resize(tst_gray, (ref_gray.shape[1], ref_gray.shape[0]))
        ref_norm = ref_gray.astype(np.float32) / (ref_gray.max() + 1e-8)
        tst_norm = tst_gray.astype(np.float32) / (tst_gray.max() + 1e-8)
        return float(
            np.sum(ref_norm * tst_norm) / (
                np.sqrt(np.sum(ref_norm**2)) * np.sqrt(np.sum(tst_norm**2)) + 1e-8
            )
        )

    def _no_registration_result(reason: str) -> ETImageRegistration:
        """Return tst_im unchanged with registration_ok=False."""
        logger.warning(reason)
        ncc = _compute_ncc(ref_gray, tst_gray)
        logger.info(f'NCC: {ncc:.4f} (no registration applied)')
        return ETImageRegistration(
            registered_test_et=tst_im,
            rotation_deg=0.0,
            translation_xy=(0.0, 0.0),
            transformation_matrix=np.eye(2, 3, dtype=np.float32),
            dice_after=ncc,
            registration_ok=False
        )

    ref_gray = _to_gray(ref_im)
    tst_gray = _to_gray(tst_im)

    warp_matrix = np.eye(2, 3, dtype=np.float32)

    crit = (
        cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,
        1000, # max iterations
        1e-6  # convergence threshold
    )

    # Resize tst_gray to match ref_gray for ECC if shapes differ
    tst_gray_ecc = tst_gray
    if ref_gray.shape != tst_gray.shape:
        logger.warning(f'Image shapes differ: ref={ref_gray.shape}, tst={tst_gray.shape} - resizing tst for ECC')
        tst_gray_ecc = cv2.resize(tst_gray, (ref_gray.shape[1], ref_gray.shape[0]))

    logger.info('Step 1: ECC registration (Euclidean: rotation + translation)..')
    try:
        cc, warp_matrix = cv2.findTransformECC(
            ref_gray,
            tst_gray_ecc,
            warp_matrix,
            cv2.MOTION_EUCLIDEAN,
            crit,
            None,  # inputMask
            5      # gaussFiltSize
        )
    except cv2.error as e:
        logger.warning(f'ECC failed to converge: {e}')
        return _no_registration_result('ECC failed - returning tst_im unchanged')

    rot_deg = np.degrees(np.arctan2(warp_matrix[1, 0], warp_matrix[0, 0]))
    translation_xy = (warp_matrix[0, 2], warp_matrix[1, 2])
    logger.info(f'ECC correlation: {cc:.6f}')
    logger.info(f'Rotation: {rot_deg:.2f} degrees')
    logger.info(f'Translation dx: {translation_xy[0]:.3f}px, dy: {translation_xy[1]:.3f}px')

    if abs(rot_deg) > angle_limit:
        return _no_registration_result(
            f'Rotation {rot_deg:.2f} exceeds limit {angle_limit} - returning tst_im unchanged'
        )

    # Apply the transformation matrix to the test image
    h, w = ref_gray.shape[:2]
    rg_tst = cv2.warpAffine(
        tst_im,
        warp_matrix,
        (w, h),
        flags=cv2.INTER_LINEAR + cv2.WARP_INVERSE_MAP,
        borderMode=cv2.BORDER_REPLICATE
    )

    ncc = _compute_ncc(ref_gray, _to_gray(rg_tst))
    logger.info(f'NCC: {ncc:.4f} (1.0=perfect match, 0.0=no correlation)')
    return ETImageRegistration(
        registered_test_et=rg_tst,
        rotation_deg=rot_deg,
        translation_xy=translation_xy,
        transformation_matrix=warp_matrix,
        dice_after=ncc,
        registration_ok=ncc > 0.9
    )


# %% ../../nbs/28_preprocessing.image_registration.ipynb #7244a59a
def extract_tile(
    img: np.ndarray, # image
    y: int, # starting row position
    x: int, # starting column position
    tile_h: int, # tile height
    tile_w: int # tile width
) -> np.ndarray:
    """Extract a single tile from image."""
    return img[y:y+tile_h, x:x+tile_w].copy()

# %% ../../nbs/28_preprocessing.image_registration.ipynb #86c9399d
def get_tile_positions(
    img_h: int, # Image height
    img_w: int, # Image width
    tile_h: int, # Tile height
    tile_w: int, # Tile width
    stride_h: int = None, # Vertical stride (default: tile_h, no overlap)
    stride_w: int = None, # Horizontal stride (default: tile_w, no overlap)
    include_edges: bool = True # If True, add edge tiles to cover full image
) -> List[Tuple[int, int]]:
    """Calculate starting positions for all tiles.
    
        
        
    Example:
        >>> positions = get_tile_positions(512, 512, 256, 256, stride_h=128)
        >>> len(positions)  # 9 tiles with 50% overlap
    """
    stride_h = stride_h or tile_h
    stride_w = stride_w or tile_w
    
    positions = []
    for y in range(0, img_h - tile_h + 1, stride_h):
        for x in range(0, img_w - tile_w + 1, stride_w):
            positions.append((y, x))
    
    # Add edge tiles if image isn't perfectly divisible
    if include_edges:
        # Right edge
        if (img_w - tile_w) % stride_w != 0:
            for y in range(0, img_h - tile_h + 1, stride_h):
                positions.append((y, img_w - tile_w))
        # Bottom edge
        if (img_h - tile_h) % stride_h != 0:
            for x in range(0, img_w - tile_w + 1, stride_w):
                positions.append((img_h - tile_h, x))
        # Bottom-right corner
        if (img_h - tile_h) % stride_h != 0 and (img_w - tile_w) % stride_w != 0:
            positions.append((img_h - tile_h, img_w - tile_w))
    
    # Remove duplicates while preserving order
    seen = set()
    unique_positions = []
    for pos in positions:
        if pos not in seen:
            seen.add(pos)
            unique_positions.append(pos)
    
    return unique_positions

# %% ../../nbs/28_preprocessing.image_registration.ipynb #cfa186e7
def extract_tiles(
    img: np.ndarray,
    tile_h: int,
    tile_w: int,
    stride_h: int = None,
    stride_w: int = None,
    include_edges: bool = True
) -> Tuple[List[np.ndarray], List[Tuple[int, int]]]:
    """Extract all tiles from an image.
    
    Args:
        img: Input image [H, W] or [H, W, C]
        tile_h: Tile height
        tile_w: Tile width
        stride_h: Vertical stride
        stride_w: Horizontal stride
        include_edges: Include edge tiles
        
    Returns:
        tiles: List of tile arrays
        positions: List of (y, x) positions for each tile
        
    Example:
        >>> tiles, positions = extract_tiles(img, 256, 256, stride_h=128)
    """
    img_h, img_w = img.shape[:2]
    positions = get_tile_positions(
        img_h, img_w, tile_h, tile_w, 
        stride_h, stride_w, include_edges
    )
    
    tiles = [extract_tile(img, y, x, tile_h, tile_w) for y, x in positions]
    return tiles, positions

# %% ../../nbs/28_preprocessing.image_registration.ipynb #f7062c9a
def _to_display_img(img):
    """Convert img (numpy or torch.Tensor) to (H,W) uint8 for imshow."""
    if hasattr(img, 'detach'):  # PyTorch tensor
        arr = img.detach().cpu().numpy()
    else:
        arr = np.asarray(img, dtype=np.float32)
    # Handle 1D (e.g. phase_shift [dx,dy]) -> reshape to valid 2D for imshow
    if arr.ndim == 1:
        arr = arr.reshape(1, -1)  # (2,) -> (1,2) so imshow accepts it
    # Handle (B,C,H,W) or (C,H,W) -> take first, squeeze channels
    if arr.ndim == 4:
        arr = arr[0]
    if arr.ndim == 3:
        arr = arr.squeeze()
        if arr.ndim == 3 and arr.shape[0] in (1, 3):  # (C,H,W)
            arr = arr.transpose(1, 2, 0).squeeze()
    # Scale to 0-255 for display (handles arbitrary ranges)
    if arr.size > 0 and arr.max() > arr.min():
        arr = (arr - arr.min()) / (arr.max() - arr.min()) * 255
    else:
        arr = np.zeros_like(arr) if arr.size > 0 else np.array([[0]])
    return np.clip(arr, 0, 255).astype(np.uint8)


def display_imgs(
    images, # images
    scale=2, # scale
    COLS=5, # columns
    desc=None # description
    ):
    """Display images in a grid. Accepts numpy arrays or PyTorch tensors (B,C,H,W or C,H,W)."""
    DPI = float(mpl.rcParams['figure.dpi'])
    ROWS = math.ceil(len(images) / COLS)
    
    # Get h,w from first image (handle tensor layout)
    img0 = images[0]
    if hasattr(img0, 'detach'):
        shp = img0.detach().cpu().numpy().shape
    else:
        shp = np.asarray(img0).shape
    if len(shp) >= 3 and shp[0] in (1, 3):  # (C,H,W)
        h, w = shp[1], shp[2]
    else:
        h, w = shp[0], shp[1]
    
    fig, axs = plt.subplots(ROWS, COLS, figsize=((COLS * w * scale) / DPI, (ROWS * h * scale) / DPI))
    
    if desc is not None:
        fig.suptitle(desc, fontsize=10)
        
    axs = np.array([axs]).reshape(-1, COLS)
    for r in range(ROWS):
        for c in range(COLS):
            pos = (r * COLS) + c
            if pos < len(images):
                img = _to_display_img(images[pos])
                axs[r][c].imshow(img, cmap="gray", vmin=0, vmax=255)
                
            axs[r][c].xaxis.set_major_locator(ticker.NullLocator())
            axs[r][c].yaxis.set_major_locator(ticker.NullLocator())        
    fig.subplots_adjust(wspace=0.01, hspace=0.01)
    fig.tight_layout()
    return fig
