"""Image registration"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb.

# %% auto #0
__all__ = ['CV_TOOLS', 'custom_lib_path', 'CURRETNT_NB', 'ImageRegistration', 'parallel_image_registration', 'main_']

# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #8f2daa10
import sys
from pathlib import Path
from threading import Thread
from tqdm.auto import tqdm
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures import ProcessPoolExecutor
import concurrent.futures


# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #e88af279
CV_TOOLS = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools')
sys.path.append(str(CV_TOOLS))

# %% ../../../nbs/39_preprocessing.zero_degree_solder_pin.ipynb 6
custom_lib_path = Path(r'/home/ai_warstein/homes/goni/custom_libs')
sys.path.append(str(custom_lib_path))
from dotenv import load_dotenv

# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #2dc610ec
CV_TOOLS = Path(r'/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools')
sys.path.append(str(CV_TOOLS))


# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #477b4884
custom_lib_path = Path(r'/home/ai_warstein/homes/goni/custom_libs')
sys.path.append(str(custom_lib_path))


# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #a2c759d5
from cv_tools.imports import *
from cv_tools.core import *
from dotenv import load_dotenv
from fastcore.script import *
from fastcore.all import *


# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #12c7c24b
load_dotenv(dotenv_path=f'/home/ai_sintercra/homes/hasan/projects/git_data/new_test/new_test/.env')

# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #7d238100
class ImageRegistration:
    def __init__(
        self, 
        query_image_path, 
        ):
        store_attr()
        self.query_image = cv2.imread(str(self.query_image_path),0)
    __repr__ = basic_repr()

    def _align_images_ecc(self, test_img_path):
        test_image = cv2.imread(str(test_img_path),0)


        warp_mode = cv2.MOTION_EUCLIDEAN
        crit = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10000, 1e-10)

        # warp matrix
        warp_matrix = np.eye(2, 3, dtype=np.float32)

        # run optimization
        _, warp_matix = cv2.findTransformECC(
            self.query_image, 
            test_image, 
            warp_matrix, 
            warp_mode, crit, None,5)
        # Apply transformation
        h, w = self.query_image.shape
        aligned_image = cv2.warpAffine(
            test_image, 
            warp_matrix, 
            (w, h), 
            flags=cv2.INTER_LINEAR + cv2.WARP_INVERSE_MAP)
        
        ssim_score = self._check_alignment(aligned_image)
        if ssim_score < 0.9:
            print(f'SSIM score: {ssim_score}')
            return None

        return aligned_image

    def _check_alignment(self, aligned_image):
        ssim_score = cv2.matchTemplate(
            self.query_image,
            aligned_image, 
            cv2.TM_CCOEFF_NORMED)[0][0]
        print(f'SSIM score: {ssim_score}')
        return ssim_score


# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #9e6d565f
@patch_to(ImageRegistration)
def _align_images_orb(self, test_img_path):
    test_image = cv2.cvtColor(cv2.imread(str(test_img_path)), cv2.COLOR_BGR2GRAY)

    # Initialize feature detector (ORB is robust and faster than SIFT)
    orb = cv2.ORB_create(nfeatures=2000)
    
    # Find keypoints and descriptors
    kp1, des1 = orb.detectAndCompute(self.query_image, None)
    kp2, des2 = orb.detectAndCompute(test_image, None)
    
    # Create Brute Force Matcher with Hamming distance
    bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck=True)
    
    # Match descriptors
    matches = bf.match(des1, des2)
    
    # Sort matches by distance (best matches first)
    matches = sorted(matches, key=lambda x: x.distance)
    
    # Use top matches to find homography
    # Use at least 10 matches or 20% of all matches, whichever is higher
    num_good_matches = max(10, int(len(matches) * 0.2))
    good_matches = matches[:num_good_matches]
    
    # Extract location of good matches
    src_pts = np.float32([kp1[m.queryIdx].pt for m in good_matches]).reshape(-1, 1, 2)
    dst_pts = np.float32([kp2[m.trainIdx].pt for m in good_matches]).reshape(-1, 1, 2)
    
    # Find homography
    H, mask = cv2.findHomography(dst_pts, src_pts, cv2.RANSAC, 5.0)
    
    # Apply homography to align test image
    h, w = self.query_image.shape[:2]
    aligned_image = cv2.warpPerspective(test_image, H, (w, h))
    
    ssim_score = self._check_alignment(aligned_image)
    if ssim_score < 0.9:
        print(f'SSIM score: {ssim_score}')
        return None

    return aligned_image


# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #f84e9795
CURRETNT_NB='/home/ai_sintercra/homes/hasan/projects/git_data/new_test/nbs'

# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #f300823c
def parallel_image_registration(
    query_image_path, 
    search_folder, 
    output_folder=None,
    non_aligned_folder=None,
    method='ecc',
    similarity_threshold=0.9,
    max_workers=os.cpu_count(),
    file_extensions=('.jpg', '.jpeg', '.png', '.tif', '.tiff'
    )):
    """
    Parallely search images from a folder and apply image registration.
    
    Args:
        query_image_path: Path to the reference image
        search_folder: Folder containing images to be aligned
        output_folder: Folder to save aligned images (default: search_folder/aligned)
        non_aligned_folder: Folder to save images with similarity < threshold (default: search_folder/non_aligned)
        method: Registration method - 'ecc' or 'orb' (default: 'ecc')
        similarity_threshold: Minimum similarity score to consider successful alignment (default: 0.9)
        max_workers: Maximum number of parallel workers (default: number of CPU cores)
        file_extensions: Tuple of file extensions to process
    
    Returns:
        dict: Results with image paths and their similarity scores
    """
    # Setup paths
    search_folder = Path(search_folder)
    if output_folder is None:
        output_folder = search_folder / 'aligned'
    else:
        output_folder = Path(output_folder)
        
    if non_aligned_folder is None:
        non_aligned_folder = search_folder / 'non_aligned'
    else:
        non_aligned_folder = Path(non_aligned_folder)
    
    # Create output directories if they don't exist
    output_folder.mkdir(exist_ok=True, parents=True)
    non_aligned_folder.mkdir(exist_ok=True, parents=True)
    
    # Initialize image registration
    img_reg = ImageRegistration(query_image_path=query_image_path)
    
    # Get all image files
    image_files = [f for f in search_folder.glob('**/*') 
                  if f.is_file() and f.suffix.lower() in file_extensions]
    
    results = {}
    
    def process_image(img_path):
        try:
            # Skip if the file is in output or non_aligned folders
            if output_folder in img_path.parents or non_aligned_folder in img_path.parents:
                return None
            
            # Align image based on method
            if method.lower() == 'ecc':
                aligned_img = img_reg._align_images_ecc(img_path)
            else:
                aligned_img = img_reg._align_images_orb(img_path)
            
            # Calculate similarity score
            similarity = cv2.matchTemplate(img_reg.query_image, aligned_img, cv2.TM_CCOEFF_NORMED)[0][0]
            
            # Determine output path
            rel_path = img_path.relative_to(search_folder)
            if similarity >= similarity_threshold:
                out_path = output_folder / rel_path
            else:
                out_path = non_aligned_folder / rel_path
            
            # Create parent directories if needed
            out_path.parent.mkdir(exist_ok=True, parents=True)
            
            # Save aligned image
            cv2.imwrite(str(out_path), aligned_img)
            
            return (img_path, similarity, out_path)
        except Exception as e:
            print(f"Error processing {img_path}: {e}")
            return None
    
    # Process images in parallel
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(process_image, img_path): img_path for img_path in image_files}
        
        # Show progress bar
        for future in tqdm(concurrent.futures.as_completed(futures), total=len(image_files), desc="Aligning images"):
            result = future.result()
            if result:
                img_path, similarity, out_path = result
                results[str(img_path)] = {'similarity': similarity, 'output_path': str(out_path)}
    
    # Summary
    aligned_count = sum(1 for v in results.values() if v['similarity'] >= similarity_threshold)
    non_aligned_count = sum(1 for v in results.values() if v['similarity'] < similarity_threshold)
    
    print(f"Registration complete:")
    print(f"- Total images processed: {len(results)}")
    print(f"- Successfully aligned (similarity ≥ {similarity_threshold}): {aligned_count}")
    print(f"- Non-aligned (similarity < {similarity_threshold}): {non_aligned_count}")
    
    return results


# %% ../../../nbs/44_preprocessing.zero_degree_solder_pin.image_registration.ipynb #b9093eac
@call_parse
def main_(
    query_image_fn:Param("Path to the query image to use as reference")='query_image.png',
    search_folder:Param("Folder containing images to be aligned")='/search_folder',
    output_folder:Param("Folder to save aligned images", default=None)=None,
    non_aligned_folder:Param("Folder to save non-aligned images", default=None)=None,
    method:Param("Registration method to use", default='ecc')='ecc',
    similarity_threshold:Param("Minimum similarity score to consider an image aligned",type=float, default=0.9)=0.9,
    max_workers:Param("Number of parallel workers",type=int, default=os.cpu_count())=30,
    file_extensions:Param("File extensions to process", default=('.jpg', '.jpeg', '.png', '.tif', '.tiff'))='.png'
):
    parallel_image_registration(
        query_image_path=query_image_fn,
        search_folder=search_folder,
        output_folder=output_folder,
        non_aligned_folder=non_aligned_folder,
        method=method,
        similarity_threshold=similarity_threshold,
        max_workers=max_workers,
        file_extensions=file_extensions
    )

