# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_generate_image.ipynb.

# %% auto #0
__all__ = ['OpenCvImage', 'edit_image_old', 'augment_image', 'edit_image', 'edit_image_add_pin_folder',
           'generate_image_from_path', 'parse_args_', 'main_']

# %% ../../nbs/05_generate_image.ipynb #f36ee744
from typing import List, Dict, Union
import numpy as np
from pathlib import Path

import inspect
import os
import cv2
from argparse import ArgumentParser
import matplotlib as mpl
from typing import Tuple, List, Dict, Union, TypeVar, NewType
from tqdm.auto import tqdm
import numpy as np
from fastcore.all import *
import shutil
from argparse import ArgumentParser
import random

# %% ../../nbs/05_generate_image.ipynb #4f664196
sys.path.append('/home/ai_sintercra/homes/hasan/projects/git_data/cv_tools')
sys.path.append('/home/ai_sintercra/homes/hasan/projects/git_data/2023_easy_pin_detection')

# %% ../../nbs/05_generate_image.ipynb #fadcaa19
from cv_tools.core import *

# %% ../../nbs/05_generate_image.ipynb #44208798
from new_test.pin_map import *
from new_test.core import *

# %% ../../nbs/05_generate_image.ipynb #e856057d
OpenCvImage = NewType('OpenCvImage', np.ndarray)

# %% ../../nbs/05_generate_image.ipynb #69a09d85
def edit_image_old(
        img:OpenCvImage,
        msk:OpenCvImage,
        tmp_img:OpenCvImage,
        recipe_no:str,
        new_part:OpenCvImage,
        msk_part:OpenCvImage,
        ):
    'Change image based on case'
    num_cols_ = split_image_no()[recipe_no]
    pin_map_func = f'pin_map{recipe_no}'

    last_img = img.copy()
    last_msk = msk.copy()
    pin_index_func = globals()[pin_map_func]

    all_cols = []
    num_cols = len(pin_index_func().keys())

    # getting the bounding box coordinates of all columns
    # regarding the recipe no
    bbox_func = globals()[f'get_all_columns_{recipe_no}']
    col_bbox = bbox_func(
        tst_img=img,
        tmp_img=tmp_img
    )



    for col_no in range(num_cols):

        # for each column get the bounding box coordinates
        col_bbox_coord = col_bbox[col_no]
        col_data = img[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]]
        col_data_msk = msk[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]]
        

        parts_ = split_image_with_coordinates(
            img=col_data,
            num_splits=num_cols_,
            direction='vertical'
            )

        msk_parts_ = split_image_with_coordinates(
                img=col_data_msk,
                num_splits=num_cols_,
                direction='vertical'
                )
        # getting indexes where pin is there
        pin_indexes = pin_index_func()[col_no]

        all_parts = []
        for (i, part, k),(mi, mpart, mk) in zip(parts_, msk_parts_):
            if recipe_no == '37':
                col_nos = [4,5,6]
            else:
                col_nos = [3,4,5,6]
            if (i not in pin_indexes) \
                and (i not in col_nos):
                # Replace the part with the new part
                # first changing the new_part shape to actual part shape
                try:
                    added_img = create_same_shape(
                                            src_img=part,
                                            dst_img=new_part
                                        )
                    if msk_part is not None:
                        added_img_msk = create_same_shape(
                                                src_img=mpart,
                                                dst_img=msk_part,
                                            )
                    #part = added_img
                    start_x, start_y, end_x, end_y = k
                    center = ((start_x + end_x) // 2, (start_y + end_y) // 2)
                    col_data = seamless_clone(
                        full_img=col_data,
                        replace_part=added_img,
                        center=center
                    )
                    if msk_part is not None:
                        col_data_msk = seamless_clone(
                            full_img=col_data_msk,
                            replace_part=added_img_msk,
                            center=center
                        )
                except Exception as e:
                    print(e)
            #else:
                #part = part

            #all_parts.append(part)

        
        last_img[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]] = col_data
        if msk_part is not None:
            last_msk[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]] = col_data_msk


    return last_img, last_msk

# %% ../../nbs/05_generate_image.ipynb #b0095de9
def augment_image(image, augmentation=None):
    """
    Randomly augment the input image with a 50% chance.
    Possible augmentations: brightness change, noise, blur, or sharpen.
    """
    if random.random() < 0.5:
        return image  # No augmentation 50% of the time
    if augmentation is None:
        augmentation = random.choice(['brightness', 'noise', 'blur', 'sharpen'])
    
    if augmentation == 'brightness':
        factor = random.uniform(0.3, 1.3)
        return cv2.convertScaleAbs(image, alpha=factor, beta=0)
    elif augmentation == 'noise':
        noise = np.random.uniform(0, 1, image.shape).astype(np.uint8)
        return cv2.add(image, noise)
    elif augmentation == 'blur':
        
        return cv2.GaussianBlur(image, (5, 5), 0)
    elif augmentation == 'sharpen':
        kernel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]])
        return cv2.filter2D(image, -1, kernel)

# %% ../../nbs/05_generate_image.ipynb #8ab49ed7
def edit_image(
        img:OpenCvImage,
        msk:OpenCvImage,
        tmp_img:OpenCvImage,
        recipe_no:str,
        new_part:OpenCvImage,
        msk_part:OpenCvImage,
        ):
    'Change image based on case'
    num_cols_ = split_image_no()[recipe_no]
    pin_map_func = f'pin_map{recipe_no}'

    last_img = img.copy()
    last_msk = msk.copy()
    pin_index_func = globals()[pin_map_func]

    all_cols = []
    num_cols = len(pin_index_func().keys())

    # getting the bounding box coordinates of all columns
    # regarding the recipe no
    bbox_func = globals()[f'get_all_columns_{recipe_no}']
    col_bbox = bbox_func(
        tst_img=img,
        tmp_img=tmp_img
    )


    pin_type = get_pin_type()[recipe_no]
    if '1B' in pin_type:
        col_nos=[1,2,3]
    elif pin_type == '97':
        col_nos = [3,4,5]
    else:
        col_nos=[3,4,5]

    for col_no in range(num_cols):

        # for each column get the bounding box coordinates
        col_bbox_coord = col_bbox[col_no]
        col_data = img[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]]
        col_data_msk = msk[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]]
        

        parts_ = split_image_with_coordinates(
            img=col_data,
            num_splits=num_cols_,
            direction='vertical'
            )

        msk_parts_ = split_image_with_coordinates(
                img=col_data_msk,
                num_splits=num_cols_,
                direction='vertical'
                )
        # getting indexes where pin is there
        pin_indexes = pin_index_func()[col_no]

        all_parts = []
        for (i, part, k),(mi, mpart, mk) in zip(parts_, msk_parts_):
            if (i not in pin_indexes) \
                and (col_no not in col_nos):
                # Replace the part with the new part
                # first changing the new_part shape to actual part shape
                try:
                    added_img = create_same_shape(
                                            src_img=part,
                                            dst_img=new_part
                                        )
                    added_img = augment_image(added_img)
                    if msk_part is not None:
                        added_img_msk = create_same_shape(
                                                src_img=mpart,
                                                dst_img=msk_part,
                                            )
                    #part = added_img
                    start_x, start_y, end_x, end_y = k
                    center = ((start_x + end_x) // 2, (start_y + end_y) // 2)
                    col_data = seamless_clone(
                        full_img=col_data,
                        replace_part=added_img,
                        center=center
                    )
                    if msk_part is not None:
                        col_data_msk = seamless_clone(
                            full_img=col_data_msk,
                            replace_part=added_img_msk,
                            center=center
                        )
                except Exception as e:
                    print(e)
            #else:
                #part = part

            #all_parts.append(part)

        
        last_img[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]] = col_data
        if msk_part is not None:
            last_msk[col_bbox_coord[0]:col_bbox_coord[1], col_bbox_coord[2]:col_bbox_coord[3]] = col_data_msk


    return last_img, last_msk

# %% ../../nbs/05_generate_image.ipynb #83746b06
def edit_image_add_pin_folder(
        img:OpenCvImage,
        tmp_img:OpenCvImage,
        msk:OpenCvImage,
        new_part_folder:Union[str,Path], # loop through each image in this pin folder (each single pin all be added in a image)
        new_msk_part_folder:Union[str,Path]=None, # loop thorugh each mask fodler but name will be new_part folder, if it is None, then just empty mask will be created
        recipe_no:str='17',
        show:bool=False,
        gen_im_path:Union[Path, str]=None,
        gen_msk_path:Union[Path, str]=None,
        fn=None # when loop through each image, the name of main image will be same, to make sure different images are created, idx is added inside name
    ):
    'Create image based from all pins insider new_part_folder'
    try:
        new_part_folder = Path(new_part_folder)
        new_part_fns = new_part_folder.ls()
    except Exception as e:
        print(e)
    if len(new_part_fns) >=1:
        for idx, i in tqdm(enumerate(new_part_fns), total=len(new_part_fns)):
            name_= Path(i).name
            new_part = read_img(i, cv=True)
            if new_msk_part_folder is None:
                new_msk_part = np.zeros_like(new_part)
            else:
                new_msk_part = read_img(Path(new_msk_part_folder, name_), cv=True)
            new_img, new_msk = edit_image(
                img=img, 
                msk=msk,
                tmp_img=tmp_img,
                recipe_no=recipe_no,
                new_part=new_part,
                msk_part=new_msk_part
            )
            if show:
                show_(new_img)
            if gen_im_path is not None:
                # create folder if its not there
                Path(gen_im_path).mkdir(exist_ok=True, parents=True)

                cv2.imwrite(f'{gen_im_path}/{fn}_gen_image_{idx}_{name_}',new_img)
            if gen_msk_path is not None:
                # create folder if its not there
                Path(gen_msk_path).mkdir(exist_ok=True, parents=True)
                cv2.imwrite(f'{gen_msk_path}/{fn}_gen_image_{idx}_{name_}',new_msk)




# %% ../../nbs/05_generate_image.ipynb #da3e73c7
def generate_image_from_path(
        im_path:Union[Path,str],
        msk_path:Union[Path,str],
        tmp_path:Union[Path,str],
        add_pin_path:Union[Path,str],
        add_msk_path:Union[Path,str]=None,
        gen_im_path:Union[Path, str]=None,
        gen_msk_path:Union[Path, str]=None,
      ):
        'Generate images based on failed imges'

        im_path = Path(im_path)
        for idx, i in enumerate(im_path.ls()):
                recipe_no = get_m_name(f'{i}')
                name_ = Path(i).name
                img = read_img(i, cv=True)
                try:
                        msk = read_img(f'{msk_path}/{name_}', cv=True)
                except Exception as e:
                        print(e)
                        print('No mask found')

                tmp_img = read_img(f'{tmp_path}/{recipe_no}.png', cv=True)

                edit_image_add_pin_folder(
                        img=img,
                        tmp_img=tmp_img,
                        msk=msk,
                        new_part_folder=add_pin_path,
                        new_msk_part_folder=add_msk_path,
                        recipe_no=recipe_no,
                        show=False,
                        gen_im_path=gen_im_path,
                        gen_msk_path=gen_msk_path,
                        fn=f'src_img_recipe_{recipe_no}_idx_{idx}',
                )




# %% ../../nbs/05_generate_image.ipynb #daf32fb6
def parse_args_():
    parser = ArgumentParser()
    parser.add_argument(
        "--im_path",
        type=str,
        required=True,
        help="Path to images, this image will be used to generate new images[this image + addtional pins]"
    )
    parser.add_argument(
        "--msk_path",
        type=str,
        default=None,
        help="Path to masks, this mask will be used to generate new masks"
    )
    parser.add_argument(
        "--tmp_path",
        type=str,
        required=True,
        help="Path to tmp image, this is the template image"
    )
    parser.add_argument(
        "--add_pin_path",
        type=str,
        required=True,
        help="Path to additional pins, this will be used to generate new images"
    )
    parser.add_argument(
        "--add_msk_path",
        default=None,
        help="In case of mask is available, missing pin case, then mask will be created, otherwise empty masks will be created "
    )
    parser.add_argument(
        "--gen_im_path",
        type=str,
        default=None,
        required=False,
        help="Path to saved generated images"
    )

    parser.add_argument(
        "--gen_msk_path",
        type=str,
        required=False,
        default=None,
        help="Path to saved generated masks"
    )
    parser.add_argument(
        "--show",
        type=bool,
        required=False,
        help="Show generated images if True"
    )
    return parser.parse_args()

# %% ../../nbs/05_generate_image.ipynb #9615331f
def main_():
    args = parse_args_()
    generate_image_from_path(
        im_path=Path(args.im_path),
        msk_path=Path(args.msk_path),
        tmp_path=Path(args.tmp_path),
        add_pin_path=Path(args.add_pin_path),
        add_msk_path=args.add_msk_path,
        gen_im_path=Path(args.gen_im_path),
        gen_msk_path=Path(args.gen_msk_path)
    )


# %% ../../nbs/05_generate_image.ipynb #66945063
if __name__ == '__main__':
    main_()
